"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered where your new red blood cells", "open", "Where do new red blood cells come from?"),
 ("has no nucleus and cannot divide", "nonuc", "Mature human red blood cell: no nucleus; cannot divide"),
 ("worn-out ones are removed", "worn", "Worn-out cells removed; new ones arrive"),
 ("Your skin tells the same story", "skin", "Skin: the same story"),
 ("lost from its surface every day", "lost", "Surface cells flake away"),
 ("a graze leaves a gap", "graze", "A graze leaves a gap"),
 ("keep making the replacements", "q", "Where do the new cells come from?"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("say what makes a cell a stem cell", "l1", ""),
 ("outline how stem cells replace lost cells", "l2", ""),
 ("using bone marrow and skin", "l2b", ""),
 ("keep two words apart", "l3", ""),
],
3: [
 ("First, a quick recall", "open", "Recall: what mitosis gives (5.2.1, 5.1.2)"),
 ("Mitosis gives two nuclei", "tel", "Two new nuclei"),
 ("the same number of chromosomes", "num", "Same number of chromosomes as the parent nucleus"),
 ("the same genetic information", "info", "Same genetic information"),
 ("after cytokinesis", "cyto", "Cytokinesis: two genetically identical cells"),
 ("for growth", "growth", "New cells for growth"),
 ("replacement and repair", "repl", "…and for replacement and repair"),
 ("many cells specialise and stop dividing", "stop", "Many cells specialise and stop dividing"),
 ("which cells do the dividing", "q", "Which cells divide to replace them?"),
],
4: [
 ("In the tissues we follow here", "open", "The tissues we follow here"),
 ("the answer is stem cells", "stem", "Stem cells"),
 ("A stem cell is unspecialised", "unsp", "Unspecialised: no particular job yet"),
 ("divide by mitosis again and again", "div", "Divides by mitosis"),
 ("keeping a supply of stem cells", "keep", "Keeps a supply of stem cells"),
 ("that is self-renewal", "self", "Self-renewal"),
 ("can also differentiate", "diff", "Daughter cells can differentiate"),
 ("with a structure suited to one function", "spec", "Specialised cell"),
 ("like the stem of a plant", "handle", "Handle: the stem is where the branches start"),
 ("Written properly", "wp", "Written properly"),
 ("some of its daughter cells differentiate", "c2", ""),
],
5: [
 ("Here is one in the bone marrow", "open", "Bone marrow"),
 ("Watch it divide by mitosis", "div", "It divides by mitosis"),
 ("In one possible pattern", "pattern", "One possible pattern"),
 ("one daughter remains a stem cell", "stay", "One daughter: stays a stem cell"),
 ("the other goes on to differentiate", "diff", "The other: differentiates"),
 ("several intermediate stages", "inter", "Intermediate stages"),
 ("filling with haemoglobin", "hb", "Filling with haemoglobin"),
 ("loses its nucleus", "nuc", "Nucleus lost"),
 ("It enters the blood", "blood", "Into the blood"),
 ("completes its maturation", "mature", "Mature human red blood cell: no nucleus"),
 ("about four months", "life", "Typical lifespan: about four months"),
],
6: [
 ("The same idea runs in your skin", "open", "Skin"),
 ("Stem cells in the base layer", "base", "Base layer: stem cells"),
 ("keep dividing by mitosis", "div", "Base-layer cells divide by mitosis"),
 ("Daughter cells that move upwards differentiate", "up", "Daughters move up and differentiate"),
 ("lost from the surface", "lost", "Lost from the surface"),
 ("the base layer carries on", "carry", "The base layer carries on"),
 ("After a graze", "graze", "A graze"),
 ("extra divisions there", "extra", "Extra divisions beneath the graze"),
 ("help replace the lost cells", "fill", "New cells fill the gap"),
 ("that is tissue repair", "repair", "Tissue repair"),
 ("Notice the two separate steps", "two", "Two separate steps"),
 ("Mitosis makes new cells", "mit", "Mitosis: new cells, genetically identical"),
 ("Differentiation makes them specialised", "dif", "Differentiation: specialised cells"),
],
7: [
 ("So here it is", "open", "What I told you, on the lineage"),
 ("on the diagram you watched", "settle", ""),
 ("A stem cell is unspecialised", "unsp", "Unspecialised"),
 ("divides by mitosis", "mit", "Divides by mitosis"),
 ("Self-renewal keeps the supply", "self", "Self-renewal keeps the supply"),
 ("Some daughters differentiate", "diff", "Some daughters differentiate"),
 ("through intermediate stages", "inter", "Through intermediate stages"),
 ("a red blood cell that loses its nucleus", "rbc", "Red blood cell: nucleus lost"),
 ("a flattened skin cell", "skin", "Flattened skin cell"),
 ("replace lost cells and repair tissue", "end", "Replacement and repair"),
],
8: [
 ("How does this reach you?", "open", "How it is asked"),
 ("The command word is outline", "r1", "Outline: the main points, clearly linked"),
 ("clearly linked", "linked", ""),
 ("One multiple-choice question", "r2", "w22_13 Q20: skin stem cells + the Golgi body"),
 ("with the Golgi body", "golgi", ""),
 ("Beyond the mark scheme", "beyond", "Beyond the mark scheme"),
 ("marrow stem cells divide by mitosis", "bmit", ""),
 ("daughters differentiate into red blood cells", "bdiff", ""),
 ("The card keeps the order", "reject", "The reject card"),
 ("mitosis first", "first", "Mitosis first…"),
 ("then differentiation", "then", "…then differentiation"),
],
}
