"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues plus visual-only cues
that break long holds (recorded in qa/cue-additions.md). '^' marks the trigger word inside a
phrase that is matched whole for uniqueness. An empty caption keeps the previous caption.
Captions are look-here anchors, never the narration re-typed."""
PLANS = {
1: [
 ("Ever wondered", "open", "Four clear liquids. What is in each tube?"),
 ("Here are four test tubes", "rack", "Four tubes, labelled only 1 · 2 · 3 · 4"),
 ("One is water", "w1", ""),
 ("One has sugar dissolved", "w2", ""),
 ("one protein", "w3", ""),
 ("one starch", "w4", "All four colourless: nothing tells them apart"),
 ("nothing your eyes can do", "eye", "Looking is not enough"),
 ("handed tubes like these", "bench", "Paper 3: tubes, labelled bottles, a water bath"),
 ("You do it by giving each tube the conditions", "dropper", "Give the tube the conditions for one class"),
 ("shows itself", "flash", "The class shows itself as a visible change (model)"),
],
2: [
 ("This is a section", "open", "Syllabus 2.1.1"),
 ("describe and carry out", "outcome", "Command words: describe and CARRY OUT"),
 ("Paper 3 can require you", "paper3", "Paper 3: you do the tests yourself"),
 ("labelled bottles", "i1", ""),
 ("a water bath", "i2", ""),
 ("unknown solutions", "i3", ""),
 ("your own hands", "i4", "Labelled bottles · water bath · unknowns · your hands"),
 ("every object on that bench", "preview", "Know every object on the bench"),
 ("why each step is done the way it is", "reason", "Every step has a reason"),
 ("read a result that went wrong", "wrong", "The reason is what lets you read a doubtful result"),
],
3: [
 ("By the end of this", "open", "What you will be able to do"),
 ("describe and carry out the Benedict's test", "l1", ""),
 ("the iodine test for starch", "l1b", ""),
 ("the emulsion test for lipids", "l1c", ""),
 ("the biuret test for proteins", "l1d", ""),
 ("record what you observe", "l2", ""),
 ("infer what each result means", "l2b", ""),
 ("look at a doubtful result", "l3", ""),
 ("before you conclude anything", "l3b", ""),
],
4: [
 ("Before any apparatus", "open", "One idea before any apparatus"),
 ("makes something in the sample show itself", "schem", "The test makes something in the sample visible"),
 ("You give the tube the conditions", "cond", "Conditions go in"),
 ("for reducing sugars, copper ions in excess and heat", "r1", "Four tests, four readouts"),
 ("for starch, iodine", "r2", ""),
 ("for lipids, ethanol and then water", "r3", ""),
 ("for proteins, alkali and copper", "r4", ""),
 ("Then you record what you see", "rec", "Record what you see"),
 ("a colour or a cloudiness", "cloud", "Emulsion: cloudiness, not a colour reaction"),
 ("only then do you say what class", "infer", "Only then: which class it points to"),
 ("Conditions, observation, inference", "coi", "CONDITIONS → OBSERVATION → INFERENCE"),
 ("a control beside it", "control", "A control shows what unchanged looks like"),
],
5: [
 ("Start at the rack", "rack", "Test-tube rack: front centre"),
 ("Label each tube", "label", "Label every tube before use"),
 ("the syringe or measuring cylinder", "syringe", "Syringe / measuring cylinder: measure volumes"),
 ("its own dropper pipette", "dropper", "One dropper pipette per reagent"),
 ("The water bath is at the back right", "bath", "Water bath + thermometer: back right"),
 ("use the holder", "holder", "Test-tube holder for hot tubes"),
 ("Read colours against the white tile", "tile", "White tile: front left"),
 ("Put your eye protection on", "goggles", "Eye protection on before any bottle opens"),
 ("The labelled reagents wait at the back left", "reagents", "Labelled reagents: back left"),
 ("distilled water is there for rinsing and controls", "water", "Distilled water: rinsing and controls · waste far right"),
 ("You will meet each reagent", "meet", "Each reagent is introduced when its test begins"),
],
6: [
 ("Start with Benedict's", "open", "Benedict's test for reducing sugars"),
 ("Eye protection on", "goggles", "Eye protection: Benedict's is harmful / irritant"),
 ("Label a tube", "label", "Label the tube"),
 ("two cubic centimetres of the sample", "sample", "Measure the sample: do not guess"),
 ("Now the reagent", "reagent", "Now the reagent"),
 ("Use Benedict's solution in excess", "excess", "Benedict's solution in excess"),
 ("Benedict's contains copper", "cu", "Cu²⁺ ions react with a reducing sugar"),
 ("if the reagent runs out before the sugar does", "cutaway", "Reagent used up: colour no longer reports the sample"),
 ("the colour tells you about the reagent", "cutaway2", "Copper in excess: colour reports the sample"),
 ("Here we illustrate", "illus", "Example volumes, not a guarantee of chemical excess"),
 ("Equal volumes alone do not establish chemical excess", "conc", "Volume is not the same as amount: concentration matters"),
 ("Follow the supplied practical's amounts", "follow", "Follow the supplied practical's amounts"),
 ("an equal or greater volume of Benedict's than sample", "ms", "Mark scheme: equal or greater volume of Benedict's"),
 ("Shake gently to mix", "shake", "Shake gently to mix"),
],
7: [
 ("Now heat", "open", "Benedict's needs heat"),
 ("Put the tube in the water bath", "bath", "Water bath at 80 °C or above"),
 ("the cited practical uses a boiling water bath", "boiling", "The cited practical: a boiling water bath"),
 ("Not a Bunsen flame straight on the tube", "flameX", "WRONG METHOD: flame straight on the tube"),
 ("a flame heats one spot", "spot", ""),
 ("the liquid can spit out", "spit", ""),
 ("you cannot say what temperature it reached", "notemp", "Uneven heating · spitting · no temperature"),
 ("we heat for four minutes", "timer", "Heat for a stated time: here, 4 minutes"),
 ("in an exam, follow the supplied method", "follow", "In an exam: follow the supplied method"),
 ("Lift the tube out with the holder", "lift", "Hot: holder, not fingers"),
 ("against the white tile", "tile", "Read the colour against the white tile"),
],
8: [
 ("Here is what you may see", "open", "Reading the Benedict's result"),
 ("Blue is the reagent", "blue", "Blue: the reagent's own colour"),
 ("negative under these conditions", "neg", "Still blue after heating: negative under these conditions"),
 ("may appear green", "g", "Positive results: separate tubes, same heating"),
 ("green, ^yellow, orange", "y", ""),
 ("yellow, ^orange or", "o", ""),
 ("orange or ^brick-red", "br", ""),
 ("with a precipitate", "ppt", "Precipitate: a solid"),
 ("first clouds the liquid", "susp", "Precipitate first suspended in the liquid"),
 ("and then settles", "settle", "…then settles as a layer"),
 ("It need not show every colour in sequence", "sep", "Separate endpoint tubes, not one tube's journey"),
 ("Say the colour you saw", "say", "Observation in words; then the inference"),
 ("say precipitate if there was one", "sayppt", ""),
 ("Green and yellow are positive results", "pos", "Green and yellow are positive too"),
 ("more reducing sugar gives a colour further along", "further", "Standards heated alike: more sugar, further along"),
 ("which is the next lesson", "next", "Standards and comparisons: next lesson (2.1.2)"),
 ("And red is one end of the row", "redend", "Brick-red: one end of the row, not the only positive"),
],
9: [
 ("Two more tubes go through the same heating", "open", "Controls: same heating, every time"),
 ("One with distilled water", "W", "W: distilled water instead of sample"),
 ("it should stay blue", "Wblue", "Negative control stays blue"),
 ("check the tube, the pipette and the reagent", "Wcheck", "If W changes: check before trusting anything"),
 ("One with a solution you know contains a reducing sugar", "G", "G: a known reducing sugar (glucose)"),
 ("it should change", "Gchange", "Positive control changes"),
 ("check the control solution, the volumes", "Gcheck", "If G stays blue: check before trusting anything"),
 ("Those are your negative and positive controls", "tags", "Negative control · positive control"),
 ("Now what the result means", "means", "What a positive result means"),
 ("Blue to orange tells you", "detected", "Inference: reducing sugar detected"),
 ("It does not tell you which one", "which", "Which reducing sugar? Not established"),
 ("glucose, fructose and maltose all give it", "three", "Different reducing sugars, same kind of result"),
 ("So write", "card", "Name the class: reducing sugar"),
],
10: [
 ("The iodine test is the quick one", "open", "Iodine test for starch"),
 ("it needs no heat", "noheat", "No heating"),
 ("Put a little of the sample on a white tile", "spot", "A little sample on the white tile"),
 ("add a few drops of iodine", "drops", "A few drops of iodine in potassium iodide solution"),
 ("The solution itself is orange-brown", "ob", "The reagent: orange-brown"),
 ("it turns blue-black", "bb", "Starch present: blue-black"),
 ("you write both words", "both", "Write both words: blue-black"),
 ("the observation the mark scheme wants", "ms", ""),
 ("If it stays orange-brown", "neg", "Stays orange-brown: negative under these conditions"),
 ("do a water control alongside", "controls", "Water control beside a known starch control"),
 ("keep the iodine pipette for iodine only", "pipette", "The iodine pipette goes back to the iodine bottle"),
 ("cross-contamination can change the colour", "xinset", "WRONG METHOD: a shared pipette carries reagent across"),
 ("make the result unreliable", "end", "One pipette per reagent"),
],
11: [
 ("Lipids are made visible a different way", "open", "Emulsion test for lipids"),
 ("uses cloudiness rather than a colour reaction", "row3", "Readout: cloudiness, not a colour reaction"),
 ("it rests on solubility", "sol", "It rests on solubility"),
 ("dissolve much more readily in ethanol than in water", "dissolve", "This example: far more soluble in ethanol than in water"),
 ("Before the ethanol bottle opens", "before", "Before the ethanol opens"),
 ("extinguish the Bunsen", "off", "Extinguish the Bunsen"),
 ("keep the ethanol away from any ignition source", "flam", "Ethanol is flammable: no naked flames"),
 ("an electric water bath", "elec", "An electric water bath keeps flames off the bench"),
 ("put a small amount of the sample in a dry tube", "L", "A small amount of sample in a dry tube"),
 ("about two cubic centimetres here", "eth", "Ethanol: the amount your method specifies"),
 ("stopper it and shake well", "shake", "Stopper and shake: extract the lipid"),
 ("If solid particles remain", "particles", "Solid particles?"),
 ("let them settle", "settle", "Let solids settle"),
 ("the clear ethanolic extract", "extract", "Pour only the clear ethanolic extract"),
],
12: [
 ("pour that clear extract into a tube of water", "pour", "Clear extract into water"),
 ("about the same volume, and shake again", "shake", "About the same volume · shake again"),
 ("The ethanol mixes into the water", "mix", "Ethanol mixes with the water"),
 ("comes out of solution as tiny droplets", "drops", "Lipid comes out as tiny droplets"),
 ("the tube goes cloudy white", "cloudy", "Cloudy white emulsion"),
 ("That cloudy white emulsion is a positive result", "pos", "Inference: lipid present"),
 ("A clear tube is negative", "neg", "Clear: negative under these conditions"),
 ("Run a blank of ethanol and water", "blank", "Blank: ethanol + water, no sample"),
 ("not mistaken for an emulsion", "haze", "The blank shows any haze from the reagents"),
 ("Water first can prevent effective extraction", "xinset", "WRONG METHOD: water added to the sample first"),
 ("the exam has asked for the order", "order", "The credited order"),
 ("the credited one is", "cite", ""),
 ("then into water and shake again", "step2", ""),
 ("cloudy means lipid", "final", "Ethanol and shake → into water and shake → cloudy = lipid"),
],
13: [
 ("Now protein", "open", "Biuret test for proteins"),
 ("a single bottle of biuret reagent", "single", "One bottle: follow the supplied protocol"),
 ("as two bottles", "two", "Or two bottles (June 2021 practical)"),
 ("five percent potassium hydroxide", "koh", ""),
 ("zero point one five percent copper sulfate", "cuso4", "Concentrations as supplied"),
 ("the order is alkali first", "order", "Order: alkali first"),
 ("Measure one cubic centimetre of the sample", "s", "1 cm³ sample"),
 ("add one cubic centimetre of the potassium hydroxide", "p", "1 cm³ potassium hydroxide"),
 ("which is an irritant", "irr", "KOH is an irritant: eye protection stays on"),
 ("and shake gently, then", "shake1", ""),
 ("then add one cubic centimetre of the copper sulfate", "c", "1 cm³ copper sulfate"),
 ("shake gently again", "shake2", ""),
 ("The violet colour only develops in alkaline conditions", "xinset", "WRONG METHOD: copper sulfate with no alkali"),
 ("which is why the alkali goes in first", "correct", "Alkali first, then copper sulfate"),
 ("No heating", "noheat", "No heating"),
 ("Leave it at least a minute", "timer", "Leave at least 1 minute"),
],
14: [
 ("Hold it against the white tile", "tile", "Read against the white tile"),
 ("The reagent is blue", "blue", "The reagent: blue"),
 ("turns to a lilac, purple or violet colour", "violet", "Protein present: lilac / purple / violet"),
 ("the mark scheme accepts any of those words", "ms", "Mark scheme: violet / AW"),
 ("If it stays blue", "neg", "Stays blue: negative under these conditions"),
 ("the reagent's own blue, not no colour", "own", "Negative = the reagent's own blue"),
 ("Run a known protein and a water tube", "controls", "Controls: known protein · water"),
 ("What is it detecting", "what", "What does biuret detect?"),
 ("detects peptide bonds in proteins", "peptide", "Peptide bonds"),
 ("at least two peptide bonds", "ring", "At least two peptide bonds"),
 ("Free amino acids give no violet colour", "aa", "Free amino acids: no violet result"),
 ("the reagent remains blue", "remains", ""),
 ("So write", "card", "Name the class: protein"),
],
15: [
 ("Every one of those results goes into a table", "open", "Recording: the results table"),
 ("the table is marked", "marked", "The table itself earns marks"),
 ("the sample, which test was done, what you observed", "headings", "sample | test | observation"),
 ("only then what it supports", "inf", "…then the supported inference"),
 ("Under observation you write what you saw", "obs", "Observation: what you saw, in words"),
 ("for every test you actually did on every tube", "rows", "Every test you actually did"),
 ("a precipitate or an emulsion", "pe", "Colour, plus precipitate or emulsion"),
 ("including tubes that stayed blue", "blue", "A negative is a result"),
 ("A test you did not do", "nt", "Not done → “not tested”"),
 ("In June 2021 each solution contained one or none", "design", "June 2021: one or none of the three classes"),
 ("tested for protein first", "protein", "Protein test on all four first"),
 ("stopped testing a tube once it was identified", "stop", "Discard · rinse · fresh sample for the next test"),
 ("four protein results", "counts", "4 + 3 + 2 results"),
 ("none of the three tested classes detected", "none", "“None” = none of the three tested classes"),
],
16: [
 ("Real samples can be mixtures", "open", "A mixture"),
 ("Solution U in June 2021", "U", "Solution U (June 2021)"),
 ("from separate fresh portions", "pour", "Three separate fresh portions"),
 ("it gave violet, blue, and blue-black", "swatches", "Three observations"),
 ("Read that as three observations", "rows", "One row per test"),
 ("protein detected", "r1", ""),
 ("no reducing sugar detected", "r2", ""),
 ("starch detected", "r3", ""),
 ("So U contains protein and starch", "inf", "U: protein and starch"),
 ("a fresh portion in a clean tube", "fresh", "Fresh portion, clean tube, every test"),
 ("For a mixture, the difference", "diff", "Mixture: do every relevant test"),
 ("rather than stop when one class is detected", "contrast", "Staged design stops · mixture continues"),
],
17: [
 ("The June 2023 report highlighted", "announce", "Exam contrast: colour matching"),
 ("in a biuret practical", "standards", "Biuret standards of known concentration"),
 ("compared an unknown against them", "unknown", "An unknown, U, compared by eye"),
 ("Here is an illustrative answer", "illus", "Illustrative answer: not a quoted candidate response"),
 ("Read it", "show", "Read it. What is wrong?"),
 ("Look at the word", "ring", "The word under discussion: “exactly”"),
 ("These two standards received the same colour description", "bracket", "Two standards, one colour name"),
 ("the unknown matched them", "arrow", "U matches that pair"),
 ("So the colour alone does not justify that precision", "precision", "Colour alone cannot give that precision"),
 ("A point estimate must be labelled approximate", "approx", "A point estimate is approximate"),
 ("The examiners' words", "quote", "June 2023 examiner report"),
 ("which reduces the subjectivity", "colorimeter", "Colorimeter: less subjective, not free of uncertainty"),
 ("Written properly", "correct", "Written properly"),
 ("one point two five and two point five percent", "hl", ""),
 ("giving an approximate estimate in that region", "region", "An approximate estimate in that region"),
 ("more closely spaced standards would refine it", "refine", "Closer standards would refine it"),
],
18: [
 ("Now the part that makes you", "open", "Check before concluding"),
 ("A result looks wrong", "panel", "Four doubtful results"),
 ("If the positive control stays blue", "t1", "1 · Positive control stayed blue"),
 ("check the control solution, the labels", "c1", ""),
 ("before interpreting the unknown", "rerun", "One check performed: heating re-run"),
 ("A Benedict's tube that went green", "t2", "2 · A green Benedict's tube"),
 ("may simply hold a little reducing sugar", "valid", "Possibly a valid result"),
 ("check the heating time", "c2", ""),
 ("With a known protein that stayed blue", "t3", "3 · Known protein stayed blue"),
 ("check that the alkali went in", "c3", ""),
 ("the colour-development time was allowed", "c3b", ""),
 ("A clear emulsion tube can be a valid negative", "t4", "4 · A clear emulsion tube"),
 ("check the extraction and the blank", "c4", ""),
 ("Controls help you distinguish", "coi", "Controls separate a valid negative from a failed test"),
],
19: [
 ("So, on the bench you now know", "open", "The bench you now know"),
 ("Each test gave the sample the conditions", "cond", "Conditions for one class"),
 ("you recorded what you saw", "obs", "Observation recorded first"),
 ("Copper ions in excess and heat", "ben", "Benedict's: ≥ 80 °C → green to brick-red, precipitate"),
 ("Iodine, and starch showed blue-black", "iod", "Iodine: blue-black"),
 ("Ethanol then water", "emu", "Emulsion: cloudy white"),
 ("Alkali then copper", "biu", "Biuret: violet"),
 ("Observation first", "heads", "Observation in words, test named"),
 ("inference second, as a class", "inf", "Inference: a class"),
 ("a control beside every test", "controls", "A control beside every test"),
],
20: [
 ("How is this asked", "open", "How it is asked"),
 ("Here is a Paper 3 example", "q", "9700/33 June 2021 Q1(a)(i) [3]"),
 ("Read it and decide what you would write", "read", "Read it: reagent · colours · volume · heat"),
 ("They credited the reagent and the colours", "m1", "What the mark scheme credited"),
 ("an equal or greater volume", "m2", ""),
 ("heating to eighty degrees or above", "m3", ""),
 ("name the class: reducing sugar", "class", "Name the class: reducing sugar"),
],
}
