"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered why your skin", "open", "Why doesn't your skin keep getting thicker?"),
 ("go on dividing for your whole life", "div", "Cells go on dividing"),
 ("In a healthy adult tissue", "healthy", "A healthy adult tissue that is maintaining its size"),
 ("worn away at the surface", "lost", "Cells lost at the surface"),
 ("new cells made by mitosis replace them", "repl", "New cells made by mitosis replace them"),
 ("stay roughly in balance", "bal", "Cells made and cells lost: in balance"),
 ("Now picture one cell", "one", "Picture one cell…"),
 ("just goes on dividing", "goes", "…that just goes on dividing"),
 ("where a tumour can begin", "tum", "Where a tumour can begin"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("explain how a mutation", "l1", ""),
 ("tell a benign tumour from a malignant one", "l2", ""),
 ("write that causal chain", "l3", ""),
],
3: [
 ("Look closer", "open", "The healthy tissue, closer"),
 ("cells divide by mitosis", "div", "Near the base: cells divide by mitosis"),
 ("become specialised", "spec", "Daughters move up and specialise"),
 ("not left to chance", "chance", "Not left to chance"),
 ("Genes in the cell control", "genes", "Genes control when a cell divides"),
 ("division replaces them", "repl", "Cells lost: division replaces them"),
 ("division is held back", "held", "At its size: division held back"),
 ("A growing tissue", "grow", "A growing tissue: net growth"),
 ("this adult tissue stays level", "level", "This adult tissue stays level"),
],
4: [
 ("So what breaks the balance", "open", "What breaks the balance?"),
 ("genes are lengths of DNA", "dna", "A gene: a length of DNA"),
 ("A mutation is a change", "mut", "Mutation: a change in the DNA sequence"),
 ("ultraviolet radiation in sunlight", "uv", "One typical cause: UV in sunlight"),
 ("can cause mutations in them", "hit", ""),
 ("Many such changes", "many", "Many changes miss division-control genes"),
 ("A change in a division-control gene", "ctrl", "A change in a division-control gene"),
 ("Suppose that happens here", "star", "In this example: the control gene is mutated"),
 ("loses control of its cell cycle", "loss", "Loss of control of the cell cycle"),
 ("divides repeatedly when it should not", "rep", "Divides repeatedly when it should not"),
],
5: [
 ("why one faulty cell becomes a lump", "open", "From one cell to a lump"),
 ("copies its DNA, mutated gene included", "copy", "DNA copied: the mutated gene too"),
 ("both daughter cells inherit the mutation", "inherit", "Both daughters inherit the mutation"),
 ("and so do theirs", "rounds", "…and so do theirs"),
 ("Picture a tap stuck open", "tap", "Handle: a tap stuck open, the drain the same"),
 ("Written properly", "wp", "Written properly"),
 ("can cause loss of control", "c1", ""),
 ("divides repeatedly by mitosis", "c2", ""),
 ("a mass of abnormal cells", "c3", ""),
 ("Usually more than one such mutation", "more", "Usually more than one mutation"),
],
6: [
 ("A tumour is not always a cancer", "open", "A tumour is not always a cancer"),
 ("A benign tumour typically stays", "benign", "Benign: typically stays in one place"),
 ("within a clear boundary", "bound", "Usually within a clear boundary"),
 ("does not invade", "noinv", "Does not invade"),
 ("A malignant tumour is a cancer", "malig", "Malignant tumour: a cancer"),
 ("invade the surrounding tissue", "inv", "Invades surrounding tissue"),
 ("some can break away", "away", "Cells can break away"),
 ("travel in the blood", "travel", "…travel in blood or lymph"),
 ("settle somewhere else", "settle", "…settle elsewhere"),
 ("form secondary tumours", "sec", "Secondary tumours"),
],
7: [
 ("Here is an answer that would lose the mark", "open", "EXAM CONTRAST: an answer that would lose the mark"),
 ("Our framing", "q", "Our framing of w20_21 Q6(a)(i)"),
 ("Read this answer", "card", "Read the answer. What is missing?"),
 ("Look at the word mitosis", "word", "The word: mitosis"),
 ("a tumour is built by cells dividing", "true", "True, but not enough"),
 ("Beyond the scheme", "beyond", "Beyond the mark scheme"),
 ("mitosis also repairs healthy tissue", "heal", "Mitosis also repairs healthy tissue"),
 ("naming it does not explain", "nocause", "Naming mitosis explains nothing"),
 ("What is missing is control", "gap", "What is missing: control"),
 ("the mutation is supplied", "sup", "The mutation is supplied"),
 ("Loss of cell-cycle control allows", "k1", "Its consequences"),
 ("repeated uncontrolled division", "k2", ""),
 ("builds a mass of abnormal cells", "k3", ""),
 ("two marks for any two credited consequences", "marks", "2 marks: any two credited points"),
 ("It does not require", "notreq", "Not required here"),
 ("So, in place", "fix", "Corrected in place"),
 ("so the cell divides repeatedly by mitosis without control", "fix2", ""),
 ("a mass of abnormal cells, a tumour$", "done", "The corrected answer"),
],
8: [
 ("So here it is", "open", "What I told you, on the tissue"),
 ("on the tissue you watched", "settle", ""),
 ("In balance, division replaces lost cells", "bal", "In balance: controlled mitosis"),
 ("can disrupt that control", "mut", "A mutation can disrupt control"),
 ("Daughter cells inherit it", "inh", "Inherited: repeated, uncontrolled mitosis"),
 ("building a mass", "mass", "A mass: a tumour"),
 ("typically stays put", "ben", "Benign: typically stays put"),
 ("a malignant one invades", "mal", "Malignant: invades"),
 ("spread in blood or lymph", "spread", "Can spread: secondary tumours"),
],
9: [
 ("How does this reach you?", "open", "How it is asked"),
 ("supplied the mutation", "r1", "w20_21 Q6(a)(i): consequences of a supplied mutation"),
 ("supplied information about inhibitors", "r2", "s24_23 Q5(d): supplied inhibitor information"),
 ("work from what it gives you", "work", ""),
 ("The reject card", "reject", "The reject card"),
 ("Beyond the scheme", "beyond", "Beyond the mark scheme"),
 ("cell production balances cell loss$", "end", ""),
],
}
