"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues plus visual-only cues that
break long holds (recorded in qa/cue-additions.md). '^' marks the trigger word inside a phrase that is
matched whole for uniqueness; a trailing '$' triggers at the END of the phrase's last spoken word
(exit cues). An empty caption keeps the previous caption. Captions are look-here anchors, never the
narration re-typed. Matching is case-normalised, so every phrase is unique within its beat."""
PLANS = {
1: [
 ("Ever wondered", "open", "Bread in your mouth. Why does it turn sweet?"),
 ("a piece of bread", "bread", ""),
 ("taste sweet", "sweet", "Keep it there: it starts to taste sweet"),
 ("Something in your saliva", "saliva", "Saliva around the bread"),
 ("cutting starch into sugar", "cut", "Starch cut into maltose (MODEL beads)"),
 ("the cells of your tongue", "cells", "Tongue cells in the same liquid: untouched"),
 ("That something is an enzyme", "enzyme", "The cutter: an enzyme, amylase"),
 ("thousands of reactions at once", "cell", "One cell: thousands of reactions at once"),
 ("far too slow", "slow", "Left alone, many are far too slow"),
 ("Enzymes speed particular reactions", "speed", "Enzymes speed particular reactions"),
 ("acting on suitable substrates", "ring", "Each enzyme acts on suitable substrates"),
 ("How, and where", "zoom", "How, and where"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("state what an enzyme is", "l1", ""),
 ("inside a cell or outside it", "l1b", ""),
 ("explain how an enzyme works", "l2", ""),
 ("the active site", "l2a", ""),
 ("the enzyme–substrate complex", "l2b", ""),
 ("the lowering of activation energy", "l2c", ""),
 ("and specificity", "l2d", ""),
 ("keep the two hypotheses", "l3", ""),
 ("lock-and-key and induced fit", "l3a", ""),
 ("two separate pictures", "l3b", ""),
],
3: [
 ("Start with what an enzyme is", "open", "What an enzyme is"),
 ("An enzyme is a globular protein", "fold", "A chain folds into a compact, globular shape"),
 ("one or more polypeptide chains", "chains", "One or more polypeptide chains, folded"),
 ("the kind you met in the protein lessons", "recall", "Recall 2.3.4: globular proteins"),
 ("a biological catalyst", "catalyst", "Its job: a biological catalyst"),
 ("increases the rate of a reaction", "rate", "It increases the rate of a reaction"),
 ("the enzyme itself is unchanged", "unchanged", "At the end, the enzyme is unchanged"),
 ("ready to go again", "again", ""),
 ("Its folded structure", "forward", "The fold forms the active site: next"),
],
4: [
 ("where does it work", "open", "Where does an enzyme work?"),
 ("inside the cell that made them", "inside", "Some work inside the cell that made them"),
 ("Catalase is one", "catalase", "Catalase: inside cells"),
 ("breaks down hydrogen peroxide inside cells", "h2o2", ""),
 ("intracellular enzymes", "intra", "Inside the cell: intracellular"),
 ("then secreted", "secrete", "Others are secreted: released from the cell"),
 ("The amylase in your saliva", "amylase", "Amylase: works outside, in your mouth"),
 ("work on starch out there", "starch", ""),
 ("lipase in your intestine", "lipase", "Lipase: works outside, in the intestine"),
 ("extracellular enzymes", "extra", "Outside the cell: extracellular"),
 ("Same kind of molecule", "same", "Same kind of molecule"),
 ("where the reaction happens", "where", "The difference: where the reaction happens"),
],
5: [
 ("Here is a mistake the examiners list", "announce", "A mistake the examiners list"),
 ("The question asked for the term", "header", "The term for an enzyme that works outside cells"),
 ("Read this answer", "show", "Read this answer. What is wrong?"),
 ("Look at the prefix", "prefix", "Look at the prefix"),
 ("ex means out", "exout", ""),
 ("they have just learnt that the enzyme leaves the cell", "replay", "Leaving the cell blurs into where it works"),
 ("the word for leaving", "ghost", ""),
 ("the examiners' list of common mistakes", "cite", "The examiners' own list"),
 ("the term credited is extracellular", "credited", "Credited: extracellular"),
 ("underline the terms that describe lipases", "qp", "November 2020: the terms that describe lipases"),
 ("write it in full", "correct", "Write it in full: extracellular enzyme"),
 ("catalyst on its own was not credited either", "catalyst", "Catalyst alone: what it does, not where"),
 ("not where$", "exit", ""),
],
6: [
 ("Look closely at the enzyme", "zoom", "Look closely: it is all about shape"),
 ("the whole explanation is about shape", "shape", ""),
 ("one folded polypeptide", "backbone", "This model: one folded polypeptide"),
 ("Its tertiary structure", "tertiary", "Tertiary structure"),
 ("held by interactions between R groups", "links", "Held by interactions between R groups"),
 ("a small region", "region", "A small region of the surface"),
 ("a cleft or pocket", "cleft", ""),
 ("the active site", "label", "The active site"),
 ("set by the whole fold around it", "stubs", "Its shape is set by the whole fold"),
 ("the catalysis happens here", "here", "Catalysis happens here"),
],
7: [
 ("three different molecules", "line", "Three molecules try the active site"),
 ("This one drifts in and does not fit", "m1", "Watch it try"),
 ("it slides off", "m1off", "Does not fit: slides off"),
 ("This one, the same", "m2", "The second: the same"),
 ("This one settles in", "m3", "The third settles in"),
 ("complementary in shape to this substrate", "trace", "Complementary in shape"),
 ("not the same shape, complementary", "ghost", "Not the same shape: complementary"),
 ("That is enzyme specificity", "spec", "Enzyme specificity"),
 ("a limited group of related substrates", "group", ""),
 ("These two molecules do not fit", "reject", "These two do not fit this active site"),
 ("Picture a lock and a key", "handle", "The handle: lock and key"),
 ("written properly", "sentence", "Written properly"),
 ("so the enzyme is specific", "specific", ""),
],
8: [
 ("When the substrate seats", "open", "The substrate seats"),
 ("it is held in place", "bound", "Held in place"),
 ("temporary bonds", "ticks", "Temporary bonds (dashed)"),
 ("the R groups lining the active site", "rgroups", "R groups line the active site"),
 ("hydrogen bonds, for example", "legend", "For example, hydrogen bonds"),
 ("Enzyme and substrate bound together", "together", ""),
 ("the enzyme–substrate complex", "bracket", "The enzyme–substrate complex"),
 ("write that name out in full", "underline", "Write the name out in full"),
 ("building to", "build", ""),
 ("inside this complex", "ring", "The reaction happens inside the complex"),
],
9: [
 ("Take a real reaction", "open", "A real reaction"),
 ("Amylase is our enzyme", "amylase", "Enzyme: amylase"),
 ("a stretch of starch", "starch", "Substrate: a stretch of starch"),
 ("four glucose units in a chain", "inset", "Four glucose units, atom by atom (MODEL)"),
 ("a molecule of water is used", "water", "A water molecule comes in, fully bonded"),
 ("one glycosidic bond is ^broken", "switch", "One glycosidic bond broken: the net change"),
 ("the net change", "net", ""),
 ("The bridge oxygen keeps its bond to carbon one", "c1og", "The bridge O keeps its bond to C1"),
 ("takes a hydrogen from the water", "oght", "…and gains an H from the water"),
 ("goes to carbon four on the other side", "cpow", "The water's O–H goes to C4"),
 ("two molecules of maltose", "maltose", "Two maltose: the products"),
 ("they leave the active site", "leave", "The products leave"),
 ("nothing about it has changed", "unchanged", "The enzyme: unchanged"),
 ("same active site", "site", ""),
 ("That is what catalyst meant", "reuse", "Unchanged, and used again"),
],
10: [
 ("Why is it faster", "open", "Why is it faster?"),
 ("Here is an energy profile", "axes", "An energy profile (our graph)"),
 ("energy up the side", "yl", ""),
 ("the progress of the reaction along the bottom", "xl", ""),
 ("The substrate starts here", "sub", "Start: the substrate"),
 ("the product ends here", "prod", "Finish: the product"),
 ("in between there is a hill", "hill", "In between: a hill"),
 ("its height is the activation energy", "ea1", "Its height: the activation energy"),
 ("the energy that has to be put in", "climb", "Energy put in before it can go"),
 ("The enzyme lowers the activation energy", "cat", "With the enzyme: a lower hill"),
 ("same start", "same", "Same start, same finish"),
 ("same finish, a lower hill", "ea2", ""),
 ("The gap between the two peaks is the reduction", "red", "The gap between peaks: the reduction"),
 ("not either hill on its own", "dim", ""),
 ("many more molecules get over it", "tokens", "More get over a lower hill"),
 ("the rate goes up", "rate", "So the rate goes up"),
],
11: [
 ("Here is a mistake that comes from knowing this lesson well", "announce", "A mistake from knowing this lesson well"),
 ("asked why glycogen branching enzyme is needed", "header", "June 2016: why is this enzyme needed?"),
 ("Read this answer", "show", "Read this answer. What is missing?"),
 ("about glycogen branching enzyme in particular", "hdr1", "This enzyme, in particular"),
 ("does not identify the bond", "bracket", "Role given; bond not identified"),
 ("Lowering activation energy is true", "ul1", "True of enzymes generally"),
 ("forming branches is this enzyme's role", "ul2", "This enzyme's role"),
 ("Naming the particular bond", "name", "Name the bond"),
 ("This can feel like a useful answer because", "tint", "It is the sentence just learnt"),
 ("this enzyme's precise job", "hdr2", "The question: this enzyme's precise job"),
 ("the examiners' comment says", "cite", "What the examiners said"),
 ("alpha one-six glycosidic bonds, from the carbohydrate lessons", "recall", "Recall: α-1,6 glycosidic bonds at the branch points"),
 ("the credited answer names the bond", "correct", "Credited: it names the bond"),
 ("Now the boundary", "boundary", "The boundary: a ruling about that question"),
 ("Where a question asks for the mode of action", "ul3", "Mode-of-action questions"),
 ("June 2024 credited it for laccase", "ul4", "June 2024: credited for laccase"),
 ("the question in front of you$", "exit", "Answer the question in front of you"),
],
12: [
 ("Now the two hypotheses", "open", "Two hypotheses"),
 ("two separate drawings", "split", "Two separate drawings"),
 ("The first and older one", "lk", "Lock-and-key hypothesis"),
 ("a fixed shape that is complementary to the substrate before the substrate arrives", "trace", "Complementary before binding"),
 ("like a lock cut for one key", "icon", ""),
 ("The substrate fits", "fits", "The substrate fits"),
 ("the complex forms", "complex", "Enzyme–substrate complex"),
 ("the products leave", "leave", "The products leave"),
 ("the same shape throughout", "same", "The active site shape: unchanged throughout"),
 ("This is not a wrong picture", "tick", "Not a wrong picture"),
 ("those diagrams earned the marks", "cite", "June 2024: lock-and-key diagrams earned marks"),
 ("It is the simpler model", "simple", "The simpler model; explains specificity"),
],
13: [
 ("the induced-fit hypothesis", "open", "Induced-fit hypothesis"),
 ("not fully complementary", "gap", "At rest: not fully complementary"),
 ("changes shape to fit it", "close", "The active site changes shape to fit"),
 ("becoming fully complementary", "match", "Now fully complementary"),
 ("the complex forms", "complex", "Enzyme–substrate complex"),
 ("the products leave", "leave", "The products leave"),
 ("returns to its original shape", "reopen", "The enzyme returns to its original shape"),
 ("the resting shape", "f1", "Resting shape"),
 ("the change on binding", "f2", "Change on binding"),
 ("the return", "f3", "The return"),
 ("the refinement now generally accepted", "accepted", "The accepted refinement"),
 ("the credited phrase", "cite", "The credited phrase"),
 ("Two ideas, two names", "both", "Two ideas, two names"),
],
14: [
 ("And that brings us to a mistake", "announce", "A mistake the examiners list word for word"),
 ("The question asked for the name", "header", "Name the hypothesis: the active site changes shape"),
 ("Read this answer", "show", "Read this answer. What is wrong?"),
 ("Look at the words", "ul", "Look at the words"),
 ("taken a piece of each", "tint", "A piece of each, glued together"),
 ("The names can merge when both are taught together", "merge", "Taught together, the names can merge"),
 ("lock-and-key is the fixed shape", "lkfixed", "Lock-and-key: the fixed shape"),
 ("induced fit is the shape that changes", "ifchange", "Induced fit: the shape that changes"),
 ("The examiners' list shows five of these hybrids", "cite", "The examiners' list: five hybrids"),
 ("looking only for induced fit", "only", "Looking only for induced fit"),
 ("two names in your pen", "correct", "Two drawings, two names"),
 ("never a blend of the two$", "exit", ""),
],
15: [
 ("Now build the sentence", "open", "The sentence the examiners credit"),
 ("clause by clause", "layout", "Clause by clause"),
 ("complementary to its substrate", "c1", "1 · complementary"),
 ("forming an enzyme–substrate complex", "c2", "2 · enzyme–substrate complex"),
 ("lowers the activation energy", "c3", "3 · lowers the activation energy"),
 ("so the reaction is faster", "c3b", ""),
 ("The products are released", "c4", "4 · products released"),
 ("unchanged and used again", "c4b", "4 · enzyme unchanged, used again"),
],
16: [
 ("Last mistake", "announce", "Last mistake: on the drawing itself"),
 ("asked for labelled diagrams", "header", "June 2024 Paper 22: labelled diagrams"),
 ("Here is a drawing of the kind the report describes", "kind", "A drawing of the kind the report describes"),
 ("Read it", "show", "Read the drawing. What is wrong?"),
 ("Start with the labels", "ul", "Start with the labels"),
 ("the wrong way round", "swaparrow", "The two names: the wrong way round"),
 ("Lysozyme is the enzyme", "ghostE", "Lysozyme: the enzyme"),
 ("peptidoglycan is what it acts on", "ghostS", "Peptidoglycan: the substrate"),
 ("both names are unfamiliar", "pulse", "Two new names in one sentence"),
 ("look where the active site has been drawn", "ringAS", "Where is the active site drawn?"),
 ("belongs in the big shape's cleft", "ringCleft", "The active site is on the enzyme"),
 ("the complex is labelled E S C", "ringESC", "The complex: labelled ESC"),
 ("The report for that paper says", "cite", "What the report says"),
 ("swap the two names", "fix1", "Swap the names"),
 ("move the active site onto the enzyme", "fix2", "Move the active site onto the enzyme"),
 ("write the complex out in full", "fix3", "Write the complex out in full"),
 ("earns its marks", "ticks", "Now it earns its marks"),
],
17: [
 ("So here is the whole lesson", "open", "What I told you, on the model"),
 ("a globular protein and a biological catalyst", "cap", "Globular protein · biological catalyst"),
 ("intracellular", "intra", "Inside: intracellular"),
 ("extracellular", "extra", "Secreted, outside: extracellular"),
 ("the active site, complementary to its substrate", "site", "Complementary active site"),
 ("that is specificity", "spec", "Specificity"),
 ("held by temporary bonds", "ticks", "Temporary bonds"),
 ("the enzyme–substrate complex", "esc", "Enzyme–substrate complex"),
 ("a lower activation energy", "ea", "Lower activation energy"),
 ("the enzyme is unchanged", "unch", "Enzyme unchanged"),
 ("lock-and-key, a fixed shape", "lk", "Lock-and-key: a fixed shape"),
 ("changes shape to fit and returns afterwards", "if", "Induced fit: changes shape, then returns"),
],
18: [
 ("how this reaches you in an exam", "open", "How it is asked"),
 ("They ask you to draw labelled diagrams", "r1", "Form 1: draw labelled diagrams"),
 ("a label or annotation linking the drawing to the supplied example", "r1b", "Link the drawing to the example"),
 ("describe and explain the mode of action of a named enzyme", "r2", "Form 2: the mode of action of a named enzyme"),
 ("a reference to laccase or its substrates", "r2b", "Refer to the named enzyme or substrate"),
 ("For substrate binding, describe complementary shapes", "contrast", "Complementary, not the same shape"),
 ("Here is the drawing question", "q", "The real question"),
 ("Read it", "read", "Read it: draw and label"),
 ("the credited points land on our model", "land", "The credited points, on our model"),
 ("And the bread", "bread", "And the bread?"),
 ("complementary to starch", "seat", "Amylase: complementary to starch"),
 ("not its substrate$", "tag", "Tongue cells: not its substrate"),
],
}
