import transcript from '../../public/transcripts/mechanics/energy-principles.json';
import {figureNumberMatch,Scene} from '../mechanics-m42/Presentation';
import React,{useLayoutEffect,useState} from 'react';
import {Artifact,continueRender,delayRender,useCurrentFrame} from 'remotion';
/** Actual transformed car contacts, path/annotation collisions, energy bars and number rings. */
export const EnergyPrinciplesShapeAudit:React.FC=()=>{const frame=useCurrentFrame();const [handle]=useState(()=>delayRender('Energy principles geometry'));const [data,setData]=useState('');useLayoutEffect(()=>{let req=0;const run=()=>{const stage=document.querySelector<SVGSVGElement>('svg[data-visual="diagram"]');if(!stage||stage.getBoundingClientRect().width<900){req=requestAnimationFrame(run);return;}const bounds=stage.getBoundingClientRect();const shapes=Array.from(stage.querySelectorAll('path,rect,circle')).map(e=>({kind:e.tagName,force:e.getAttribute('data-force-arrow'),d:e.getAttribute('d'),bounds:e.getBoundingClientRect().toJSON()}));const overflow=shapes.filter(s=>s.bounds.left<bounds.left+4||s.bounds.right>bounds.right-4||s.bounds.top<bounds.top+4||s.bounds.bottom>bounds.bottom-4);const scene=document.querySelector('[data-scene]')?.getAttribute('data-scene');const events=(transcript.scenes as unknown as Scene[]).find(s=>s.id===scene)?.figureEvents??[];
 const ringChecks=Array.from(document.querySelectorAll<SVGPathElement>('[data-ring]')).map(r=>{const event=events.find(e=>e.id===r.getAttribute('data-ring'));const label=r.parentElement!.querySelector<SVGTextElement>(`[data-figure-id="${r.getAttribute('data-ring-target')}"]`)!;const match=figureNumberMatch(label.textContent??'',event?.word);const expected=match?label.getSubStringLength(0,match.index!)+label.getSubStringLength(match.index!,match[0].length)/2+Number(label.getAttribute('x')):null;const box=r.getBBox();return {id:event?.id,value:event?.word,match:match?.[0],expectedCenter:expected,observedCenter:box.x+box.width/2,centerError:expected===null?null:Math.abs(expected-box.x-box.width/2)};});
 const road=stage.querySelector<SVGPathElement>('[data-road]');const matrix=road?.getScreenCTM();const ra=road?.getPointAtLength(0).matrixTransform(matrix!),rb=road?.getPointAtLength(road.getTotalLength()).matrixTransform(matrix!);const dx=ra&&rb?rb.x-ra.x:0,dy=ra&&rb?rb.y-ra.y:0,L=Math.hypot(dx,dy);
 const cars=Array.from(stage.querySelectorAll<SVGGElement>('[data-car-x]')).map(car=>({x:Number(car.getAttribute('data-car-x')),y:Number(car.getAttribute('data-car-y')),transform:car.getAttribute('transform'),wheels:Array.from(car.querySelectorAll<SVGCircleElement>('circle')).map(w=>{const m=w.getScreenCTM()!,point=new DOMPoint(Number(w.getAttribute('cx')??0),Number(w.getAttribute('cy')??0)).matrixTransform(m);const outerRadius=(Number(w.getAttribute('r'))+Number(w.getAttribute('stroke-width'))/2)*Math.hypot(m.a,m.b);const contact={x:point.x-dy/L*outerRadius,y:point.y+dx/L*outerRadius};return {centre:{x:point.x,y:point.y},outerRadius,contact,roadNormalResidual:ra?Math.abs((contact.x-ra.x)*dy-(contact.y-ra.y)*dx)/L:null};})}));
 const labels=Array.from(stage.querySelectorAll<SVGGraphicsElement>('[data-label],[data-ring]'));const barCollisions:Array<unknown>=[];
 for(const path of Array.from(stage.querySelectorAll<SVGPathElement>('[data-road],[data-distance],[data-height],[data-force-arrow]'))){const m=path.getScreenCTM()!,n=Math.ceil(path.getTotalLength()/2);const points=Array.from({length:n+1},(_,i)=>path.getPointAtLength(i/n*path.getTotalLength()).matrixTransform(m));for(const e of labels){const b=e.getBoundingClientRect();if(points.some(p=>p.x>b.left-1&&p.x<b.right+1&&p.y>b.top-1&&p.y<b.bottom+1))barCollisions.push({path:path.getAttribute('data-force-arrow')??path.getAttributeNames().find(k=>k.startsWith('data-')),label:e.textContent||e.getAttribute('data-ring')});}}
 const energyBars=Array.from(document.querySelectorAll<SVGRectElement>('[data-energy-bar]')).map(e=>({id:e.getAttribute('data-energy-bar'),joules:Number(e.getAttribute('data-joules')),width:Number(e.getAttribute('width')),screenWidth:e.getBoundingClientRect().width}));
 setData(JSON.stringify({frame,barCollisions,ringChecks,stage:bounds.toJSON(),shapes,overflow,cars,roadEndpoints:ra&&rb?[{x:ra.x,y:ra.y},{x:rb.x,y:rb.y}]:[],energyBars}));continueRender(handle);};req=requestAnimationFrame(run);return()=>cancelAnimationFrame(req);},[frame,handle]);return data?<Artifact filename={`energy-principles-shapes-${frame}.json`} content={data}/>:null;};
