"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in progress-notes.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Beat 7 (E43, EXAM CONTRAST): entry cue = its first words; the marker
clears on the completed correct frame at the END of "through channel or carrier proteins" (key 'exit')."""
PLANS = {
1: [
 ("Ever wondered why oxygen slips", "hook", "Oxygen slips straight through"),
 ("a sodium ion, tiny as it is", "na", "A sodium ion is turned back"),
 ("unless a protein lets it through", "chan", "...unless a protein lets it through"),
 ("keep the cell's contents in", "keep", "Keep the contents in"),
 ("let the right substances across", "across", "Let the right substances across"),
 ("stay in one piece, yet stay flexible", "flex", "Stay in one piece, yet flexible"),
 ("receive signals", "signal", "Receive signals"),
 ("be recognised by other cells", "recog", "Be recognised by other cells"),
 ("different molecules in it do different jobs", "jobs", "Different molecules, different jobs"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("describe what each of the five kinds of molecule", "l1", ""),
 ("use the six role words", "l2", ""),
 ("from stability to recognition", "tiles", ""),
 ("explain why sodium ions and glucose need transport proteins", "l3", ""),
 ("the way mark schemes credit it", "tick", ""),
],
3: [
 ("Here is the membrane", "open", "The membrane (recall: 4.1.1-2)"),
 ("a phospholipid bilayer", "bilayer", "A phospholipid bilayer"),
 ("heads facing the watery outside", "heads", "Heads face the water on both sides"),
 ("tails meeting in the middle", "core", "Tails meet in the hydrophobic core"),
 ("with cholesterol, glycolipids, proteins and glycoproteins", "comps", "Cholesterol, glycolipids, proteins, glycoproteins"),
 ("what each of them does", "roles", "What does each one do?"),
 ("let nothing across and carried no signals", "wall", "A wall would cut the cell off"),
 ("control what crosses", "control", "Control what crosses"),
 ("to stay intact", "intact", "Stay intact"),
 ("or to communicate", "comm", "Communicate"),
 ("Six role words carry it", "grid", "Six role words"),
 ("this grid fills in as we go", "cols", "The grid fills in as we go"),
],
4: [
 ("Start with the phospholipids and permeability", "open", "Phospholipids × permeability"),
 ("The middle of the bilayer is the tails", "core", "The hydrophobic core"),
 ("Small non-polar molecules such as oxygen", "o2", "Small non-polar molecules pass through"),
 ("carbon dioxide", "co2", ""),
 ("oxygen enters a red blood cell", "rbc", "Example: oxygen into a red blood cell"),
 ("Sodium ions and glucose interact strongly with water", "halo", "Sodium ions and glucose: surrounded by water"),
 ("entering the hydrophobic core is unfavourable for them", "bounce", "Entering the core is unfavourable"),
 ("do not cross it readily", "barrier", "A barrier to ions and polar molecules"),
 ("Keep the image of oil and water", "oil", "Handle: oil and water don't mix"),
 ("don't mix. ^Oil: the non-polar tails", "l1", "Oil → the non-polar tails in the core"),
 ("Water: the watery solutions", "l2", "Water → the watery solutions on each side"),
 ("so those stay out of the core$", "map", "They don't mix: ions and glucose stay out of the core"),
 ("isn't a film of oil", "film", "Only the core is oil-like"),
 ("Written properly", "written", "Written properly"),
 ("small non-polar molecules cross the phospholipid bilayer", "c1", "Clause 1: small non-polar molecules cross"),
 ("its hydrophobic core is a barrier", "c2", "Clause 2: the core is a barrier"),
 ("partially permeable", "pp", "Partially permeable"),
],
5: [
 ("how do sodium ions cross this barrier", "open", "How do sodium ions cross?"),
 ("this is their transport role", "role", "Proteins × transport"),
 ("Watch a sodium ion reach the bilayer", "reach", "A sodium ion reaches the bilayer"),
 ("the core turns it back", "back", "The core turns it back"),
 ("it meets a channel protein", "chan", "A channel protein"),
 ("span the bilayer", "span", "It spans the bilayer"),
 ("Down its middle runs a pore", "pore", "A water-filled pore"),
 ("lined with hydrophilic parts of the protein", "lining", "Lined with hydrophilic parts"),
 ("the ion passes through", "pass", "The ion passes through"),
 ("without touching the hydrophobic core", "untouched", "Without touching the core"),
 ("Each kind of channel lets particular ions", "particular", "Particular ions for each channel"),
 ("different channels pass different ones", "different", ""),
 ("keeps its shape the whole time", "shape", "The channel keeps its shape"),
],
6: [
 ("A carrier protein works another way", "open", "A carrier protein"),
 ("Glucose is polar", "glu", "Glucose is polar"),
 ("does not cross the hydrophobic bilayer core readily", "bounce", "Not across the core readily"),
 ("it needs a transport protein", "needs", "It needs a transport protein"),
 ("in this example that protein is a carrier", "example", "Our example: a carrier"),
 ("The carrier has a binding site", "site", "The carrier's binding site"),
 ("The glucose binds", "bind", "The glucose binds"),
 ("the carrier changes shape", "flip", "The carrier changes shape (preview)"),
 ("the glucose is released there", "release", "Released on the other side"),
 ("When that happens, in which direction", "handoff", "When, which direction, energy? 4.2.1"),
 ("For now, the role", "role", "The role"),
 ("channel proteins and carrier proteins let ions and polar molecules cross", "both", "Transport: channel and carrier proteins"),
],
7: [
 ("Now an exam contrast", "entry", "EXAM CONTRAST: the word 'membrane'"),
 ("a November 2022 mark scheme", "header", "Our framing of a November 2022 question"),
 ("Read this answer", "card", "Read this answer"),
 ("Look at the word membrane here", "word", "Look at this word"),
 ("the bilayer really is a barrier to ions", "bilayer", "The bilayer core: yes, a barrier"),
 ("most of what you picture", "picture", "Membrane is more than the bilayer"),
 ("also holds the channel and carrier proteins", "proteins", "The membrane also holds the proteins"),
 ("rules out the very route the ions use", "route", "It rules out the protein route"),
 ("That scheme lists this exact wording as ignore", "ms", "The scheme: ignore"),
 ("at that point it earns nothing", "nothing", "Earns nothing at that point"),
 ("It is a ruling on one question", "local", "A ruling on one question"),
 ("So, in place", "fix", "Corrected in place"),
 ("cannot cross the hydrophobic core of the bilayer", "c1", ""),
 ("they cross the membrane through channel or carrier proteins", "c2", ""),
 ("through channel or carrier proteins$", "exit", "Through channel or carrier proteins"),
],
8: [
 ("Next, fluidity", "open", "Fluidity"),
 ("they jiggle and drift sideways within their own layer", "drift", "Sideways, within one layer"),
 ("many proteins drift too, more slowly", "pdrift", "Proteins drift more slowly"),
 ("what fluid means in fluid mosaic", "fluid", "Fluid"),
 ("Cholesterol, in animal cell membranes", "chol", "Cholesterol (animal cell membranes)"),
 ("helps regulate it", "reg", "Helps regulate fluidity"),
 ("In the usual account", "inset", "Qualitative schematic; not measured data"),
 ("at higher temperatures", "hot", "Higher temperature"),
 ("restrains the phospholipids' movement", "restrain", "Cholesterol restrains movement"),
 ("at lower temperatures it sits between the tails", "cold", "Lower temperature"),
 ("stops them packing tightly together", "pack", "Cholesterol stops tight packing"),
 ("helps keep the membrane's fluidity steadier", "steady", "Fluidity kept steadier"),
],
9: [
 ("Cholesterol does more than that", "open", "Cholesterol: more roles"),
 ("Its rigid rings sit among the tails", "rings", "Rigid rings among the tails"),
 ("helps make the membrane more stable", "stable", "Helps stability"),
 ("by filling spaces between the tails", "fill", "Filling spaces between the tails"),
 ("even less permeable to small polar molecules and ions", "perm", "Reduces permeability"),
 ("cholesterol appears three times on the grid", "three", "Cholesterol: three roles"),
 ("The carbohydrate chains of glycolipids and glycoproteins", "chains", "Carbohydrate chains"),
 ("project from the outer surface", "outer", "On the outer face"),
 ("form hydrogen bonds with the water there", "hb", "Chains hydrogen-bond with water"),
],
10: [
 ("Now cell signalling", "open", "Cell signalling"),
 ("act as cell surface receptors", "rec", "Cell surface receptors"),
 ("a binding site on its outer face", "site", "Its binding site"),
 ("complementary to a particular signalling molecule", "comp", "Complementary to its signalling molecule"),
 ("arrives and binds to the binding site", "bind", "The signalling molecule binds"),
 ("leads to a response inside the cell", "resp", "A response in the cell (4.1.4)"),
 ("Not every glycoprotein is a receptor", "notevery", "Not every glycoprotein is a receptor"),
 ("have a lesson of their own", "handoff", "Stages of signalling: 4.1.4"),
 ("Written properly", "written", "Written properly"),
 ("a receptor has a binding site complementary in shape", "sent", "Binding site complementary in shape"),
],
11: [
 ("Last, cell recognition", "open", "Cell recognition"),
 ("Glycoproteins and glycolipids, with their carbohydrate chains", "chains", "Glycoproteins and glycolipids"),
 ("act as cell surface antigens", "antigens", "Cell surface antigens"),
 ("markers on the outside of the cell", "markers", "Markers on the outside"),
 ("other cells can recognise", "cell", "Recognised by other cells"),
 ("how the body recognises its own cells", "self", "Self and non-self: 11.1.2"),
 ("where the chains sit, on the outer face", "outer", "Chains on the outer face"),
],
12: [
 ("So here it is", "open", "What I told you, on the membrane"),
 ("on the membrane", "settle", ""),
 ("Phospholipids: a hydrophobic core", "pl", "Phospholipids"),
 ("is a barrier to ions and polar ones", "barrier", ""),
 ("sideways movement", "fluid", ""),
 ("Cholesterol: regulates fluidity", "chol", "Cholesterol"),
 ("Proteins: channels and carriers for transport", "prot", "Proteins"),
 ("some as receptors for signalling", "rec", ""),
 ("Glycoproteins: receptors, recognition and stability", "gp", "Glycoproteins"),
 ("Glycolipids: recognition and stability", "gl", "Glycolipids"),
 ("Six roles, five kinds of molecule", "six", "Six roles, five kinds of molecule"),
 ("one membrane", "one", "One membrane"),
],
13: [
 ("How does this reach you?", "open", "How it is asked"),
 ("why a particular substance needs a transport protein", "row1", "Why does this substance need a transport protein?"),
 ("a polar substance in a June 2023 paper", "s23", ""),
 ("sodium ions in March 2024", "m24", ""),
 ("The credited idea links the substance", "credit", "Link the substance to the hydrophobic core"),
 ("size alone, or just naming facilitated diffusion", "ignored", "Size alone, or naming the process: nothing"),
 ("asks for one role of cholesterol", "row2", "State one role of cholesterol"),
 ("The reject card", "reject", "The reject card (our wording contrast)"),
 ("And the sodium ion?", "na", "And the sodium ion?"),
 ("the hydrophobic core turns it back", "back", "The core turns it back"),
 ("a channel protein lets it through", "through", "A channel protein lets it through"),
],
}
