"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in progress-notes.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. "LL-37" is request-normalised, so no cue phrase contains it: Beat 7's exit
is the END of "a binding site complementary to" and the clear frame adds the measured length of "LL-37"
(Lesson.tsx ERROR_BEATS animFrames)."""
PLANS = {
1: [
 ("Ever wondered how a hormone", "hook", "How does a hormone find the right cells?"),
 ("your blood carries it widely", "flow", "Blood carries it widely"),
 ("separate compartments", "comp", "Each cell inside its own membrane"),
 ("one way they coordinate", "signal", "A chemical signal"),
 ("After a meal", "meal", "After a meal: blood glucose rises"),
 ("cells in your pancreas release", "insulin", "The pancreas releases insulin"),
 ("past cells of many different kinds", "past", "Past cells of many kinds"),
 ("get acted on in the right places", "why", "Why here?"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("outline the three stages of cell signalling", "l1", ""),
 ("why a cell responds to a signal only if it has a complementary receptor", "l2", ""),
 ("several cell types can share one", "l2b", ""),
 ("the words mark schemes credit", "l3", ""),
],
3: [
 ("Stage one is secretion", "open", "Stage one: secretion"),
 ("is called a ligand", "ligand", "A ligand: a chemical released as a signal"),
 ("the beta cells of the pancreas", "beta", "Our example: insulin from beta cells"),
 ("stored in vesicles", "vesicles", "Stored in vesicles"),
 ("a vesicle moves to the cell surface membrane", "move", "A vesicle moves to the membrane"),
 ("the two membranes fuse", "fuse", "The membranes fuse"),
 ("released outside the cell", "release", "Released outside the cell"),
 ("That is exocytosis", "exo", "Exocytosis"),
 ("other ligands can be released in other ways", "bound", "This example's secretion mechanism"),
],
4: [
 ("Stage two is transport", "open", "Stage two: transport"),
 ("passes into a nearby capillary", "enter", "Into a nearby capillary"),
 ("blood carries the signal widely around the body", "carry", "Blood carries the signal widely"),
 ("reach cells through tissue fluid", "out", "Then through tissue fluid"),
 ("the liquid that bathes them", "bathe", "Tissue fluid bathes the cells"),
 ("cells of many different kinds", "kinds", "Cells of many different kinds"),
 ("Not every signal travels this far", "short", "A short-range signal (not insulin)"),
 ("diffuse through tissue fluid to cells close by", "diffuse", "Diffusion through tissue fluid"),
 ("the route is the blood", "blood", "Insulin: carried by blood"),
],
5: [
 ("Stage three is binding", "open", "Stage three: binding"),
 ("cell surface receptors", "rec", "Cell surface receptors"),
 ("this one a glycoprotein", "gp", "This one: a glycoprotein"),
 ("a binding site with a particular shape", "site", "A binding site with a particular shape"),
 ("a different signalling molecule arrive", "wrong", "A different signalling molecule"),
 ("It touches the binding site", "touch", ""),
 ("the shapes do not fit", "nofit", "Not complementary"),
 ("it drifts away", "away", ""),
 ("Now insulin", "insulin", "Now insulin"),
 ("Its shape is complementary to the binding site", "seat", "Complementary shape"),
 ("so it binds", "bound", "Bound"),
 ("Picture an address on an envelope", "env", "Handle: an address on an envelope"),
 ("opened where the address matches", "match", ""),
 ("address matches. ^The letter: insulin", "l1", "Letter → insulin, the signalling molecule"),
 ("The address: its shape", "l2", "Address → its shape"),
 ("The matching door", "l3", "Matching door → the receptor with a complementary binding site"),
 ("with a complementary binding site$", "map", "The whole mapping: letter, address, door"),
 ("Unlike the letter", "surface", "It binds at the cell surface; insulin is not taken in"),
 ("Written properly", "written", "Written properly"),
 ("the ligand binds to a specific receptor", "sent", "Binds to a specific receptor"),
],
6: [
 ("Binding starts a specific response", "open", "A specific response"),
 ("leads to an increase in glucose uptake", "uptake", "Muscle cell: more glucose uptake"),
 ("watch more glucose enter", "more", "More glucose enters after binding"),
 ("How the cell does that inside", "inside", "Inside the cell: not drawn"),
 ("here you name the response", "name", "Name the response"),
 ("Liver cells carry the same insulin receptor", "liver", "Liver cells: the same receptor"),
 ("so they respond too", "respond", "They respond too"),
 ("A cell without a complementary receptor", "other", "No complementary receptor"),
 ("does not respond to it", "none", "No response to insulin"),
 ("the blood broadcasts the message", "broad", "The blood broadcasts"),
 ("the receptors decide where it is acted on", "decide", "The receptors decide"),
 ("That is why complementary shape matters", "why", "Why complementary shape matters"),
],
7: [
 ("Here is a mistake the mark scheme names", "entry", "COMMON MISTAKE: 'active site' for a receptor"),
 ("A November 2022 question asked", "header", "Our framing of a November 2022 question"),
 ("the same signalling molecule", "ll37", ""),
 ("Read this answer", "card", "Read this answer"),
 ("Look at the words active site here", "ring", "Look at these words"),
 ("you met complementary shapes with enzymes", "enzyme", "The enzyme word"),
 ("is not turned into products here", "noprod", "No products here"),
 ("it binds to a receptor", "receptor", "It binds to a receptor"),
 ("The mark scheme for this question rejects active site", "ms", "The scheme rejects 'active site'"),
 ("that wording earns nothing", "nothing", "That wording earns nothing"),
 ("The receptor's term is binding site", "term", "Receptor → binding site"),
 ("many cell types respond", "many", "Many cell types respond"),
 ("Specific does not mean one cell type", "specific", "Specific ≠ one cell type"),
 ("share the same complementary receptor", "share", "They share the same receptor"),
 ("So, in place", "fix", "Corrected in place"),
 ("with a binding site", "c2", ""),
 ("a binding site complementary to$", "exit", "A binding site complementary to LL-37"),
],
8: [
 ("So here it is", "open", "What I told you, on the scene"),
 ("on the scene you watched", "settle", ""),
 ("Secretion: beta cells release insulin", "sec", "Secretion"),
 ("by exocytosis", "exo", ""),
 ("Transport: the blood carries it widely", "tra", "Transport"),
 ("it reaches cells through tissue fluid", "tf", ""),
 ("Binding: on target cells", "bin", "Binding"),
 ("complementary in shape", "comp", ""),
 ("muscle cells take up more glucose", "resp", "A specific response"),
 ("Cells that share the receptor can all respond", "share", "Shared receptor, shared response"),
 ("cells without it do not", "none", ""),
],
9: [
 ("How does this reach you?", "open", "How it is asked"),
 ("March 2024 Paper 22", "row1", "March 2024, Paper 22: prostaglandins"),
 ("Prostaglandins are released by cells", "l1", "Point 1: released OR transported"),
 ("then bind to receptors", "l2", "Point 2: bind to receptors"),
 ("release and transport share one", "bracket", "Release and transport: one point"),
 ("A full outline still names all three stages", "full", "A full outline: all three stages"),
 ("beyond the mark scheme", "beyond", "Beyond the mark scheme"),
 ("November 2022", "row2", "November 2022: LL-37"),
 ("shared complementary receptors", "shared", "Shared complementary receptors"),
 ("use binding site for the receptor", "reject", "Receptor: binding site"),
 ("And our hormone does not search", "search", "The hormone does not search"),
 ("blood carries it widely", "wide", ""),
 ("complementary receptors determine which cells respond", "decide", "Receptors determine which cells respond"),
],
}
