"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues plus visual-only cues that
break long holds (recorded in qa/cue-additions.md). '^' marks the trigger word inside a phrase that is
matched whole for uniqueness. An empty caption keeps the previous caption.
Captions are look-here anchors, never the narration re-typed."""
PLANS = {
1: [
 ("Ever wondered", "open", "Ever wondered how a tablet switches off one enzyme?"),
 ("a tablet", "tablet", ""),
 ("leave thousands of others running", "dim", "One enzyme stops; the others keep running (MODEL)"),
 ("Something in it binds", "binds", "Something binds to that enzyme"),
 ("the same two numbers", "boxes", "Two numbers: the same ones used to compare enzymes"),
 ("You have already drawn the graph", "graph", "Initial rate against substrate concentration"),
 ("rising, then flattening off", "redraw", "It rises, then flattens off"),
 ("compare how readily these enzymes bind their substrates", "km", "Job one: compare enzymes"),
 ("what an inhibitor does", "vmax", "Job two: what an inhibitor does"),
],
2: [
 ("By the end", "open", "By the end of this lesson"),
 ("read Vmax", "l1", ""),
 ("use Km to compare", "l2", ""),
 ("explain what a competitive", "l3", ""),
],
3: [
 ("Here is the graph again", "graph", "Read the axes first"),
 ("substrate concentration", "xlab", "Along: substrate concentration"),
 ("initial rate", "ylab", "Up: initial rate"),
 ("the very start of each run", "inset", "Initial rate: the rate at the very start (t = 0)"),
 ("the rate climbs steeply", "steep", "Low substrate: steep rise"),
 ("the active sites fill", "fill", "Active sites filling up (MODEL)"),
 ("the curve levels off", "plateau", "The curve levels off"),
 ("the maximum rate, Vmax", "vmax", "Vmax: the maximum rate"),
 ("Read it from the plateau", "pulse", "Vmax from the plateau …"),
 ("the value the question gives you", "supplied", "… or a supplied value"),
 ("still rising at the last point", "rising", "Still rising: the last point is not Vmax"),
],
4: [
 ("Now the number that lets you compare enzymes", "open", "A number to compare enzymes"),
 ("Different enzymes have different curves", "curves", "Different enzymes, different curves"),
 ("the Michaelis–Menten constant, Km", "name", "The Michaelis–Menten constant, Km"),
 ("in the words a paper used", "def", "The definition, in a paper's own words"),
 ("the substrate concentration at which", "d1", ""),
 ("half its maximum value", "d2", ""),
 ("It is a concentration", "conc", "Km is read on the concentration axis"),
 ("with concentration units", "units", ""),
 ("Km is not a rate", "notrate", "Km is not a rate"),
],
5: [
 ("Here is how you get Km from Vmax", "open", "From Vmax to Km"),
 ("drawn on the graph", "reset", "Our worked example (values match the MS reading)"),
 ("the plateau is at nine", "plateau", "Plateau: 9.0 au, so Vmax = 9.0 au"),
 ("Draw the horizontal line at Vmax", "vline", "Line at Vmax"),
 ("Halve it", "halve", "Halve it: 4.5 au"),
 ("Draw the horizontal line at half Vmax", "hline", "Line at ½Vmax"),
 ("Follow that line across", "across", "Across to the curve"),
 ("drop a vertical line", "drop", "Down to the concentration axis"),
 ("read the value: eighteen", "read", "Read the axis: 18"),
 ("Km is eighteen millimoles per decimetre cubed", "km", "Km = 18 mmol dm⁻³"),
 ("Show the construction on the graph", "strip", "Show the construction on the graph"),
 ("Vmax, half Vmax, across, down", "steps", "Vmax · ½Vmax · across · down"),
],
6: [
 ("Here is the most common error", "enter", "Common mistake: estimate Km, show working on the graph"),
 ("gave the lactase graph", "header", "The question: 9700/31 June 2023 Q1(b)(ii)"),
 ("Read this answer", "card", "Read the answer. What is missing?"),
 ("Look at the number first", "num", "The number: 18, correct"),
 ("Now look at the graph", "graph", "The graph: nothing on it"),
 ("The calculation is written out neatly", "calc", "The working is beside the graph, not on it"),
 ("The arithmetic can feel like the working", "arith", ""),
 ("the question said show your working", "said", "The question said: on the graph"),
 ("the mark scheme has three marks", "ms", "Mark scheme: three marks"),
 ("showing those values on the graph", "ms12", "Two marks: values shown on the graph"),
 ("The examiners' report says", "er", "Examiner report: the most common error"),
 ("instead of showing how Vmax and half Vmax were obtained", "er2", ""),
 ("half Vmax is a stage on the way", "stage", "½Vmax is a stage; the answer is Km"),
 ("draw the lines in place", "draw", "Draw the lines on the graph"),
 ("in place: ^Vmax across", "dv", ""),
 ("half Vmax across, down", "dh", ""),
 ("down to eighteen", "dk", ""),
 ("all three marks are on the page", "correct", "All three marks on the page"),
],
7: [
 ("So what does Km tell you", "open", "What Km tells you"),
 ("Compare two enzymes", "two", "Two enzymes, each with its own construction"),
 ("This one reaches half its maximum rate", "a", "A: half its maximum at low concentration"),
 ("its Km is small", "asmall", "A: Km small"),
 ("This one needs far more substrate", "b", "B: needs far more substrate"),
 ("its Km is large", "blarge", "B: Km large"),
 ("picture the eager enzyme", "handle", "The eager enzyme: a picture, not the answer"),
 ("Written properly", "proper", "Written properly"),
 ("a higher Km means a lower affinity", "proper2", ""),
 ("comparing the affinity of different enzymes", "syl", "What Km is for (syllabus p.20)"),
],
8: [
 ("three enzymes on one graph", "reset", "Three enzymes, X, Y and Z (our values)"),
 ("each curve separately", "trace", "Each curve separately"),
 ("Y has the highest Vmax", "yv", "Y: its own plateau, 2500"),
 ("its half line is highest", "yh", "Y: its own half line, 1250"),
 ("its Km reads four hundred", "yk", "Y: Km = 400 µmol dm⁻³"),
 ("X: its own plateau", "xv", "X: its own plateau, 1500"),
 ("its own plateau, its own ^half line", "xh", "X: its own half line, 750"),
 ("Km one hundred", "xk", "X: Km = 100 µmol dm⁻³"),
 ("Z: a low plateau", "zv", "Z: its own plateau, 600"),
 ("read from its own half line", "zh", "Z: its own half line, 300"),
 ("Km two hundred", "zk", "Z: Km = 200 µmol dm⁻³"),
 ("Lowest Km first", "order", "Lowest Km first = highest affinity first"),
 ("Y, the fastest at the top, has the lowest affinity", "ring", "Y: highest Vmax, lowest affinity"),
 ("never draw one horizontal across all three", "ghost", "Not one line across all three"),
 ("half of its own maximum", "pulse", "Each half line: half of its OWN maximum"),
],
9: [
 ("That question is a real one", "enter", "Common mistake: order of affinity"),
 ("put them in order of affinity", "header", "The question: 9700/12 June 2024 Q11"),
 ("Read these two answers", "card", "Read the two answers. What went wrong?"),
 ("Look at the first line", "l1", "Line 1: the highest plateau"),
 ("picked out the highest plateau", "yring", ""),
 ("how fast the enzyme can go when it is saturated", "yaxis", "Vmax is a rate"),
 ("That concentration is Km, a different quantity in different units", "xaxis", "Km is a concentration"),
 ("The report says some candidates confused Km with Vmax", "cite", "Examiner report, June 2024"),
 ("Now the second line", "l2", "Line 2: the steepest start"),
 ("X does happen to start steepest here", "xsteep", ""),
 ("a rate per concentration, not a concentration", "tri", "A gradient is rate ÷ concentration"),
 ("a similar proportion thought the gradient", "cite2", ""),
 ("Affinity is read from Km", "fix1", "Affinity is read from Km"),
 ("each curve, its own half Vmax", "redraw", "Each curve, its own half Vmax"),
 ("Lowest Km, highest affinity", "correct", "Lowest Km, highest affinity: X, Z, Y"),
],
10: [
 ("Now the second half", "open", "The second half"),
 ("the comparison changes", "switch", "The comparison changes"),
 ("Until now it was different enzymes", "left", "Until now: different enzymes"),
 ("the same enzyme, under the same conditions", "right", "Now: the same enzyme, with and without inhibitor"),
 ("An inhibitor is a molecule", "inh", "An inhibitor binds and lowers activity"),
 ("lowers its activity", "lower", ""),
 ("the inhibitor binds and leaves again", "binds", "Reversible: binds, then leaves"),
 ("the activity returns", "returns", "Activity returns when it leaves"),
 ("one way cells control their reactions", "cells", "Why it matters: control in cells"),
 ("how a number of medicines work", "meds", "… and medicines"),
 ("Here we compare two classes", "panels", "Two classes"),
 ("where the inhibitor binds", "where", "The difference: where it binds"),
],
11: [
 ("A competitive inhibitor has", "open", "Competitive inhibitor"),
 ("a shape similar to the substrate", "similar", "Similar shape, not identical"),
 ("the inhibitor seats", "iseat", "The inhibitor seats in the active site"),
 ("a substrate arrives", "sarr", "A substrate arrives …"),
 ("it slides away", "slide", "… and cannot seat"),
 ("the inhibitor leaves", "ileave", "The inhibitor leaves"),
 ("a substrate seats and reacts", "sseat", "Now a substrate seats and reacts"),
 ("competing for the same site", "compete", "Competing for the same site"),
 ("the more often substrate wins", "wins", "More substrate: substrate wins more often"),
 ("the inhibition can be overcome", "graph", "High substrate: the inhibition can be overcome"),
 ("Vmax is unchanged", "vmax", "Vmax unchanged"),
 ("so Km increases", "km", "Km increased"),
 ("merges with it at the plateau", "merge", "Curve to the right, merging at the plateau"),
],
12: [
 ("A non-competitive inhibitor", "open", "Non-competitive inhibitor"),
 ("binds at a different site from the substrate", "nc", "Non-competitive: a different site"),
 ("a site other than the active site", "site", "A site other than the active site"),
 ("changes the shape of the active site", "shape", "The active site changes shape"),
 ("the inhibitor seats at the other site", "iseat", "The inhibitor seats at the other site"),
 ("the cleft distorts", "distort", "The active site changes shape"),
 ("a substrate arrives and cannot seat", "fail", "No longer complementary: cannot seat"),
 ("cannot restore the uninhibited maximum rate", "crowd", "More substrate does not restore it"),
 ("does not compete for the inhibitor's binding site", "nocomp", "Substrate does not compete for that site"),
 ("In the simplified model drawn here", "graph", "Simplified non-competitive model"),
 ("Vmax decreases", "vdec", "Vmax decreased"),
 ("does not restore it", "bracket", "The plateaux stay apart"),
 ("Km is unchanged", "km", "Each curve from its own half Vmax"),
 ("at the same concentration", "same", "Km unchanged: the same concentration"),
 ("When the inhibitor leaves", "leave", "When the inhibitor leaves …"),
 ("activity comes back", "back", "… the shape returns: reversible"),
],
13: [
 ("Here is where the two curves get swapped", "enter", "Common mistake: the two curves swapped"),
 ("sulfonamide is a competitive inhibitor", "header", "The question: 9700/23 June 2023 Q3(b)(ii)"),
 ("Read this sketch", "card", "Read the sketch. What is wrong?"),
 ("Look at where the sketched curve ends", "end", "Where does the sketch end?"),
 ("its own lower plateau", "gap", "Its own lower plateau"),
 ("That is the non-competitive shape", "nctitle", "That is the non-competitive shape"),
 ("the question said competitive", "said", "The question said competitive"),
 ("Both inhibited curves lie below the original", "low", "At low concentrations both lie below"),
 ("what happens at high substrate", "high", "Ask: what happens at high substrate?"),
 ("can be overcome by more substrate", "replay", "Competitive: overcome by more substrate"),
 ("meet the original plateau", "arrow", "So it must meet the original plateau"),
 ("The June 2023 report says", "cite", "Examiner report, June 2023"),
 ("which an inhibitor does not do", "strike", "An inhibitor does not go above the maximum"),
 ("The March 2023 Paper 1 report", "cite2", "Examiner report, March 2023"),
 ("Redraw it", "correct", "Redrawn: below first, then merging at the plateau"),
 ("Vmax unchanged, Km increased", "labels", "Vmax unchanged, Km increased: competitive"),
],
14: [
 ("Now the sentences you write", "open", "The sentences you write"),
 ("For Km", "b1", "For Km"),
 ("Vmax is the maximum initial rate", "c1", ""),
 ("read by construction from each enzyme's own curve", "c2", ""),
 ("a lower Km means a higher affinity", "c3", ""),
 ("For inhibitors", "b2", "For inhibitors"),
 ("binds reversibly in the active site", "c4", "Competitive"),
 ("Vmax is unchanged and Km increases", "c5", ""),
 ("because more substrate can overcome it", "c5b", "The causal link: because"),
 ("binds at a site other than the active site", "c6", "Non-competitive (simplified model)"),
 ("Vmax decreases and Km is unchanged", "c7", ""),
],
15: [
 ("So here is the whole lesson", "open", "What I told you, on the graph and the model"),
 ("Vmax from the plateau", "v", "Vmax from the plateau"),
 ("Half it, across, down", "hk", "Half it, across, down"),
 ("Km, a concentration", "x", "Km: a concentration"),
 ("each enzyme's Km from its own half Vmax", "strip", "Each enzyme from its own half Vmax"),
 ("competitive, in the active site", "comp", "Competitive: in the active site"),
 ("the curve merges at the plateau", "merge", "Merges at the plateau"),
 ("Non-competitive, at another site", "nc", "Non-competitive: another site"),
 ("Vmax decreased, Km unchanged in this model", "nclab", "Vmax decreased, Km unchanged (this model)"),
 ("Both reversible", "rev", "Both reversible"),
],
16: [
 ("How this reaches you", "open", "How it is asked"),
 ("estimate Km, show your working on the graph", "r1", ""),
 ("two for showing the values on the graph", "r1b", ""),
 ("sketch the effect of a competitive inhibitor", "r2", ""),
 ("the merge at the plateau is a mark", "r2b", ""),
 ("the order of affinity of three enzymes", "r3", ""),
 ("a row for the effect of a competitive inhibitor", "r4", ""),
 ("which lines on a graph belong to which mixture", "r5", ""),
 ("suggest why an enzyme's Km is lower", "r6", ""),
 ("The reject", "reject", "The reject: Km is not a rate"),
],
17: [
 ("Here is the question itself", "q", "The real question: 9700/31 June 2023 Q1(b)(ii)"),
 ("Read it", "read", "Read it: estimate Km; show working on the graph"),
 ("the three marks land on our graph", "marks", "Three marks, on our graph"),
 ("our graph: ^Vmax shown", "m1", ""),
 ("half Vmax shown", "m2", ""),
 ("shown, eighteen", "m3", ""),
 ("And the tablet", "tablet", "And the tablet?"),
 ("in the active site or beside it", "sites", "It binds one enzyme, reversibly"),
 ("need not fit the rest", "rest", "Other enzymes: different active sites"),
 ("read off a graph", "flash", "Which kind? Read it off the graph"),
],
}
