"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered", "open", "About 2 m of DNA, a nucleus a few µm across"),
 ("about two metres of DNA", "pay", ""),
 ("a few micrometres across", "bar", "Nucleus: a few µm across (typical)"),
 ("laid end to end", "row", "Laid end to end: about 2 m (typical)"),
 ("not a loose tangle", "rewind", "Not a tangle: orderly loops"),
 ("hands a complete copy", "divide", "A complete copy to each new cell"),
 ("packing its DNA into chromosomes", "model", "Simplified model cell: 2n = 4"),
 ("what is a chromosome", "lift", "So what is a chromosome?"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("describe a chromosome from five structures", "l1", ""),
 ("structures: DNA", "d1", ""),
 ("histone proteins", "d2", ""),
 ("sister chromatids", "d3", ""),
 ("the centromere", "d4", ""),
 ("and telomeres", "d5", ""),
 ("tell a chromosome before replication", "l2", ""),
 ("count chromosomes and DNA molecules", "l3", ""),
],
3: [
 ("Start small", "open", "Start small: DNA (Z2)"),
 ("two strands twisted together", "strands", "Two strands: a helix"),
 ("wind around beads of protein", "wind", "DNA winds round beads of protein"),
 ("These are histone proteins", "histone", "Histone proteins"),
 ("successive histone beads", "succ", ""),
 ("short stretches of DNA linking them", "linker", "Short linking stretches of DNA"),
 ("Written properly", "written", "Written properly"),
 ("one long DNA molecule associated", "sentence", ""),
 ("a couple of metres", "pack", "Packing: DNA with histones"),
],
4: [
 ("Pull back", "open", "Pull back: one whole chromosome"),
 ("is a whole chromosome", "chrom", ""),
 ("Along it sit genes", "genes", "Genes at fixed places"),
 ("The centromere is a constricted region", "cen", "The centromere: a constriction"),
 ("looks pinched in", "pinch", ""),
 ("each end is a telomere", "tel", "A telomere at each end"),
 ("a short sequence repeated many times", "repeat", "A short sequence, repeated"),
 ("does not code for a protein", "noncoding", "Non-coding DNA"),
 ("What telomeres do comes later", "later", "Their role: 5.1.4"),
 ("find them at the ends", "ends", ""),
],
5: [
 ("Before a cell divides", "open", "Before a cell divides"),
 ("it copies its DNA", "copies", "The DNA is copied"),
 ("the synthesis, or S, phase of interphase", "sphase", "In the S phase of interphase"),
 ("Watch the copy build", "build", "The copy builds along the molecule"),
 ("When it is complete", "complete", "Complete: two DNA molecules"),
 ("each with its own histones", "histones", ""),
 ("genetically identical", "identical", "Identical: one is a copy of the other"),
 ("The genes match", "genes", "Same bands, same places"),
 ("These are sister chromatids", "sisters", "Sister chromatids"),
 ("joined at the centromere", "cen", "Joined at the centromere"),
],
6: [
 ("In a cell that is not dividing", "open", "In a cell that is not dividing"),
 ("long, thin and spread out", "thin", "Long, thin and spread out"),
 ("far too fine", "fine", "Too fine to pick out"),
 ("As division begins", "begin", "As division begins"),
 ("it coils more tightly", "coil", "Condensing: coiling more tightly"),
 ("shorter and thicker", "thick", ""),
 ("once stained, you can see it", "visible", "Visible with a light microscope"),
 ("the familiar X shape", "x", "The familiar X shape"),
 ("held at the centromere", "held", ""),
 ("each of the four ends", "four", "Four ends: four telomeres"),
],
7: [
 ("Now the trap", "open", "Now the trap"),
 ("How many chromosomes is this X", "how", "How many chromosomes?"),
 ("Picture a page and its photocopy", "staple", "A page and its photocopy, one staple"),
 ("still one stapled set", "set", ""),
 ("Written properly", "written", "Written properly"),
 ("each its own DNA molecule", "each", ""),
 ("count chromosomes by counting centromeres", "rule1", "Chromosomes: count centromeres"),
 ("count DNA molecules separately", "rule2", "DNA molecules: count separately"),
 ("Before replication, one centromere", "before", "Before: 1 centromere · 1 DNA molecule"),
 ("still one centromere, but two DNA molecules", "after", "After: 1 centromere · 2 DNA molecules"),
],
8: [
 ("Now a whole cell", "open", "A whole cell (model, 2n = 4)"),
 ("two long and two short", "four", ""),
 ("each colour is a different chromosome", "key", "Colour = which chromosome"),
 ("the whole cell has four centromeres", "count", "Whole cell: 4 centromeres"),
 ("After replication, still four chromosomes", "rep", "After replication: still 4 chromosomes"),
 ("eight DNA molecules in eight sister chromatids", "eight", "8 DNA molecules in 8 sister chromatids"),
 ("A typical diploid human somatic cell", "human", "Typical diploid human somatic cell"),
 ("forty-six chromosomes before and after", "h46", ""),
 ("ninety-two after", "h92", "46 chromosomes; 92 DNA molecules after"),
],
9: [
 ("when does the count go up", "open", "When does the count go up?"),
 ("Later, in mitosis", "line", "Later, in mitosis (5.2.1)"),
 ("centromere divides", "divide", "The centromere divides"),
 ("has its own centromere", "own", ""),
 ("it is a daughter chromosome", "daughter", "Each: a daughter chromosome"),
 ("still carrying its own DNA molecule", "dna", ""),
 ("eight chromosomes and eight DNA molecules", "eight", "Whole cell: 8 chromosomes · 8 DNA molecules"),
 ("move to opposite poles", "move", "To opposite poles"),
 ("each pole receives four", "pole", "One pole: 4 chromosomes · 4 DNA molecules"),
 ("How they move comes with mitosis", "how", ""),
],
10: [
 ("on the chromosome you built", "open", "What I told you"),
 ("one long molecule in each chromatid", "dna", ""),
 ("wound around histone proteins", "hist", ""),
 ("two identical sister chromatids", "sisters", ""),
 ("joined at the centromere", "cen", ""),
 ("telomeres at the ends", "tel", ""),
 ("Coiled up for division", "coil", ""),
 ("Count centromeres for chromosomes", "count", ""),
 ("name the part of the cell", "comp", ""),
 ("And the two metres", "metres", "And the two metres?"),
 ("it fits", "fits", "Histones and coiling: it fits"),
],
11: [
 ("How does this reach you", "open", "How it is asked"),
 ("labelled a structure A", "row1", "June 2023: name and function of A"),
 ("asked for its name and function", "answer", ""),
 ("carried one mark", "mark", ""),
 ("Name it centromere", "name", "Name: centromere"),
 ("holding the sister chromatids together", "hold", "Function: holds the sister chromatids together"),
 ("rejected the words daughter chromatids", "reject", ""),
 ("a chromosome cloze", "row2", "Also: a cloze and multiple choice"),
 ("multiple-choice items", "row3", ""),
 ("The reject card", "card", "The reject card"),
 ("still one chromosome", "one", ""),
 ("joined at the centromere$", "exit", ""),
],
}
