'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useMutation, useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';
import { AuthShell, buttonClass, secondaryButtonClass } from '@/components/auth-shell';
import { RegistrationGate } from '@/components/registration-gate';

export default function GuardianLinkPage() {
  return (
    <RegistrationGate>
      <GuardianLink />
    </RegistrationGate>
  );
}

/**
 * The student's side of the link. The student generates; the guardian redeems.
 * The direction is the control: if a guardian could invite a student by email,
 * the platform would hold a route from an adult to a named child, which is the
 * one channel §11.1 exists to not have.
 */
function GuardianLink() {
  const state = useQuery(api.session.guardianState, {});
  const status = useQuery(api.session.status, {});
  const createCode = useMutation(api.identity.createGuardianLinkCode);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  if (state === undefined || status === undefined) return null;
  if (state?.side !== 'student') {
    return (
      <AuthShell title="This page is for students" lede="Link codes are generated by the student, then read out to a guardian.">
        <Link href="/account" className={secondaryButtonClass}>
          Back to your account
        </Link>
      </AuthShell>
    );
  }

  const open = state.codes.filter((c) => c.state === 'open');

  async function generate() {
    setError(null);
    setBusy(true);
    try {
      await createCode({});
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not create a code.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <AuthShell
      eyebrow="Guardian link"
      title="Give a parent or guardian a code"
      lede={
        <>
          You make the code. You read it to them. They type it into their own
          account. There is no way for an adult to find you and ask — the invitation
          has to start with you.
        </>
      }
      footer={
        <Link href="/account" className={secondaryButtonClass}>
          Back to your account
        </Link>
      }
    >
      {status.user?.isMinor ? (
        <p className="mb-6 rounded-lg border border-grid-line bg-paper px-3 py-2.5 text-sm leading-relaxed text-ink">
          Studying is free and needs nobody&apos;s permission. Because you are
          under 18, <strong>paying to have your work marked will need a linked
          guardian first.</strong> Linking now means that is already done when you
          want it.
        </p>
      ) : null}

      <button type="button" onClick={generate} disabled={busy} className={buttonClass}>
        {busy ? 'Making a code…' : 'Create a new code'}
      </button>

      {error ? (
        <p role="alert" className="mt-4 rounded-lg border border-accent/40 bg-accent/5 px-3 py-2.5 text-sm">
          {error}
        </p>
      ) : null}

      {open.length > 0 ? (
        <div className="mt-6">
          <h2 className="text-sm font-semibold text-ink">Ready to read out</h2>
          <ul className="mt-2 space-y-2">
            {open.map((c) => (
              <li
                key={c.code}
                className="flex flex-wrap items-baseline justify-between gap-2 rounded-lg border border-grid-line bg-paper px-3 py-2.5"
              >
                <code className="font-mono text-lg font-semibold tracking-[0.08em] text-ink">
                  {c.code}
                </code>
                <span className="text-xs text-ink-muted">
                  expires {new Date(c.expiresAt).toLocaleDateString()}
                </span>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[0.8rem] leading-relaxed text-ink-muted">
            A code works once and lasts seven days. There are no letters that look
            like each other in it — no I, L, O or U — so reading it aloud is safe.
          </p>
        </div>
      ) : null}

      {state.codes.length > open.length ? (
        <div className="mt-8">
          <h2 className="text-sm font-semibold text-ink">Earlier codes</h2>
          <ul className="mt-2 space-y-1 text-sm text-ink-muted">
            {state.codes
              .filter((c) => c.state !== 'open')
              .map((c) => (
                <li key={c.code}>
                  <code className="font-mono">{c.code}</code> — {c.state}
                </li>
              ))}
          </ul>
          <p className="mt-2 text-[0.8rem] text-ink-muted">
            Used and expired codes stay on this list rather than disappearing, so
            there is always a record of who was given a way in.
          </p>
        </div>
      ) : null}
    </AuthShell>
  );
}
