import React from 'react';
import transcript from '../public/transcripts/mechanics/connected-bodies-lifts.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-m42/Ink';
const scenes=transcript.scenes as Scene[];
export type MechanicsConnectedBodiesLiftsProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsConnectedBodiesLiftsDuration=(fps:number)=>duration(scenes,fps);
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string}>=({x,y,children,size=28,fill=T.text})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size}>{children}</text>;
const Arrow:React.FC<{x:number;y:number;dy:number;accent?:boolean}>=({x,y,dy,accent=false})=><path data-force-arrow="true" d={`M${x} ${y} v${dy}`} stroke={accent?T.accent:T.text} strokeWidth={4} fill="none" markerEnd={accent?'url(#lift-green)':'url(#lift-white)'}/>;
const Person:React.FC<{x?:number;y?:number;muted?:boolean}>=({x=370,y=340,muted=false})=><g transform={`translate(${x} ${y})`} opacity={muted?.2:1}><circle cy={-90} r={22} fill={T.text}/><path d="M-20 -61 Q0 -73 20 -61 L28 0 H-28 Z" fill={T.accent}/><path d="M-12 0 L-18 55 M12 0 L18 55 M-20 -54 L-40 -9 M20 -54 L40 -9" fill="none" stroke={T.text} strokeWidth={9} strokeLinecap="round"/></g>;
const Cabin:React.FC<{y?:number;passenger?:boolean;muted?:boolean}>=({y=220,passenger=true,muted=false})=><g data-lift-y={y} transform={`translate(0 ${y})`} opacity={muted?.25:1}><path d="M365 -100 V0" stroke={T.muted} strokeWidth={5}/><rect x={255} y={0} width={220} height={270} rx={5} fill="#293431" stroke={T.text} strokeWidth={4}/><path d="M255 268 H475" stroke={T.text} strokeWidth={10}/>{passenger&&<Person x={365} y={210}/>}</g>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs><marker id="lift-white" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.text} strokeWidth={1.5}/></marker><marker id="lift-green" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.accent} strokeWidth={1.5}/></marker></defs>{children}</svg>;
const Note:React.FC<{text:string}>=({text})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}><Caption x={24} y={85} text={text}/></svg>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{b.id==='answer'&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{const accel=['passenger','combined'].includes(s.mode)||s.mode==='acceleration'&&t>=at(s,'answer');const reaction=s.mode==='combined'||s.mode==='passenger'&&t>=at(s,'answer');const tension=s.mode==='combined'&&t>=at(s,'answer');return <g><path d="M35 588 H895" stroke={T.muted} strokeWidth={1}/><Figure id="liftMass" x={45} y={636} size={27}>M = 400 kg</Figure><Figure id="mass" x={355} y={636} size={27}>m = 60 kg</Figure><Figure id="gravity" x={625} y={636} size={27}>g = 10 m s⁻²</Figure><Figure id="initial" x={45} y={689} size={27}>u = +4 m s⁻¹</Figure><Figure id="final" x={355} y={689} size={27}>v = 0 m s⁻¹</Figure><Figure id="time" x={680} y={689} size={27}>t = 2 s</Figure><Figure id="acceleration" x={45} y={742} size={27}>{accel?'a = −2 m s⁻²':'a = ?'}</Figure><Figure id="reaction" x={355} y={742} size={27}>{reaction?'R = 480 N':'R = ?'}</Figure><Figure id="tension" x={625} y={742} size={27}>{tension?'T = 3680 N':'T = ?'}</Figure></g>;};
const Forces:React.FC<{kind:'passenger'|'combined'|'lift';state?:'brake'|'steady'|'speedup';results?:boolean;weight?:boolean}>=({kind,state='brake',results=false,weight=false})=>{const len=state==='steady'?200:state==='speedup'?240:160;return <g>{kind==='passenger'?<><Person x={365} y={330}/><path d="M285 390 H445" stroke={T.muted} strokeWidth={4}/><Arrow x={255} y={350} dy={-len} accent/><Txt x={45} y={205}>{results?'R = 480 N':'R'}</Txt><Arrow x={475} y={350} dy={200}/><Figure id="weight" x={515} y={500} size={28}>{weight?'mg = 600 N':'mg'}</Figure></>:<><Cabin y={200} passenger={kind==='combined'}/>{kind==='combined'&&<rect x={238} y={180} width={255} height={310} rx={14} stroke={T.accent} strokeWidth={3} strokeDasharray="12 9" fill="none"/>}<Arrow x={540} y={360} dy={kind==='lift'? -184:-len} accent/><Txt x={585} y={220}>{results?'T = 3680 N':'T'}</Txt><Arrow x={190} y={350} dy={200}/><Figure id="weight" x={35} y={520} size={27}>{kind==='combined'?weight?'4600 N':'(M + m)g':'Mg'}</Figure>{kind==='lift'&&<><Arrow x={550} y={410} dy={24}/><Txt x={590} y={500}>R</Txt></>}</>}{state==='steady'?<Txt x={665} y={435}>a = 0</Txt>:<><Arrow x={755} y={state==='speedup'?465:340} dy={state==='speedup'?-105:105} accent/><Txt x={800} y={400}>a</Txt></>}<Arrow x={845} y={270} dy={-90}/><Txt x={798} y={150} size={24}>v up</Txt></g>;};
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Cabin y={240}/><Arrow x={630} y={490} dy={-180} accent/><Txt x={240} y={640}>Passenger + lift</Txt></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.4 · excerpt · p.33</Txt>{['“solve simple problems which','may be modelled as the motion','of connected particles.”'].map((x,i)=><Txt key={x} x={35} y={155+i*65} size={36} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){const cruise=at(s,'cruise'),brake=at(s,'brake'),stop=at(s,'stop');const active=(v:number)=>v-s.holds.reduce((n,h)=>n+Math.max(0,Math.min(v,h.end)-h.start),0);const dc=active(brake)-active(cruise),db=active(stop)-active(brake),v=270/(dc+db/2),tc=Math.max(0,Math.min(dc,active(t)-active(cruise))),tb=Math.max(0,Math.min(db,active(t)-active(brake))),q=tb/db;const y=420-v*tc-v*(tb-tb*tb/(2*db));return <><Stage><path d="M180 20 V780 M550 20 V780" stroke="#596660" strokeWidth={4}/>{[130,430,730].map(y=><path key={y} d={`M130 ${y} H180 M550 ${y} H600`} stroke={T.muted} strokeWidth={6}/>)}<Cabin y={y}/>{t>=cruise&&t<stop&&<><Arrow x={680} y={y+240} dy={-100*(1-q)} accent/><Txt x={630} y={y+305}>Moving up</Txt></>}{t>=stop&&<Txt x={620} y={410}>Stopped</Txt>}</Stage><Note text={t>=stop?'Now analyse the braking interval':t>=brake?'Moving up, slowing down':t>=cruise?'Steady upward motion':'A passenger rides upwards'}/></>;}
 if(s.mode==='problem')return <><Stage><Cabin y={210}/><Txt x={35} y={35}>During uniform braking · up is positive</Txt><Arrow x={620} y={340} dy={-100}/><Txt x={655} y={280}>Moving up</Txt><Values s={s} t={t}/></Stage><svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{['Contact maintained; cable taut.','No other external vertical forces.','Find a, floor reaction R, cable tension T.'].map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={31}>{x}</Txt>{((i===0&&['gravity','conditions'].includes(b?.id??''))||(i===1&&b?.id==='conditions')||(i===2&&b?.id==='unknown'))&&<path d={`M30 ${138+i*150} H750`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b!.cue)/.5)}/>}</g>)}</svg></>;
 if(s.mode==='acceleration')return <><Stage><Txt x={35} y={35}>Braking interval · up is positive</Txt><Cabin y={205}/><Arrow x={600} y={365} dy={-125}/><Txt x={645} y={270}>Velocity up</Txt>{t>=at(s,'answer')&&<><Arrow x={600} y={390} dy={130} accent/><Txt x={645} y={500}>Acceleration down</Txt></>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;
 if(s.mode==='passenger'||s.mode==='combined')return <><Stage><Txt x={35} y={35}>{s.mode==='passenger'?'Selected body: passenger':'Selected system: lift + passenger'}</Txt><Forces kind={s.mode} results={t>=at(s,'answer')} weight={t>=at(s,'simplify')}/>{t>=at(s,'simplify')&&<Figure id="net" x={35} y={90} size={25}>{s.mode==='passenger'?'Resultant = 120 N down':'Resultant = 920 N down'}</Figure>}{s.mode==='combined'&&t>=at(s,'internal')&&t<at(s,'formula')&&<g><Arrow x={290} y={447} dy={-80} accent/><Txt x={260} y={350} size={23}>R</Txt><Arrow x={440} y={380} dy={80} accent/><Txt x={445} y={360} size={23}>R</Txt></g>}{s.mode==='combined'&&t>=at(s,'mass')&&<Figure id="total" x={285} y={570} size={25}>M + m = 460 kg</Figure>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;
 if(s.mode==='contrast'){const answered=t>=at(s,'answer'),speedup=t>=at(s,'whatif');return <><Stage><Txt x={35} y={35}>{speedup?'New condition: speeding up upwards':'New condition: constant upward velocity'}</Txt>{answered?<Forces kind={t>=at(s,'system')?'combined':'passenger'} state={speedup?'speedup':'steady'}/>:<><Cabin y={230}/><Arrow x={640} y={420} dy={-120}/><Txt x={690} y={360}>v up</Txt></>}<Txt x={155} y={650}>{speedup?'Supporting force exceeds weight':answered?'Supporting force equals weight':'Has the acceleration changed?'}</Txt></Stage>{speedup?<Note text="Greater support force → upward acceleration"/>:answered?<Paper s={s} t={t}/>:<Note text="Is acceleration still downwards?"/>}</>;}
 return <><Stage><Txt x={35} y={35}>Selected body: lift alone · braking</Txt><Forces kind="lift"/><Txt x={105} y={660}>Passenger pushes floor down</Txt></Stage>{b?.caption?<Note text={`✓ ${b.caption}`}/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsConnectedBodiesLifts:React.FC<MechanicsConnectedBodiesLiftsProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
