import React from 'react';
import transcript from '../public/transcripts/mechanics/coefficient-of-friction-f-equals-ma-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/coefficient-of-friction-f-equals-ma-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsCoefficientOfFrictionFEqualsMaFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsCoefficientOfFrictionFEqualsMaFableDuration=(fps:number)=>duration(scenes,fps);
/* Force scales on the crate diagram: horizontal 12 px per newton (X, f, H compare by length); vertical 4.5 px per newton (R against mg). */
const HX=12,VX=4.5,FLOOR=460,CX=430,CW=240,CH=130,TOP=FLOOR-CH;
const SQ3=Math.sqrt(3);
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
const Line:React.FC<{children:React.ReactNode}>=({children})=><Txt x={40} y={84} size={26}>{children}</Txt>;
/* Arrows carry data-label so the still audit includes their extents in the collision check. */
const Arrow:React.FC<{x:number;y:number;dx?:number;dy?:number;accent?:boolean;width?:number;dashed?:boolean}>=({x,y,dx=0,dy=0,accent=false,width=4,dashed=false})=><g data-label="true" data-force-arrow="true"><rect x={Math.min(x,x+dx)-6} y={Math.min(y,y+dy)-6} width={Math.abs(dx)+12} height={Math.abs(dy)+12} fill="none" stroke="none"/><path d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={width} fill="none" strokeDasharray={dashed?'10 8':undefined} markerEnd={accent?'url(#cfm-green)':'url(#cfm-white)'}/></g>;
const Crate:React.FC<{x?:number}>=({x=CX})=><g data-crate-x={x}><rect x={x-CW/2} y={TOP} width={CW} height={CH} rx={6} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M${x-CW/2+8} ${FLOOR-CH*.5} H${x+CW/2-8} M${x-CW/2+8} ${FLOOR-CH*.72} H${x+CW/2-8}`} stroke="#4a3624" strokeWidth={3}/><Txt x={x-CW*.2} y={FLOOR-CH*.18} size={26}>crate</Txt></g>;
const Floor:React.FC<{x0?:number;x1?:number;y?:number}>=({x0=40,x1=890,y=FLOOR})=><g><path d={`M${x0} ${y} H${x1}`} stroke={T.text} strokeWidth={5}/>{Array.from({length:Math.floor((x1-x0-20)/50)},(_,i)=><path key={i} d={`M${x0+20+i*50} ${y+4} l-14 16`} stroke={T.muted} strokeWidth={2}/>)}</g>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs><marker id="cfm-white" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.text} strokeWidth={1.5}/></marker><marker id="cfm-green" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.accent} strokeWidth={1.5}/></marker></defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{['answer','subR','sublimit','hvalue','vvalue','whatif2'].includes(b.id)&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* Vertical pair (R grows or shrinks with the extra force), the rope X, friction f, and the extra force P in one of three directions. */
type Extra='none'|'down'|'up'|'angled'|'components';
const Forces:React.FC<{R:number;Rlabel?:string;mgLabel?:string;pull?:number;pullLabel?:string;friction?:number;frictionLabel?:string;extra?:Extra;extraLabel?:string;angleLabel?:boolean;accentR?:boolean;accentFriction?:boolean;hLabel?:string;vLabel?:string;showMg?:boolean}>=({R,Rlabel='R',mgLabel='mg',showMg=true,pull=0,pullLabel='X',friction=0,frictionLabel='f',extra='none',extraLabel='8 N',angleLabel=true,accentR=false,accentFriction=false,hLabel='H',vLabel='V'})=><g>
 <Arrow x={CX} y={TOP} dy={-R*VX} accent={accentR}/><Txt x={CX-16} y={TOP-R*VX+14} anchor="end">{Rlabel}</Txt>
 {showMg&&<><Arrow x={CX} y={FLOOR} dy={40*VX}/><Figure id="weight" x={CX+18} y={FLOOR+40*VX+2} size={28}>{mgLabel}</Figure></>}
 {pull>0&&<><Arrow x={CX+CW/2} y={FLOOR-70} dx={pull*HX} accent/><Txt x={CX+CW/2+12} y={FLOOR-70+40} size={28}>{pullLabel}</Txt></>}
 {friction>0&&<><Arrow x={CX-CW/2} y={FLOOR-70} dx={-friction*HX} accent={accentFriction}/><Txt x={CX-CW/2-12} y={FLOOR-70+40} size={28} anchor="end">{frictionLabel}</Txt></>}
 {extra==='down'&&<><Arrow x={CX+72} y={TOP-8*VX-40} dy={8*VX+34}/><Txt x={CX+88} y={TOP-8*VX-24} size={26}>{extraLabel}</Txt></>}
 {extra==='up'&&<><Arrow x={CX+72} y={TOP-6} dy={-8*VX-30}/><Txt x={CX+88} y={TOP-8*VX-22} size={26}>{extraLabel}</Txt></>}
 {extra==='angled'&&<><Arrow x={CX+CW/2} y={TOP} dx={8*HX*SQ3/2} dy={-8*HX/2} accent/>{extraLabel&&<Txt x={CX+CW/2+8*HX*SQ3/2+20} y={TOP-8*HX/2+2} size={26}>{extraLabel}</Txt>}<path d={`M${CX+CW/2+40} ${TOP} A40 40 0 0 0 ${CX+CW/2+40*SQ3/2} ${TOP-20}`} fill="none" stroke={T.muted} strokeWidth={2}/>{angleLabel&&<Txt x={CX+CW/2+104} y={TOP-6} size={22} fill={T.muted}>30°</Txt>}</>}
 {extra==='components'&&<><Arrow x={CX+CW/2} y={TOP} dx={4*SQ3*HX} accent dashed/><Txt x={CX+CW/2+12} y={TOP+40} size={26}>{hLabel}</Txt><Arrow x={CX+CW/2+14} y={TOP-14} dy={-4*VX-14} accent dashed/><Txt x={CX+CW/2+30} y={TOP-4*VX-34} size={26}>{vLabel}</Txt></>}
</g>;
/* Large component triangle beside the crate: hypotenuse 8 N, base H, vertical V, 30° at the origin. Sides appear one at a time. */
const Triangle:React.FC<{t:number;h:number;v:number;hDone:boolean;vDone:boolean;hLabel:string;vLabel:string}>=({t,h,v,hDone,vDone,hLabel,vLabel})=>{const ox=680,oy=300,L=270,dx=L*SQ3/2,dy=L/2;const p=clamp((t-h)/.6),q=clamp((t-v)/.6);return <g>
 <path d={`M${ox} ${oy} L${ox+dx} ${oy-dy}`} stroke={T.accent} strokeWidth={5} fill="none" markerEnd="url(#cfm-green)"/><Txt x={ox+dx/2-60} y={oy-dy/2-22} size={26}>8 N</Txt>
 <path d={`M${ox+50} ${oy} A50 50 0 0 0 ${ox+50*SQ3/2} ${oy-25}`} fill="none" stroke={T.text} strokeWidth={2}/><Txt x={ox+58} y={oy-6} size={24}>30°</Txt>
 {t>=h&&<><path d={`M${ox} ${oy} H${ox+dx}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-p} fill="none"/><Txt x={ox+40} y={oy+40} size={26}>{hDone?hLabel:'H'}</Txt></>}
 {t>=v&&<><path d={`M${ox+dx} ${oy} V${oy-dy}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><Txt x={ox+dx-8} y={oy-dy-18} size={26} anchor="end">{vDone?vLabel:'V'}</Txt></>}
</g>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const m=s.mode;const after=(id:string)=>s.cues[id]!==undefined&&t>=at(s,id);
 const R=m==='parta'?after('subR')?'R = 48 N':'R = ?':m==='resolve'?'R = ?':m==='limit'?after('subR')?'R = 36 N':'R = ?':m==='newton'?'R = 36 N':m==='closing'?after('whatif')?'R = 32 N':'R = ?':'R = ?';
 const fmax=m==='parta'?after('sublimit')?'f max = 12 N':'f max = ?':m==='limit'?after('sublimit')?'f max = 9 N':'f max = ?':m==='newton'?'f max = 9 N':m==='closing'?after('whatif2')?'f max = 8 N':'f max = ?':'f max = ?';
 const f=m==='parta'?after('answer')?'f = 9 N':'f = ?':m==='limit'?after('decide')?'f = 9 N':'f = ?':m==='newton'?'f = 9 N':m==='closing'?after('whatif2')?'f = 8 N':'f = ?':'f = ?';
 const a=m==='parta'?after('answer')?'a = 0':'a = ?':m==='newton'?after('answer')?'a = √3 ≈ 1.73 m s⁻²':'a = ?':'a = ?';
 return <g><path d="M35 655 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={700} size={27}>m = 4 kg</Figure><Figure id="mu" x={205} y={700} size={27}>μ = 0.25</Figure><Figure id="gravity" x={370} y={700} size={27}>g = 10 m s⁻²</Figure><Figure id="pull" x={600} y={700} size={27}>X = 9 N</Figure><Figure id="extra" x={745} y={700} size={27}>P = 8 N</Figure><Figure id="R" x={45} y={748} size={27}>{R}</Figure><Figure id="fmax" x={205} y={748} size={27}>{fmax}</Figure><Figure id="f" x={440} y={748} size={27}>{f}</Figure><Figure id="a" x={600} y={748} size={27}>{a}</Figure></g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Rough floor, μ = 0.25; rope pulls 9 N horizontally.','(a) 8 N presses straight down: does it move?','(b) 8 N pulls at 30° above horizontal: find f, a.'];const active=b?.id==='crate'||b?.id==='rope'?0:b?.id==='parta'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={30}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Slide displacement (px) with constant acceleration from a cue, on the hold-frozen clock t. */
const slide=(t:number,from:number,k:number,max:number)=>Math.min(max,Math.max(0,.5*k*(t-from)*(t-from)));
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Floor/><Crate/><Forces R={40} pull={9} friction={9} extra="angled" accentFriction/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.4 · excerpt · p.33</Txt>{['“apply Newton’s laws','of motion”'].map((x,i)=><Txt key={x} x={35} y={165+i*70} size={38} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){const press=at(s,'press'),angle=at(s,'angle'),sl=at(s,'slide');const grow=(a:number)=>clamp((t-a)/1.2);
  const R=t<press?40:t<angle?40+8*grow(press):40-4*grow(angle);const extra:Extra=t<press?'none':t<angle?'down':'angled';const dx=t>=sl?slide(t,sl,10,70):0;
  const caption=t>=sl?'Pulled at an angle: it slides':t>=angle?'Pulled at an angle: R shrinks':t>=press?'Pressed down: R grows, grip grows':'Rope pulls; friction holds';
  return <><Stage><g transform={`translate(-230 -90) scale(1.5) translate(${dx/1.5} 0)`}><Crate/><Forces R={R} showMg={false} pull={9} pullLabel="rope" friction={9} frictionLabel="friction" extra={extra} extraLabel={extra==='down'?'push':'rope 2'} accentR={t>=press&&t<angle+1.4} accentFriction={t>=sl}/></g><Floor y={FLOOR*1.5-90} x0={20} x1={910}/>{t>=sl&&<g><Arrow x={520+dx} y={200} dx={110} accent/><Txt x={505+dx} y={185} size={26}>accelerates</Txt></g>}<Caption x={60} y={720} text={caption}/></Stage></>;}
 if(s.mode==='concept'){const down=at(s,'down'),up=at(s,'up'),ang=at(s,'angled');const extra:Extra=t>=ang?'angled':t>=up?'up':t>=down?'down':'none';const R=extra==='down'?48:extra==='up'?32:40;
  return <><Stage><Txt x={35} y={35}>{extra==='angled'?'Angled force: one part along, one part up':extra==='up'?'Pulling up: R smaller than the weight':extra==='down'?'Pressing down: R bigger than the weight':'R balances the vertical forces'}</Txt><Floor/><Crate/><Forces R={R} pull={9} friction={9} extra={extra} extraLabel="P" angleLabel={false} accentR={extra!=='none'&&extra!=='angled'} accentFriction/>{extra==='angled'&&<><path d={`M${CX+CW/2} ${TOP} h${8*HX*SQ3/2} v${-8*HX/2}`} fill="none" stroke={T.accent} strokeWidth={3} strokeDasharray="9 7"/><Txt x={CX+CW/2+30} y={TOP+40} size={24}>along</Txt><Txt x={CX+CW/2+8*HX*SQ3/2+12} y={TOP-14} size={24}>up</Txt></>}{b?.caption&&<Caption x={60} y={775} text={b.caption}/>}</Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='problem'){const rope=t>=at(s,'rope'),pa=t>=at(s,'parta'),pb=t>=at(s,'partb');const extra:Extra=pb?'angled':pa?'down':'none';return <><Stage><Txt x={35} y={35}>Rough horizontal floor · at rest to begin with</Txt><Floor/><Crate/><Forces R={extra==='down'?48:extra==='angled'?36:40} pull={rope?9:0} pullLabel="X = 9 N" friction={rope?9:0} extra={extra} extraLabel="P = 8 N"/><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='parta'){const subR=t>=at(s,'subR'),cmp=t>=at(s,'compare'),done=t>=s.beats.find(b=>b.id==='answer')!.penEnd;return <><Stage><Txt x={35} y={35}>Part (a) · 8 N pressing down · at rest to begin with</Txt><Floor/><Crate/><Forces R={48} Rlabel={subR?'R = 48 N':'R'} mgLabel={subR?'mg = 40 N':'mg'} pull={9} pullLabel="X = 9 N" friction={9} frictionLabel={done?'f = 9 N':'f'} extra="down" extraLabel="8 N" accentR={t<at(s,'formula')} accentFriction={cmp}/>{cmp&&<Line>9 N {'<'} 12 N · stays at rest{done?' · a = 0':''}</Line>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='resolve'){const h=at(s,'hformula'),v=at(s,'vformula'),hDone=t>=s.beats.find(b=>b.id==='hvalue')!.penEnd,vDone=t>=s.beats.find(b=>b.id==='vvalue')!.penEnd,rep=t>=at(s,'replace');return <><Stage><Txt x={35} y={35}>Part (b) · 8 N at 30° above the horizontal</Txt><Floor/><Crate/><Forces R={40} pull={9} pullLabel="X = 9 N" friction={9} extra={rep?'components':'angled'} extraLabel={rep?'8 N':''} angleLabel={rep} hLabel="H = 4√3 N" vLabel="V = 4 N"/>{!rep&&<Triangle t={t} h={h} v={v} hDone={hDone} vDone={vDone} hLabel="H = 8 cos 30°" vLabel="V = 8 sin 30°"/>}{rep&&<Line>Components replace the 8 N · never count both</Line>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='limit'){const subR=t>=at(s,'subR'),dem=t>=at(s,'demand'),dec=t>=at(s,'decide');const dx=dec?slide(t,at(s,'decide')+.6,4,60):0;return <><Stage><Txt x={35} y={35}>Part (b) · components in place · does it move?</Txt><Floor/><g transform={`translate(${dx} 0)`}><Crate/><Forces R={36} Rlabel={subR?'R = 36 N':'R'} mgLabel={subR?'mg = 40 N':'mg'} pull={9} pullLabel="X = 9 N" friction={9} frictionLabel={dec?'f = 9 N':'f'} extra="components" hLabel="H = 4√3 N" vLabel="V = 4 N" accentR={t<at(s,'formula')} accentFriction={dec}/></g>{dem&&<Line>{dec?'15.9 N > 9 N · slides · friction at its maximum':'Along the floor: 9 + 4√3 ≈ 15.9 N'}</Line>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='newton'){const dx=slide(t,at(s,'law'),3,60);const ans=t>=at(s,'answer');return <><Stage><Txt x={35} y={35}>Part (b) · sliding · resultant force along the floor</Txt><Floor/><g transform={`translate(${dx} 0)`}><Crate/><Forces R={36} Rlabel="R = 36 N" mgLabel="mg = 40 N" pull={9} pullLabel="X = 9 N" friction={9} frictionLabel="f = 9 N" extra="components" hLabel="H = 4√3 N" vLabel="V = 4 N" accentFriction/>{ans&&<><Arrow x={CX-200} y={TOP-50} dx={120} accent/><Txt x={CX-200} y={TOP-68} size={24}>a = √3 m s⁻²</Txt></>}</g><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const w2=s.cues['whatif2']!==undefined&&t>=s.beats.find(b=>b.id==='whatif2')!.penEnd;const dx=w2?slide(t,s.beats.find(b=>b.id==='whatif2')!.penEnd,4,120):0;const w1=t>=at(s,'whatif');
 return <><Stage><Txt x={35} y={35}>What if the 8 N pulled straight up?</Txt><Floor/><g transform={`translate(${dx} 0)`}><Crate/><Forces R={32} Rlabel={w1?'R = 32 N':'R'} mgLabel="mg = 40 N" pull={9} pullLabel="X = 9 N" friction={w2?8:9} frictionLabel={w2?'f max = 8 N':'f'} extra="up" extraLabel="8 N" accentR={!w2} accentFriction={w2}/></g>{w2&&<Line>9 N {'>'} 8 N · it slides</Line>}<Values s={s} t={t}/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsCoefficientOfFrictionFEqualsMaFable:React.FC<MechanicsCoefficientOfFrictionFEqualsMaFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
