import React from 'react';
import transcript from '../public/transcripts/mechanics/f-equals-ma.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-m42/Ink';
const scenes=transcript.scenes as Scene[];
export type MechanicsFEqualsMaProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsFEqualsMaDuration=(fps:number)=>duration(scenes,fps);
const Arrow:React.FC<{x:number;y:number;dx:number;dy?:number;accent?:boolean;dashed?:boolean}>=({x,y,dx,dy=0,accent=false,dashed=false})=><path d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={5} strokeDasharray={dashed?'12 9':undefined} fill="none" markerEnd={accent?'url(#fma-green)':'url(#fma-white)'}/>;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;anchor?:'start'|'middle';fill?:string}>=({x,y,children,size=29,anchor='start',fill=T.text})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
const Car:React.FC<{x?:number;y?:number;scale?:number;wheel?:number}>=({x=420,y=340,scale=1,wheel=0})=><g transform={`translate(${x} ${y}) scale(${scale})`} data-car-x={x}><path d="M-145 28 L-131 -25 L-68 -35 L-36 -83 L65 -83 L112 -35 L150 -15 L157 28 Z" fill="#697b78" stroke={T.text} strokeWidth={3}/><path d="M-54 -39 L-27 -70 H11 V-39 Z M25 -70 H58 L91 -39 H25 Z" fill="#bbc9c6"/><path d="M-137 10 H145" stroke="#a6b4ad" strokeWidth={3}/>{[-94,100].map(z=><g key={z}><circle cx={z} cy={30} r={31} fill="#11171a" stroke={T.text} strokeWidth={3}/><circle cx={z} cy={30} r={10} fill={T.muted}/><path d={`M${z-22*Math.cos(wheel)} ${30-22*Math.sin(wheel)} L${z+22*Math.cos(wheel)} ${30+22*Math.sin(wheel)}`} stroke={T.muted} strokeWidth={3}/></g>)}</g>;
const Road:React.FC<{y?:number;width?:number}>=({y=410,width=840})=><g><path d={`M25 ${y} H${width}`} stroke={T.muted} strokeWidth={4}/>{Array.from({length:12},(_,i)=><path key={i} d={`M${35+i*72} ${y+11} l-18 18`} stroke="#56615e" strokeWidth={3}/>)}</g>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={770} style={{position:'absolute',left:85,top:220}}><defs><marker id="fma-white" markerWidth={11} markerHeight={11} refX={9} refY={5} orient="auto"><path d="M0 1 L9 5 L0 9" fill="none" stroke={T.text} strokeWidth={1.6}/></marker><marker id="fma-green" markerWidth={11} markerHeight={11} refX={9} refY={5} orient="auto"><path d="M0 1 L9 5 L0 9" fill="none" stroke={T.accent} strokeWidth={1.6}/></marker></defs>{children}</svg>;
const Note:React.FC<{text:string}>=({text})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1050,top:450}}><Caption x={30} y={80} text={text}/></svg>;
const InkPaper:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const bs=s.beats.filter(b=>b.ink);const special=s.id==='s06';
 const layout=(id:string,i:number)=>special?({formula:[42,62],forces:[42,162],drive:[42,270],resist:[185,270],mass:[336,270],net:[42,374],divide:[42,478],answer:[42,582]}[id]??[42,680]):[42,70+i*125];
 return <svg data-region="paper" data-visual="paper" width={790} height={730} style={{position:'absolute',left:1050,top:220}}><rect width={790} height={730} rx={12} fill={T.paper}/>{Array.from({length:9},(_,i)=><line key={i} x1={32} x2={756} y1={120+i*70} y2={120+i*70} stroke={T.grid}/>)}{bs.map((b,i)=>{const [x,y]=layout(b.id,i);const size=special&&['drive','resist','mass'].includes(b.id)?34:Math.min(38,705/prepareLine(b.ink!,1).width);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={x} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{b.id==='answer'&&t>=b.penEnd&&<path d={`M${x} ${y+53} Q300 ${y+64} ${x+prepareLine(b.ink!,size).width} ${y+53}`} stroke={T.accent} strokeWidth={4} fill="none"/>}</g>:null;})}</svg>;
};
const Givens:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const accel=s.id==='s07'||s.id==='s06'&&t>=at(s,'answer'); const result=s.id==='s07'&&t>=at(s,'answer');
 return <Stage><Road y={435}/><Car x={440} y={370}/><Arrow x={270} y={337} dx={-55}/><Arrow x={610} y={337} dx={275}/><Figure id="resistance" x={155} y={287} size={32}>R = 600 N</Figure><Figure id="drive" x={625} y={287} size={32}>D = 3000 N</Figure><Figure id="mass" x={331} y={490} size={34}>m = 1200 kg</Figure><Arrow x={210} y={55} dx={125}/><Txt x={370} y={65}>Right is positive</Txt><Figure id="initial" x={60} y={610} size={32}>u = 0 m s⁻¹</Figure><Figure id="time" x={525} y={610} size={32}>t = 4 s</Figure><Arrow x={360} y={165} dx={190} accent dashed={!accel}/><Figure id="acceleration" x={340} y={133} size={34}>{accel?'a = 2 m s⁻²':'a = ?'}</Figure><path d="M95 700 H820 M95 685 V715 M820 685 V715" stroke={T.accent} strokeWidth={3}/><Figure id="distance" x={360} y={755} size={32}>{result?'s = 16 m':'s = ?'}</Figure>{s.id==='s06'&&t>=at(s,'net')&&<Figure id="net" x={220} y={555} size={29}>Resultant = 2400 N right</Figure>}</Stage>;
};
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Road/><Car x={430} y={340}/><Arrow x={625} y={260} dx={190} accent/><Txt x={275} y={550} size={64}>F = ma</Txt></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={790} height={420} style={{position:'absolute',left:1050,top:320}}><rect width={790} height={360} rx={10} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.4 · excerpt · p.33</Txt>{['“apply Newton’s laws of motion to','the linear motion of a particle','of constant mass”'].map((x,i)=><Txt key={x} x={35} y={145+i*58} size={35} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='concept'){
 const bal=t>=at(s,'balanced'),third=t>=at(s,'third');const move=bal?Math.min(160,(t-at(s,'balanced'))*15):0;
 return <><Stage>{third?<><Txt x={100} y={95}>Forces act on different bodies</Txt><Car x={270} y={340} scale={.8}/><path d="M500 410 H840" stroke={T.muted} strokeWidth={12}/><Arrow x={775} y={335} dx={-150}/><Arrow x={120} y={340} dx={150}/><Txt x={130} y={470}>Road pushes car</Txt><Txt x={510} y={535}>Car pushes road</Txt></>:<><Road/><Car x={370+move} y={340}/><Arrow x={195+move} y={320} dx={-125}/><Arrow x={540+move} y={320} dx={bal?125:215}/><Txt x={55+move} y={265}>R</Txt><Txt x={bal?680+move:770+move} y={265}>D</Txt><Txt x={170} y={570}>{bal?'Balanced forces: constant velocity':'Opposing forces subtract'}</Txt>{t>=at(s,'units')&&<><Txt x={110} y={675}>F: N</Txt><Txt x={340} y={675}>m: kg</Txt><Txt x={580} y={675}>a: m s⁻²</Txt></>}</>}</Stage>{third?<Note text="Equal and opposite; different bodies"/>:<InkPaper s={s} t={t}/>}</>;
 }
 if(s.mode==='direction'){
 const vertical=t>=at(s,'weight'), setup=t>=at(s,'vertical'), balance=t>=at(s,'balance')&&t<at(s,'upcase');const speed=1-Math.exp(-t/5);
 return <><Stage>{vertical?<><path d="M450 0 V310" stroke={T.muted} strokeWidth={5}/><rect x={380} y={310} width={140} height={120} fill="#697b78" stroke={T.text} strokeWidth={3}/><Txt x={429} y={380} size={39}>m</Txt><Arrow x={450} y={445} dx={0} dy={135}/><Txt x={495} y={555}>Weight mg</Txt>{setup&&<><Arrow x={450} y={295} dx={0} dy={balance?-135:-190}/><Txt x={490} y={205}>T</Txt>{balance?<Txt x={700} y={335}>a = 0</Txt>:<><Arrow x={710} y={400} dx={0} dy={-120} accent/><Txt x={750} y={335}>a</Txt></>}<Txt x={570} y={100}>Up is positive</Txt><Txt x={210} y={675}>{balance?'Constant velocity: T = mg':t>=at(s,'upcase')?'Upward acceleration: T > mg':'Taut string; upward acceleration'}</Txt></>}</>:<><Road/><Car x={240+speed*270} y={340}/><Arrow x={380} y={160} dx={185}/><Txt x={375} y={125}>Velocity right</Txt>{t>=at(s,'negative')&&<><Arrow x={495} y={560} dx={-165} accent/><Txt x={280} y={640}>Acceleration left: a &lt; 0</Txt></>}</>}</Stage>{vertical?<InkPaper s={s} t={t}/>:<Note text="Moving right and slowing down"/>}</>;
 }
 if(s.mode==='story'){
 const run=clamp((t-at(s,'move'))/Math.max(1,at(s,'goal')-at(s,'move')));const x=200+Math.pow(run,2)*440;
 return <><Stage><Road y={440}/><Car x={x} y={365} scale={.85} wheel={run*15}/>{t>=at(s,'move')&&<><Arrow x={x+145} y={230} dx={130} accent/><Arrow x={x-105} y={290} dx={-70}/></>}{t>=at(s,'speedup')&&<Txt x={185} y={635}>More ground in equal times</Txt>}</Stage><Note text={t>=at(s,'goal')?'Find acceleration, then distance':t>=at(s,'move')?'The car speeds up':'Initially at rest'}/></>;
 }
 if(s.mode==='problem')return <><Givens s={s} t={t}/><svg data-region="problem" width={790} height={610} style={{position:'absolute',left:1050,top:290}}><rect width={790} height={520} rx={10} fill={T.paper}/>{['Constant mass and forces.','Straight, horizontal road; starts at rest.','Find a, then s in the first 4 seconds.'].map((x,i)=><g key={x}><Txt x={35} y={115+i*140} fill={T.ink} size={32}>{x}</Txt>{((i===0&&['mass','drive','resistance'].includes(b?.id??''))||(i===1&&b?.id==='initial')||(i===2&&['time','unknown'].includes(b?.id??'')))&&<path d={`M35 ${132+i*140} H${Math.min(750,35+x.length*15)}`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b!.cue)/.6)}/>}</g>)}</svg></>;
 if(s.mode==='working'||s.mode==='distance')return <><Givens s={s} t={t}/>{s.mode==='distance'&&t>=at(s,'whatif')?<Note text="More resistance → less acceleration"/>:<InkPaper s={s} t={t}/>}</>;
 const answer=t>=at(s,'answer');const x=answer?300+((t-at(s,'answer'))*18)%300:430;
 return <><Stage><Road/><Car x={x} y={340}/><Arrow x={x-160} y={320} dx={-100}/><Arrow x={x+175} y={320} dx={100}/><Txt x={280} y={170}>Resultant = 0 N</Txt>{answer&&<Txt x={265} y={575}>Constant velocity</Txt>}</Stage><Note text={b?.caption?`✓ ${b.caption}`:answer?'Zero acceleration; velocity stays constant':'Must the car stop?'}/></>;
};
export const MechanicsFEqualsMa:React.FC<MechanicsFEqualsMaProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
