import React from 'react';
import transcript from '../public/transcripts/mechanics/coefficient-of-friction-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/coefficient-of-friction-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsCoefficientOfFrictionFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsCoefficientOfFrictionFableDuration=(fps:number)=>duration(scenes,fps);
/* Force scales: horizontal 8 px per newton (X and f are compared by length); vertical 3.6 px per newton (R and mg equal). */
const HX=8,VX=3.6,FLOOR=440,CX=430;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
const Line:React.FC<{children:React.ReactNode}>=({children})=><Txt x={40} y={84} size={26}>{children}</Txt>;
/* Arrows carry data-label so the still audit includes their extents in the collision check. */
const Arrow:React.FC<{x:number;y:number;dx?:number;dy?:number;accent?:boolean;width?:number}>=({x,y,dx=0,dy=0,accent=false,width=4})=><g data-label="true" data-force-arrow="true"><rect x={Math.min(x,x+dx)-6} y={Math.min(y,y+dy)-6} width={Math.abs(dx)+12} height={Math.abs(dy)+12} fill="none" stroke="none"/><path d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={width} fill="none" markerEnd={accent?'url(#cf-green)':'url(#cf-white)'}/></g>;
const Crate:React.FC<{x?:number;floor?:number;w?:number;h?:number;label?:string}>=({x=CX,floor=FLOOR,w=240,h=140,label='crate'})=><g data-crate-x={x}><rect x={x-w/2} y={floor-h} width={w} height={h} rx={6} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M${x-w/2+8} ${floor-h*.5} H${x+w/2-8} M${x-w/2+8} ${floor-h*.72} H${x+w/2-8}`} stroke="#4a3624" strokeWidth={3}/><Txt x={x-w*.2} y={floor-h*.18} size={26}>{label}</Txt></g>;
const Floor:React.FC<{y?:number;icy?:boolean;x0?:number;x1?:number}>=({y=FLOOR,icy=false,x0=40,x1=890})=><g><path d={`M${x0} ${y} H${x1}`} stroke={icy?'#9fd8e8':T.text} strokeWidth={5}/>{!icy&&Array.from({length:17},(_,i)=><path key={i} d={`M${x0+20+i*50} ${y+4} l-14 16`} stroke={T.muted} strokeWidth={2}/>)}</g>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs><marker id="cf-white" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.text} strokeWidth={1.5}/></marker><marker id="cf-green" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.accent} strokeWidth={1.5}/></marker></defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{['answer','t1ans','t2ans','subR','whatif'].includes(b.id)&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* Vertical pair, horizontal pair, and labels. Lengths are the actual newton values at the stage scales. */
const Forces:React.FC<{pull?:number;friction?:number;pullLabel?:string;frictionLabel?:string;vertical?:boolean;accentVertical?:boolean;accentFriction?:boolean;accentPull?:boolean;R?:string;mg?:string;hx?:number}>=({pull=0,friction=0,pullLabel,frictionLabel,vertical=true,accentVertical=false,accentFriction=false,accentPull=true,R='R',mg='mg',hx=HX})=><g>
 {vertical&&<><Arrow x={CX} y={FLOOR-140} dy={-50*VX} accent={accentVertical}/><Txt x={CX+18} y={FLOOR-140-50*VX+14}>{R}</Txt><Arrow x={CX} y={FLOOR} dy={50*VX} accent={accentVertical}/><Txt x={CX+18} y={FLOOR+50*VX+2}>{mg}</Txt></>}
 {pull>0&&<><Arrow x={CX+120} y={FLOOR-70} dx={pull*hx} accent={accentPull}/><Txt x={CX+132} y={FLOOR-70-26} size={28}>{pullLabel??'X'}</Txt></>}
 {friction>0&&<><Arrow x={CX-120} y={FLOOR-70} dx={-friction*hx} accent={accentFriction}/><Txt x={CX-132} y={FLOOR-70-26} size={28} anchor="end">{frictionLabel??'f'}</Txt></>}
</g>;
const Values:React.FC<{s:Scene;t:number;icy?:boolean}>=({s,t,icy=false})=>{
 const R=['trials','slide','closing'].includes(s.mode)||s.mode==='limit'&&t>=at(s,'subR');const fmax=['trials','slide','closing'].includes(s.mode)||s.mode==='limit'&&t>=at(s,'answer');
 const f=s.mode==='trials'?t>=at(s,'t2ans')?'f = 20 N':t>=at(s,'t1ans')?'f = 12 N':'f = ?':s.mode==='slide'?t>=at(s,'t3')+.1?'f = 20 N':'f = ?':'f = ?';
 const a=s.mode==='trials'?t>=at(s,'t1ans')?'a = 0':'a = ?':s.mode==='slide'&&t>=at(s,'answer')?'a = 1 m s⁻²':'a = ?';
 return <g><path d="M35 650 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={695} size={27}>m = 5 kg</Figure>{icy?<Figure id="muIce" x={255} y={695} size={27}>μ = 0.1</Figure>:<Figure id="mu" x={255} y={695} size={27}>μ = 0.4</Figure>}<Figure id="gravity" x={430} y={695} size={27}>g = 10 m s⁻²</Figure><Figure id="pulls" x={45} y={740} size={27}>X = 12 N, 20 N, 25 N</Figure><Figure id="R" x={430} y={740} size={27}>{R?'R = 50 N':'R = ?'}</Figure>{icy?<Figure id="fmaxIce" x={640} y={740} size={27}>{t>=at(s,'whatif')+.1?'f max = 5 N':'f max = ?'}</Figure>:<Figure id="fmax" x={640} y={740} size={27}>{fmax?'f max = 20 N':'f max = ?'}</Figure>}{['trials','slide'].includes(s.mode)&&<><Figure id="f" x={620} y={695} size={27}>{f}</Figure><Figure id="a" x={770} y={695} size={27}>{a}</Figure></>}</g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Rough horizontal floor; at rest before each trial.','Pull X: 12 N, then 20 N, then 25 N.','Find friction f and acceleration a each time.'];const active=b?.id==='crate'||b?.id==='mu'?0:b?.id==='pulls'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={30}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Slide displacement (px) with constant acceleration from a cue, on the hold-frozen clock t. */
const slide=(t:number,from:number,k:number,max:number)=>Math.min(max,Math.max(0,.5*k*(t-from)*(t-from)));
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Floor/><Crate/><Forces pull={16} friction={16} accentPull={false}/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.1 · excerpt · p.31</Txt>{['“limiting friction and','limiting equilibrium”'].map((x,i)=><Txt key={x} x={35} y={165+i*70} size={38} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){const gentle=at(s,'gentle'),harder=at(s,'harder'),limit=at(s,'limit'),sl=at(s,'slide');const grow=(from:number,to:number,a:number,c:number)=>from+(to-from)*clamp((t-a)/(c-a));
  const pull=t<gentle?0:t<harder?grow(0,8,gentle,gentle+1.5):t<limit?grow(8,15,harder,harder+1.5):t<sl?grow(15,20,limit,limit+1.5):25;const friction=t<gentle?0:t<sl?pull:20;const dx=t>=sl?slide(t,sl,10,60):0;
  const caption=t>=sl?'Past the limit: it slides':t>=limit?'On the point of moving':t>=harder?'Harder pull, friction matches':t>=gentle?'Small pull, friction matches':'No pull, no friction';
  return <><Stage><g transform={`translate(-297 -188) scale(1.7) translate(${dx/1.6} 0)`}><Crate/>{pull>0&&<Forces pull={pull} friction={friction} pullLabel="pull" frictionLabel="friction" vertical={false} accentFriction={t>=sl} hx={5}/>}</g><Floor y={FLOOR*1.7-188} x0={20} x1={910}/>{t>=sl&&<g><Arrow x={CX*1.7-297+dx-50} y={275} dx={100} accent/><Txt x={CX*1.7-297+dx-105} y={250} size={26}>accelerates</Txt></g>}<Caption x={60} y={632} text={caption}/></Stage></>;}
 if(s.mode==='direction'){const side=t>=at(s,'sideways'),smooth=t>=at(s,'smooth');const dx=smooth?slide(t,at(s,'smooth'),10,200):0;return <><Stage><Txt x={35} y={35}>{smooth?'Smooth floor: no friction':'Rough floor'}</Txt><Floor icy={smooth}/><g transform={`translate(${dx} 0)`}><Crate/><Forces pull={side?15:0} friction={side&&!smooth?15:0} accentFriction={!smooth}/></g>{side&&<Line>{smooth?'Nothing opposes the pull':'Friction opposes the slide'}</Line>}</Stage>{b?.caption?<Note text={b.caption}/>:<Note text={side?'Parallel to the surface, opposite to sliding':'Only weight and normal reaction'}/>}</>;}
 if(s.mode==='law')return <><Stage><Floor/><Crate/><Forces pull={15} friction={15} accentFriction/>{b?.caption&&<Caption x={60} y={770} text={b.caption}/>}{t>=at(s,'max')&&<Line>f can grow only up to μR</Line>}</Stage><Paper s={s} t={t}/></>;
 if(s.mode==='problem'){const pull=t>=at(s,'pulls')?12:0;return <><Stage><Txt x={35} y={35}>Rough horizontal floor · at rest before each trial</Txt><Floor/><Crate/><Forces pull={pull} friction={pull} pullLabel="X" R="R" mg="mg"/><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='limit'){const vert=t>=at(s,'vertical')&&t<at(s,'formula');return <><Stage><Txt x={35} y={35}>Vertical forces balance · R = mg</Txt><Floor/><Crate/><Forces accentVertical={vert} R={t>=at(s,'subR')?'R = 50 N':'R'} mg={t>=at(s,'subR')?'mg = 50 N':'mg'}/>{t>=at(s,'answer')&&<Line>Most friction this floor can give: 20 N</Line>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='trials'){const two=t>=at(s,'t2');const pull=two?20:12;const done=two?t>=s.beats.find(b=>b.id==='t2ans')!.penEnd:t>=s.beats.find(b=>b.id==='t1ans')!.penEnd;return <><Stage><Txt x={35} y={35}>{two?'Trial 2 · X = 20 N · limiting equilibrium':'Trial 1 · X = 12 N'}</Txt><Floor/><Crate/><Forces pull={pull} friction={pull} pullLabel={two?'X = 20 N':'X = 12 N'} frictionLabel={done?two?'f = 20 N':'f = 12 N':'f'} accentFriction/><Line>{(two?'20 N = f max · still at rest':'12 N < 20 N · stays at rest')+(done?' · a = 0':'')}</Line><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='slide'){const dx=slide(t,at(s,'t3')+1,6,170);const ans=t>=at(s,'answer');return <><Stage><Txt x={35} y={35}>Trial 3 · X = 25 N · slides</Txt><Floor/><g transform={`translate(${dx} 0)`}><Crate/><Forces pull={25} friction={20} pullLabel="X = 25 N" frictionLabel="f = 20 N" accentFriction/>{ans&&<><Arrow x={CX+230} y={FLOOR-190} dx={80} accent/><Txt x={CX+170} y={FLOOR-205} size={24}>a = 1 m s⁻²</Txt></>}</g><Line>25 N {'>'} 20 N · friction at its maximum</Line><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const dx=t>=at(s,'whatif')+3?slide(t,at(s,'whatif')+3,6,120):0;
 return <><Stage><Txt x={35} y={35}>Icy floor · μ = 0.1</Txt><Floor icy/><g transform={`translate(${dx} 0)`}><Crate/><Forces pull={12} friction={5} pullLabel="X = 12 N" frictionLabel="f max = 5 N" accentFriction/></g><Line>12 N {'>'} 5 N · it slides</Line><Values s={s} t={t} icy/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsCoefficientOfFrictionFable:React.FC<MechanicsCoefficientOfFrictionFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
