import React from 'react';
import transcript from '../public/transcripts/mechanics/coefficient-of-friction-and-inclined-planes.json';
import {Lesson,Scene,Figure,Caption,T,at,currentBeat,duration,Paper} from './mechanics-m42/Presentation';
import {InclineFrictionShapeAudit} from './mechanics-incline-friction/ShapeAudit';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsCoefficientOfFrictionAndInclinedPlanesProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsCoefficientOfFrictionAndInclinedPlanesDuration=(fps:number)=>duration(scenes,fps);
const c=Math.sqrt(3)/2,scale=6,Wn=20*Math.sqrt(3),H=4*Math.sqrt(3),R=Wn-4,F=5*Math.sqrt(3)-1;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string}>=({x,y,children,size=27,fill=T.text})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size}>{children}</text>;
const Arrow:React.FC<{name:string;x:number;y:number;dx:number;dy:number;accent?:boolean;muted?:boolean}>=({name,x,y,dx,dy,accent=false,muted=false})=><path data-force-arrow={name} d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={3.5} opacity={muted?.2:1} fill="none" markerEnd={accent?'url(#incline-green)':'url(#incline-white)'}/>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs>{[['white',T.text],['green',T.accent]].map(([id,color])=><marker key={id} id={'incline-'+id} markerWidth={7} markerHeight={7} refX={6} refY={3.5} orient="auto"><path d="M1 1 L6 3.5 L1 6" fill="none" stroke={color} strokeWidth={1.3}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string}>=({text})=><svg data-region="caption" width={800} height={160} style={{position:'absolute',left:1040,top:465}}><Caption x={25} y={65} text={text}/></svg>;
const Box:React.FC<{x:number;y:number}>=({x,y})=><g data-block-x={x} data-block-y={y} transform={`translate(${x} ${y}) rotate(-30)`}><rect x={-53} y={-30} width={106} height={60} fill="#31453f" stroke={T.text} strokeWidth={3}/><path d="M-53 -30 L0 -11 L53 -30 M0 -11 V30" stroke={T.muted} strokeWidth={2}/></g>;
const lineY=(x:number)=>(300+30/c+430/Math.sqrt(3))-x/Math.sqrt(3);
const Surface:React.FC=()=> <><path d={`M65 ${lineY(65)} L870 ${lineY(870)} M65 ${lineY(65)} H290`} stroke={T.muted} strokeWidth={3} fill="none"/>{Array.from({length:15},(_,i)=>{const x=100+i*50;return <path key={i} d={`M${x} ${lineY(x)+5} l-7 15`} stroke={T.muted} strokeWidth={2}/>;})}<path d={`M165 ${lineY(65)} A100 100 0 0 0 151.6025 ${lineY(65)-50}`} stroke={T.accent} strokeWidth={2.5} fill="none"/><Txt x={187} y={lineY(65)-22} size={25}>θ</Txt></>;
const done=(s:Scene,t:number,scene:number,cue:string)=>Number(s.id.slice(1))>scene||(Number(s.id.slice(1))===scene&&t>=at(s,cue));
const Givens:React.FC<{s:Scene;t:number}>=({s,t})=><g><path d="M30 592 H900" stroke={T.muted}/><Figure id="mass" x={35} y={636}>m = 4 kg</Figure><Figure id="pull" x={340} y={636}>P = 8 N</Figure><Figure id="mu" x={650} y={636}>μ = 0.25</Figure><Figure id="slope" x={35} y={686} size={25}>θ = 30° to horizontal</Figure><Figure id="angle" x={340} y={686} size={25}>α = 30° above slope</Figure><Figure id="gravity" x={650} y={686} size={25}>g = 10 m s⁻²</Figure><Txt x={35} y={734} size={24}>Released from rest · constant pull · contact maintained</Txt><Figure id="accel" x={35} y={783} size={27}>{done(s,t,7,'resultA')?'a ≈ 1.35 m s⁻² downhill':'a = ?'}</Figure><Figure id="friction" x={420} y={783} size={27}>{done(s,t,6,'resultF')?'f = (5√3 - 1) N uphill':'f = ?'}</Figure></g>;
const Ramp:React.FC<{s:Scene;t:number;original?:boolean}>=({s,t,original=false})=>{
 const wc=done(s,t,4,'normal'),pc=done(s,t,4,'pullalong'),wn=done(s,t,4,'resultN'),wp=done(s,t,4,'resultDWeight'),h=done(s,t,4,'resultH'),v=done(s,t,4,'resultV'),w=done(s,t,4,'resultW'),r=done(s,t,5,'resultR'),fr=done(s,t,6,'frictionArrow');
 return <><Txt x={35} y={32} size={24}>Force snapshot · {fr?'sliding downhill':'friction direction to decide'}</Txt><Surface/><Box x={430} y={300}/>
 <Arrow name="R" x={385} y={292} dx={-.5*R*scale} dy={-c*R*scale}/><Figure id="reaction" x={60} y={105} size={27}>{r?'R = (20√3 - 4) N':'R = ?'}</Figure>
 {(!wc||original)&&<><Arrow name="weight" x={430} y={300} dx={0} dy={240}/><Figure id="weight" x={450} y={555}>{w?'W = 40 N':'W = mg'}</Figure></>}
 {wc&&!original&&<><Figure id="weight" x={670} y={105} size={25}>W = 40 N</Figure><Arrow name="Wnormal" x={430} y={300} dx={.5*Wn*scale} dy={c*Wn*scale} accent/><Figure id="wn" x={570} y={496} size={26}>{wn?'W⊥ = 20√3 N':'W⊥ = ?'}</Figure><path d="M430 360 A60 60 0 0 0 460 351.962 M430 300 V370" stroke={T.muted} strokeWidth={2} fill="none"/><Txt x={453} y={397} size={23}>θ</Txt>{s.mode!=='components'||t>=at(s,'parallel')?<><Arrow name="Wparallel" x={430} y={300} dx={-60*Math.sqrt(3)} dy={60} accent/><Figure id="wp" x={65} y={425} size={26}>{wp?'W∥ = 20 N':'W∥ = ?'}</Figure></>:null}</>}
 {(!pc||original)&&<><Arrow name="P" x={430+53*c} y={273.5} dx={24} dy={-24*Math.sqrt(3)} accent/><Txt x={535} y={182}>P</Txt><path d={`M${430+53*c} 273.5 l90 -51.9615242271 M${430+53*c+48*c} 249.5 A48 48 0 0 0 ${430+53*c+24} ${273.5-48*c}`} fill="none" stroke={T.muted} strokeWidth={2}/><Txt x={545} y={215} size={25}>α</Txt></>}
 {pc&&!original&&<><Arrow name="H" x={430+53*c} y={273.5} dx={c*H*scale} dy={-.5*H*scale} accent/><Figure id="horizontal" x={600} y={294} size={25}>{h?'H = 4√3 N':'H = ?'}</Figure>{s.mode!=='components'||t>=at(s,'pullaway')?<><Arrow name="V" x={430+53*c} y={273.5} dx={-12} dy={-24*c} accent/><Figure id="vertical" x={525} y={174} size={25}>{v?'V = 4 N':'V = ?'}</Figure></>:null}</>}
 {fr&&<><Arrow name="f" x={398} y={350} dx={c*F*scale} dy={-.5*F*scale}/><Txt x={490} y={365}>f uphill</Txt></>}
 {s.mode==='reaction'&&<Figure id="zero" x={560} y={70} size={24}>a⊥ = 0</Figure>}
 {s.mode==='friction'&&t>=at(s,'capsub')&&<Figure id="limit" x={45} y={570} size={25}>{t>=at(s,'decimalLimit')?'f max ≈ 7.66 N':t>=at(s,'resultLimit')?'f max = (5√3 - 1) N':'f max = ?'}</Figure>}
 {s.mode==='friction'&&t>=at(s,'demand')&&<Figure id="demand" x={550} y={570} size={25}>{t>=at(s,'decimalDemand')?'D ≈ 13.07 N':t>=at(s,'resultDemand')?'D = (20 - 4√3) N':'D = ?'}</Figure>}
 {s.mode==='acceleration'&&t>=at(s,'resultResultant')&&<Figure id="resultant" x={300} y={550} size={25}>Resultant = (21 - 9√3) N</Figure>}<Givens s={s} t={t}/></>;
};
const active=(s:Scene,t:number)=>t-s.holds.reduce((n,h)=>n+Math.max(0,Math.min(t,h.end)-h.start),0);
const Moving:React.FC<{s:Scene;t:number;start:number}>=({s,t,start})=>{const total=active(s,s.duration)-active(s,start),tau=Math.max(0,active(s,t)-active(s,start)),dist=430*(tau/total)**2,x=700-dist*c,y=lineY(x)-30/c;return <><Surface/><Box x={x} y={y}/><path d={`M${x+43.3} ${y-25} l60 -103.92304845413264`} stroke={T.text} strokeWidth={3}/>{t<start&&<><path d={`M${x-53*c+15} ${y+26.5+30*c} l-30 ${-60*c}`} stroke={T.accent} strokeWidth={8}/><Txt x={x-190} y={y+70} size={25}>Held</Txt></>}{s.mode==='acceleration'&&<><Txt x={35} y={35} size={24}>Replay from rest · equal time marks</Txt>{[.25,.5,.75,1].map((q,i)=>{const px=700-430*q*q*c,py=lineY(px);return tau/total>=q?<g key={q}><path d={`M${px} ${py+9} l8 14`} stroke={T.accent} strokeWidth={3}/><Txt x={px-10} y={py+52} size={22}>{i+1}</Txt></g>:null;})}<Arrow name="moving-friction" x={x-20} y={y+25} dx={F*6*c} dy={-F*3} accent/><Txt x={x-170} y={y-35} size={25}>f uphill</Txt><Givens s={s} t={t}/></>}{s.mode==='story'&&<Txt x={110} y={695}>Rough slope · contact maintained</Txt>}</>;};
const Contrast:React.FC<{s:Scene;t:number}>=({s,t})=><><Txt x={35} y={35} size={24}>Changed condition · pull parallel to slope</Txt><Surface/><Box x={430} y={300}/><Arrow name="contrastR" x={385} y={292} dx={-.5*Wn*scale} dy={-c*Wn*scale}/><Txt x={140} y={105}>R</Txt><Arrow name="contrastWn" x={430} y={300} dx={.5*Wn*scale} dy={c*Wn*scale}/><Txt x={570} y={500}>mg cos θ</Txt><Arrow name="contrastWp" x={430} y={300} dx={-60*Math.sqrt(3)} dy={60}/><Txt x={65} y={425}>mg sin θ</Txt><Arrow name="contrastP" x={430+53*c} y={273.5} dx={8*6*c} dy={-24} accent/><Txt x={570} y={155}>P parallel</Txt><Txt x={90} y={695}>Contact maintained · no outward pull component</Txt><Txt x={90} y={755}>Recheck friction and motion</Txt></>;
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Surface/><Box x={430} y={300}/><Arrow name="motifW" x={430} y={300} dx={0} dy={230}/><Txt x={465} y={520}>Weight</Txt></Stage>{b?.caption?<Note text={b.caption}/>:<svg data-region="syllabus" width={800} height={330} style={{position:'absolute',left:1040,top:330}}><rect width={800} height={330} rx={12} fill={T.paper}/><Txt x={32} y={65} size={27} fill={T.ink}>Syllabus 4.1 · excerpt · p.31</Txt><Txt x={32} y={160} size={35} fill={T.ink}>“limiting friction and</Txt><Txt x={32} y={222} size={35} fill={T.ink}>limiting equilibrium”</Txt></svg>}</>;
 if(s.mode==='story')return <><Stage><Moving s={s} t={t} start={at(s,'releaseMotion')}/></Stage><Note text={t<at(s,'releaseMotion')?'A rope pulls uphill and outwards':'Released: sliding downhill, gaining speed'}/></>;
 if(s.mode==='problem')return <><Stage><Ramp s={s} t={t} original/></Stage><svg data-region="problem" width={800} height={700} style={{position:'absolute',left:1040,top:280}}><rect width={800} height={650} rx={12} fill={T.paper}/>{['Release from rest; constant oblique pull P.','Only weight, pull, reaction and friction act.','Find R, motion, friction f and acceleration a.'].map((l,i)=><g key={l}><Txt x={28} y={90+i*185} size={29} fill={T.ink}>{l}</Txt>{((i===0&&['mass','slope','pull','mu'].includes(b?.id??''))||(i===1&&b?.id==='conditions')||(i===2&&b?.id==='unknown'))&&<path d={`M28 ${110+i*185} H760`} stroke={T.accent} strokeWidth={3}/>}</g>)}<Txt x={28} y={597} size={24} fill={T.ink}>Sliding model: friction equals its limiting value</Txt></svg></>;
 if(s.mode==='acceleration'&&t>=at(s,'motion'))return <><Stage><Moving s={s} t={t} start={at(s,'motion')}/></Stage><Note text="Equal times, increasing downhill distances"/></>;
 if(['components','reaction','friction','acceleration'].includes(s.mode))return <><Stage><Ramp s={s} t={t}/></Stage><Paper s={s} t={t} problem={[s.mode==='components'?'Two angles, measured from different lines':s.mode==='reaction'?'Balance perpendicular to the plane':s.mode==='friction'?'Compare demand with the friction limit':'Take downhill as positive']}/></>;
 return <><Stage><Contrast s={s} t={t}/></Stage>{b?.caption?<Note text={'✓ '+b.caption}/>:t<at(s,'normal')?<Note text="Does the pull still reduce reaction?"/>:<Paper s={s} t={t} problem={[]}/>}</>;
};
export const MechanicsCoefficientOfFrictionAndInclinedPlanes:React.FC<MechanicsCoefficientOfFrictionAndInclinedPlanesProps>=props=><><Lesson scenes={scenes} content={Content} {...props}/>{props.audit&&<InclineFrictionShapeAudit/>}</>;
