import React from 'react';
import transcript from '../public/transcripts/mechanics/connected-bodies-pulleys-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/connected-bodies-pulleys-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsConnectedBodiesPulleysFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsConnectedBodiesPulleysFableDuration=(fps:number)=>duration(scenes,fps);

// Diagram geometry (Stage-local, 930×810). Floor at FLOOR; heights to scale at SC px per metre in the to-scale scenes.
const FLOOR=640,SC=230,PX=420,QX=510,PULLEY={x:465,y:112,r:40},BOX={w:64,h:56};
// Story-scene geometry (qualitative, scaled 1.35× inside the stage).
const ST={scale:1.35,tx:40,pulley:{x:330,y:60,r:34},px:296,qx:364,floor:560,qStart:520,boxH:56};
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'middle'|'end'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
const Arrow:React.FC<{x:number;y:number;dx?:number;dy?:number;accent?:boolean;dashed?:boolean}>=({x,y,dx=0,dy=0,accent=false,dashed=false})=><path data-force-arrow="true" d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={4} fill="none" strokeDasharray={dashed?'10 8':undefined} markerEnd={accent?'url(#pf-green)':'url(#pf-white)'}/>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs><marker id="pf-white" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.text} strokeWidth={1.5}/></marker><marker id="pf-green" markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={T.accent} strokeWidth={1.5}/></marker></defs>{children}</svg>;
const Note:React.FC<{text:string}>=({text})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}><Caption x={24} y={85} text={text}/></svg>;
// Pulley, bracket and floor. Strands are drawn by the caller because their lengths follow the boxes.
const Frame:React.FC<{floor?:boolean}>=({floor=true})=><g><path d={`M${PULLEY.x-40} 62 H${PULLEY.x+40} M${PULLEY.x} 62 V${PULLEY.y}`} stroke={T.muted} strokeWidth={6}/><circle cx={PULLEY.x} cy={PULLEY.y} r={PULLEY.r} fill="#293431" stroke={T.text} strokeWidth={4}/><circle cx={PULLEY.x} cy={PULLEY.y} r={6} fill={T.text}/>{floor&&<path d={`M120 ${FLOOR} H810`} stroke={T.text} strokeWidth={6}/>}</g>;
// A particle box whose BOTTOM edge sits at y. Label sits inside the box.
const Box:React.FC<{x:number;bottom:number;label:string;muted?:boolean;accent?:boolean}>=({x,bottom,label,muted=false,accent=false})=><g opacity={muted?.25:1}><rect x={x-BOX.w/2} y={bottom-BOX.h} width={BOX.w} height={BOX.h} rx={6} fill={accent?T.accent:'#3a4642'} stroke={T.text} strokeWidth={3}/><Txt x={x} y={bottom-18} size={30} anchor="middle">{label}</Txt></g>;
// Taut strand from the pulley rim down to a box top; slack strand droops to the box.
const Strand:React.FC<{x:number;top:number;slack?:boolean}>=({x,top,slack=false})=>{const q=x>PULLEY.x,g=q?-Math.min(14,Math.max(0,(top-PULLEY.y)/8)):-Math.min(22,Math.max(0,(top-PULLEY.y)/12));return slack?<path d={`M${x} ${PULLEY.y} C ${x+g} ${PULLEY.y+(top-PULLEY.y)*.4} ${x+g*1.3} ${top-(top-PULLEY.y)*.25} ${x} ${top}`} fill="none" stroke={T.muted} strokeWidth={3}/>:<path d={`M${x} ${PULLEY.y} V${top}`} stroke={T.text} strokeWidth={3}/>;};
const Rim:React.FC=()=><path d={`M${PX} ${PULLEY.y} A${PULLEY.r} ${PULLEY.r} 0 0 1 ${QX} ${PULLEY.y}`} fill="none" stroke={T.text} strokeWidth={3}/>;
const hy=(h:number)=>FLOOR-h*SC; // bottom edge for a height h in metres
// Dimension line with a label, from the floor up to a bottom edge.
const Dim:React.FC<{x:number;bottom:number;id:string;label:string;side:'left'|'right'}>=({x,bottom,id,label,side})=><g><rect data-label="true" data-dim={id} x={x-11} y={bottom-1} width={22} height={FLOOR-bottom+2} fill="none" stroke="none"/><path d={`M${x} ${FLOOR} V${bottom}`} stroke={T.muted} strokeWidth={2} strokeDasharray="6 6"/><path d={`M${x-10} ${bottom} H${x+10} M${x-10} ${FLOOR} H${x+10}`} stroke={T.muted} strokeWidth={2}/><Figure id={id} x={side==='left'?x-22-label.length*15:x+22} y={(FLOOR+bottom)/2+10} size={27}>{label}</Figure></g>;
// Given / result row under the floor. Results replace question marks once found.
const Values:React.FC<{s:Scene;t:number;acc?:boolean;tension?:boolean;speed?:boolean;hmax?:boolean}>=({acc=false,tension=false,speed=false,hmax=false})=><g><path d="M35 672 H895" stroke={T.muted} strokeWidth={1}/><Figure id="massP" x={45} y={716} size={27}>P = 6 kg</Figure><Figure id="massQ" x={300} y={716} size={27}>Q = 4 kg</Figure><Figure id="gravity" x={560} y={716} size={27}>g = 10 m s⁻²</Figure><Figure id="acc" x={45} y={770} size={27}>{acc?'a = 2 m s⁻²':'a = ?'}</Figure><Figure id="tension" x={265} y={770} size={27}>{tension?'T = 48 N':'T = ?'}</Figure><Figure id="speed" x={470} y={770} size={27}>{speed?'v = 2 m s⁻¹':'v = ?'}</Figure><Figure id="hmax" x={700} y={770} size={27}>{hmax?'h max = 1.8 m':'h max = ?'}</Figure></g>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);const gap=bs.length>6?90:bs.length>5?105:125;return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(bs.length>6?33:36,718/prepareLine(b.ink!,1).width),y=50+i*gap;return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{['answer','tension','rise'].includes(b.id)&&t>=b.penEnd&&<path d={`M38 ${y+size*1.35} Q360 ${y+size*1.35+14} ${38+prepareLine(b.ink!,size).width} ${y+size*1.35}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
// Motion clock that ignores inserted holds, so nothing jumps across a pause.
const active=(s:Scene,v:number)=>v-s.holds.reduce((n,h)=>n+Math.max(0,Math.min(v,h.end)-h.start),0);
// Forces on the to-scale pair. Lengths: mg_P 60 N → 120 px, T 48 N → 96 px, mg_Q 40 N → 80 px.
const Forces:React.FC<{pBottom:number;qBottom:number;showP:boolean;showQ:boolean;tension:boolean;weightP:boolean;weightQ:boolean;accel:boolean}>=({pBottom,qBottom,showP,showQ,tension,weightP,weightQ,accel})=>{const pc=pBottom-BOX.h/2,qc=qBottom-BOX.h/2;return <g>{showP&&<g><Arrow x={PX-60} y={pc} dy={-96} accent/><Txt x={PX-80} y={pc-115} size={26} anchor="end">{tension?'T = 48 N':'T'}</Txt><Arrow x={PX-60} y={pc} dy={120}/><Figure id="weightP" x={PX-225} y={pc+150} size={26}>{weightP?'mg = 60 N':'mg'}</Figure>{accel&&<g><Arrow x={PX-200} y={pc-40} dy={70} accent/><Txt x={PX-245} y={pc+5} size={26} fill={T.accent}>a</Txt></g>}</g>}{showQ&&<g><Arrow x={QX+60} y={qc} dy={-96} accent/><Txt x={QX+80} y={qc-115} size={26}>{tension?'T = 48 N':'T'}</Txt><Arrow x={QX+60} y={qc} dy={80}/><Figure id="weightQ" x={QX+80} y={qc+115} size={26}>{weightQ?'mg = 40 N':'mg'}</Figure>{accel&&<g><Arrow x={QX+200} y={qc+40} dy={-70} accent/><Txt x={QX+220} y={qc+5} size={26} fill={T.accent}>a</Txt></g>}</g>}</g>;};
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Frame/><Rim/><Strand x={PX} top={hy(1)-BOX.h}/><Strand x={QX} top={hy(.6)-BOX.h}/><Box x={PX} bottom={hy(1)} label="P"/><Box x={QX} bottom={hy(.6)} label="Q" accent/><Txt x={200} y={720}>Two particles, one string, one pulley</Txt></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.4 · excerpt · p.33</Txt>{['“solve simple problems which','may be modelled as the motion','of connected particles.”'].map((x,i)=><Txt key={x} x={35} y={155+i*65} size={36} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){
  // Qualitative motion, not to scale, drawn in local coordinates and scaled up. Stage 1: P falls `drop` px from rest while Q rises the same (quadratic from rest). Stage 2: Q keeps rising at its stage-1 speed, decelerating to rest exactly at the 'falls' cue, then falls back to where the string went slack.
  const release=at(s,'release'),lands=at(s,'lands'),falls=at(s,'falls'),endFree=s.beats.find(x=>x.id==='falls')!.speechEnd;
  const d1=Math.max(.5,active(s,lands)-active(s,release)),tp=Math.max(.5,active(s,falls)-active(s,lands)),tau=active(s,t);
  const drop=Math.min(160,Math.floor(355/(1+tp/d1))),v0=2*drop/d1,rise=v0*tp/2,tdown=Math.max(.5,active(s,endFree)-active(s,falls));
  const p1=clamp((tau-active(s,release))/d1);const s1=drop*p1*p1;
  const pBottom=ST.floor-drop+s1;let qBottom=ST.qStart-s1;
  const tau2=tau-active(s,lands);
  if(tau2>0){const up=Math.min(tau2,tp);qBottom=ST.qStart-drop-(v0*up-.5*(v0/tp)*up*up);const down=clamp((tau2-tp)/tdown);qBottom+=rise*down*down;}
  const slack=t>=lands,peak=t>=falls&&t<falls+.6;const P=ST.pulley,bh=ST.boxH;
  const strand=(x:number,top:number)=>{const q=x>P.x,g=q?-Math.min(12,Math.max(0,(top-P.y)/8)):-Math.min(20,Math.max(0,(top-P.y)/12));return slack?<path d={`M${x} ${P.y} C ${x+g} ${P.y+(top-P.y)*.4} ${x+g*1.3} ${top-(top-P.y)*.25} ${x} ${top}`} fill="none" stroke={T.muted} strokeWidth={2.5}/>:<path d={`M${x} ${P.y} V${top}`} stroke={T.text} strokeWidth={2.5}/>;};
  return <><Stage><g transform={`translate(${ST.tx} 0) scale(${ST.scale})`}><path d={`M${P.x-34} 18 H${P.x+34} M${P.x} 18 V${P.y}`} stroke={T.muted} strokeWidth={5}/><circle cx={P.x} cy={P.y} r={P.r} fill="#293431" stroke={T.text} strokeWidth={3}/><circle cx={P.x} cy={P.y} r={5} fill={T.text}/><path d={`M${ST.px} ${P.y} A${P.r} ${P.r} 0 0 1 ${ST.qx} ${P.y}`} fill="none" stroke={T.text} strokeWidth={2.5}/><path d={`M120 ${ST.floor} H540`} stroke={T.text} strokeWidth={5}/>{strand(ST.px,pBottom-bh)}{strand(ST.qx,qBottom-bh)}<Box x={ST.px} bottom={pBottom} label="P"/><Box x={ST.qx} bottom={qBottom} label="Q" accent/>{t>=release&&t<lands&&<g><Arrow x={ST.px-60} y={pBottom-70} dy={50}/><Arrow x={ST.qx+60} y={qBottom-8} dy={-50}/></g>}{slack&&t<falls&&<Arrow x={ST.qx+60} y={qBottom-8} dy={-40}/>}{t>=falls+.6&&<Arrow x={ST.qx+60} y={qBottom-60} dy={40}/>}{peak&&<Txt x={ST.qx+70} y={qBottom-70} size={19}>stops for an instant</Txt>}<Txt x={120} y={ST.floor+34} size={21}>{t>=falls?'Stage 2: Q on its own':slack?'String slack':t>=release?'Stage 1: connected':'At rest'}</Txt></g></Stage><Note text={t>=falls?'Then it falls back':slack?'P stops; the string goes slack':t>=release?'P falls, Q rises the same amount':'Two particles at rest'}/></>;}
 if(s.mode==='model'){
  const rough=t>=at(s,'contrast');
  return <><Stage><Frame/><Rim/><Strand x={PX} top={hy(1)-BOX.h}/><Strand x={QX} top={hy(.6)-BOX.h}/><Box x={PX} bottom={hy(1)} label="P"/><Box x={QX} bottom={hy(.6)} label="Q" accent/><Arrow x={PX-140} y={hy(1)-100} dy={90} accent/><Txt x={PX-190} y={hy(1)-40} size={26} fill={T.accent}>a</Txt><Arrow x={QX+140} y={hy(.6)-10} dy={-90} accent/><Txt x={QX+160} y={hy(.6)-50} size={26} fill={T.accent}>a</Txt>{t>=at(s,'tension')&&<g><Arrow x={PX-60} y={hy(1)-BOX.h/2} dy={-90}/><Txt x={PX-120} y={hy(1)-BOX.h-30} size={26}>{rough?'T₁':'T'}</Txt><Arrow x={QX+60} y={hy(.6)-BOX.h/2} dy={-90}/><Txt x={QX+80} y={hy(.6)-BOX.h-30} size={26}>{rough?'T₂':'T'}</Txt></g>}{rough&&<Txt x={PULLEY.x} y={PULLEY.y-55} size={24} anchor="middle">rough?</Txt>}<Txt x={130} y={720}>{rough?'Smooth pulley: T₁ = T₂':'Inextensible: same distance each moment'}</Txt></Stage><Note text={b?.caption??''}/></>;}
 if(s.mode==='problem'){const line=b?.id==='conditions'?0:b?.id==='assume'?1:b?.id==='unknown'?2:-1;
  return <><Stage><Frame/><Rim/><Strand x={PX} top={hy(1)-BOX.h}/><Strand x={QX} top={hy(.6)-BOX.h}/><Box x={PX} bottom={hy(1)} label="P"/><Box x={QX} bottom={hy(.6)} label="Q" accent/><Dim x={190} bottom={hy(1)} id="hP" label="1 m" side="left"/><Dim x={700} bottom={hy(.6)} id="hQ" label="0.6 m" side="right"/>{t>=at(s,'think')&&<g><Arrow x={PX-90} y={hy(1)-100} dy={70} dashed/><Arrow x={QX+90} y={hy(.6)-10} dy={-70} dashed/></g>}<Txt x={35} y={35}>Released from rest · light string · smooth pulley</Txt><Values s={s} t={t}/></Stage><svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{['Light inextensible string; small smooth pulley.','P stays on the floor; Q never reaches the pulley.','Find a, T, speed of P at floor, max height of Q.'].map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={29}>{x}</Txt>{line===i&&<path d={`M30 ${138+i*150} H760`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b!.cue)/.5)}/>}</g>)}</svg></>;}
 if(s.mode==='equations'){const p=t>=at(s,'isolateP')&&t<at(s,'isolateQ'),q=t>=at(s,'isolateQ')&&t<at(s,'add'),both=t>=at(s,'add');
  return <><Stage><Txt x={35} y={35}>{both?'Both particles · a = 2 m s⁻² · T = 48 N':q?'Selected particle: Q · up is positive':'Selected particle: P · down is positive'}</Txt><Frame/><Rim/><Strand x={PX} top={hy(1)-BOX.h}/><Strand x={QX} top={hy(.6)-BOX.h}/><Box x={PX} bottom={hy(1)} label="P" muted={q}/><Box x={QX} bottom={hy(.6)} label="Q" accent muted={p}/><Forces pBottom={hy(1)} qBottom={hy(.6)} showP={p||both} showQ={q||both} tension={t>=at(s,'tension')} weightP={t>=at(s,'subP')} weightQ={t>=at(s,'subQ')} accel={t>=at(s,'answer')}/><Values s={s} t={t} acc={t>=at(s,'answer')} tension={t>=at(s,'tension')}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='stage1'){const c=at(s,'signpost'),e=s.beats[0].speechEnd;const p=clamp((active(s,t)-active(s,c))/Math.max(.5,active(s,e)-active(s,c)));const f=p*p;const pBottom=hy(1-f),qBottom=hy(.6+f);const done=t>=at(s,'formula');
  return <><Stage><Txt x={35} y={35}>Stage 1 · string taut · both move 1 m</Txt><Frame/><Rim/><Strand x={PX} top={pBottom-BOX.h}/><Strand x={QX} top={qBottom-BOX.h}/><Box x={PX} bottom={pBottom} label="P"/><Box x={QX} bottom={qBottom} label="Q" accent/><Dim x={190} bottom={hy(1)} id="hP" label="1 m" side="left"/><Dim x={700} bottom={hy(.6)} id="hQ" label="0.6 m" side="right"/>{t>=at(s,'height')&&<Dim x={810} bottom={hy(1.6)} id="hQ1" label="1.6 m" side="right"/>}{done&&<g><Arrow x={QX+80} y={qBottom-10} dy={-70} accent/><Txt x={QX+100} y={qBottom-40} size={26} fill={T.accent}>{t>=at(s,'answer')?'v = 2':'v'}</Txt><Arrow x={PX-80} y={pBottom-110} dy={70} accent/><Txt x={PX-140} y={pBottom-60} size={26} fill={T.accent} anchor="end">{t>=at(s,'answer')?'v = 2':'v'}</Txt></g>}<Values s={s} t={t} acc tension speed={t>=at(s,'answer')}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='stage2'){const r=at(s,'rise');const e=s.beats.find(x=>x.id==='rise')!.speechEnd;const p=t>=r?clamp((active(s,t)-active(s,r))/Math.max(.5,active(s,e)-active(s,r))):0;const up=.2*(1-(1-p)*(1-p));const qBottom=hy(1.6+up);const top=t>=r&&p>=1;
  return <><Stage><Txt x={35} y={35}>Stage 2 · string slack · T = 0</Txt><Frame/><Strand x={PX} top={hy(0)-BOX.h} slack/><Strand x={QX} top={qBottom-BOX.h} slack/><Box x={PX} bottom={hy(0)} label="P"/><Box x={QX} bottom={qBottom} label="Q" accent/>{t>=at(s,'forces')&&<g><Arrow x={QX+60} y={qBottom-BOX.h/2} dy={80}/><Txt x={QX+80} y={qBottom+45} size={26}>mg</Txt></g>}{t>=at(s,'initial')&&!top&&<g><Arrow x={QX-60} y={qBottom-10} dy={-60} accent/><Txt x={QX-135} y={qBottom-40} size={26} fill={T.accent}>u = 2</Txt></g>}{top&&<Txt x={QX-58} y={qBottom-20} size={24} anchor="end">v = 0</Txt>}<Dim x={700} bottom={hy(1.6)} id="hQ1" label="1.6 m" side="right"/>{t>=r&&<g><rect data-label="true" data-dim="rise" x={799} y={qBottom-1} width={22} height={hy(1.6)-qBottom+2} fill="none" stroke="none"/><path d={`M810 ${hy(1.6)} V${qBottom}`} stroke={T.accent} strokeWidth={3}/><path d={`M800 ${qBottom} H820 M800 ${hy(1.6)} H820`} stroke={T.accent} strokeWidth={3}/><Figure id="rise" x={832} y={hy(1.6)-20} size={27}>0.2 m</Figure></g>}<Values s={s} t={t} acc tension speed hmax={t>=at(s,'answer')}/></Stage><Paper s={s} t={t}/></>;}
 // closing: equal masses, then tick the outcomes
 const equal=t>=at(s,'equal');
 return <><Stage><Txt x={35} y={35}>{equal?'Equal masses: a = 0, T = mg':'Equal masses?'}</Txt><Frame/><Rim/><Strand x={PX} top={hy(.8)-BOX.h}/><Strand x={QX} top={hy(.8)-BOX.h}/><Box x={PX} bottom={hy(.8)} label="m"/><Box x={QX} bottom={hy(.8)} label="m" accent/>{equal&&<g><Arrow x={PX-60} y={hy(.8)-28} dy={-90}/><Txt x={PX-140} y={hy(.8)-60} size={26}>T</Txt><Arrow x={PX-60} y={hy(.8)-28} dy={90}/><Txt x={PX-150} y={hy(.8)+70} size={26}>mg</Txt><Arrow x={QX+60} y={hy(.8)-28} dy={-90}/><Txt x={QX+80} y={hy(.8)-60} size={26}>T</Txt><Arrow x={QX+60} y={hy(.8)-28} dy={90}/><Txt x={QX+80} y={hy(.8)+70} size={26}>mg</Txt><Txt x={130} y={720}>Nothing moves: a = 0</Txt></g>}</Stage>{b?.caption?<Note text={`✓ ${b.caption}`}/>:equal?<Paper s={s} t={t}/>:<Note text="Which way would it move?"/>}</>;
};
export const MechanicsConnectedBodiesPulleysFable:React.FC<MechanicsConnectedBodiesPulleysFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
