import React from 'react';
import transcript from '../public/transcripts/mechanics/coefficient-of-friction-harder-problems-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/coefficient-of-friction-harder-problems-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsCoefficientOfFrictionHarderProblemsFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsCoefficientOfFrictionHarderProblemsFableDuration=(fps:number)=>duration(scenes,fps);
/* Ramp geometry: slope 30° rising to the right from A. u = up-slope unit, n = outward normal. Forces on the block at 8 px per newton. */
const S3=Math.sqrt(3),C30=S3/2,S30=.5,K=7;
const A={x:60,y:700},LEN=820;
const u={x:C30,y:-S30},n={x:-S30,y:-C30};
const pt=(s:number,h=0)=>({x:A.x+s*u.x+h*n.x,y:A.y+s*u.y+h*n.y});
const MG=40,WCOS=20*S3,WSIN=20,RN=20*S3,FMAX=.25*RN,PMIN=WSIN-FMAX,PMAX=WSIN+FMAX;
const S0=520;
const surfaceY=(x:number)=>A.y-(x-A.x)*S30/C30;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
/* Arrow from (x,y) along (dx,dy). Four small data-label rects follow the shaft so a diagonal arrow's collision box is tight, not its whole bounding square. */
const Arrow:React.FC<{x:number;y:number;dx:number;dy:number;accent?:boolean;width?:number;dashed?:boolean;muted?:boolean}>=({x,y,dx,dy,accent=false,width=4,dashed=false,muted=false})=><g data-force-arrow="true">{[0,1,2,3].map(i=>{const ax=x+dx*(i+.03)/4,ay=y+dy*(i+.03)/4,bx=x+dx*(i+.97)/4,by=y+dy*(i+.97)/4,w=Math.max(8,Math.abs(bx-ax)),h=Math.max(8,Math.abs(by-ay));return <rect key={i} data-label="true" x={(ax+bx)/2-w/2} y={(ay+by)/2-h/2} width={w} height={h} fill="none" stroke="none"/>;})}<path d={`M${x} ${y} l${dx} ${dy}`} stroke={muted?T.muted:accent?T.accent:T.text} strokeWidth={width} fill="none" strokeDasharray={dashed?'10 8':undefined} markerEnd={muted?'url(#cfh-muted)':accent?'url(#cfh-green)':'url(#cfh-white)'}/></g>;
/* Ramp with 42 blank collision boxes along its outline (40 tight hypotenuse strips, right edge, base) so labels crossing the edge fail the audit. */
const Ramp:React.FC=()=><g><path d={`M${A.x} ${A.y} L${pt(LEN).x} ${pt(LEN).y} L${pt(LEN).x} ${A.y} Z`} fill="#2b3a35" stroke={T.text} strokeWidth={4}/>{Array.from({length:40},(_,i)=>{const a=pt(LEN*i/40),b=pt(LEN*(i+1)/40);return <rect key={i} data-label="true" data-ramp-edge="true" x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)-3} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)+6} fill="none" stroke="none"/>;})}<rect data-label="true" data-ramp-edge="true" x={pt(LEN).x-3} y={pt(LEN).y} width={6} height={A.y-pt(LEN).y} fill="none" stroke="none"/><rect data-label="true" data-ramp-edge="true" x={A.x} y={A.y-3} width={pt(LEN).x-A.x} height={6} fill="none" stroke="none"/><path d={`M${A.x+70} ${A.y} A70 70 0 0 0 ${A.x+70*C30} ${A.y-35}`} fill="none" stroke={T.muted} strokeWidth={2}/><Txt x={A.x+80} y={A.y-12} size={24}>30°</Txt></g>;
const Block:React.FC<{s:number;w?:number;h?:number}>=({s,w=110,h=72})=>{const p=pt(s);return <g data-block-s={s} transform={`translate(${p.x} ${p.y}) rotate(-30)`}><rect x={-w/2} y={-h} width={w} height={h} rx={5} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M${-w/2+8} ${-h/2} H${w/2-8} M${-w/2+8} ${-h*.72} H${w/2-8}`} stroke="#4a3624" strokeWidth={3}/></g>;};
/* Worker standing on the ramp, down-slope of the block, arms towards it. */
const Worker:React.FC<{s:number;lean:number}>=({s,lean})=>{const f=pt(s,0);return <g transform={`translate(${f.x} ${f.y}) rotate(${-8-lean*10})`}><circle cy={-178} r={20} fill={T.text}/><path d="M-16 -150 Q0 -160 16 -150 L22 -80 H-22 Z" fill={T.accent}/><path d="M-12 -80 L-24 -4 M12 -80 L26 -4 M14 -140 L58 -118 M14 -128 L58 -106" fill="none" stroke={T.text} strokeWidth={8} strokeLinecap="round"/></g>;};
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs>{[['cfh-white',T.text],['cfh-green',T.accent],['cfh-muted',T.muted]].map(([id,c])=><marker key={id} id={id} markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={c} strokeWidth={1.5}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const RESULTS=['into','along','subR','sublimit','answer','whatif','limit'];
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?105:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{RESULTS.includes(b.id)&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* Forces on the block. Weight from the centre; R from the top face; P from the up-slope face at mid-height along the slope; friction along the contact line under the block centre, sign + = up the slope. Component arrows are dashed from the centre. */
const Forces:React.FC<{s:number;R?:number;Rlabel?:string;weight?:boolean;weightLabel?:string;components?:boolean;P?:number;Plabel?:string;accentP?:boolean;friction?:number;frictionLabel?:string;accentFriction?:boolean;accentR?:boolean;muteWeight?:boolean}>=({s,R=0,Rlabel='R',weight=false,weightLabel='mg',components=false,P=0,Plabel='P',accentP=false,friction=0,frictionLabel='f',accentFriction=true,accentR=false,muteWeight=false})=>{
 const c=pt(s,36),top=pt(s,72),face=pt(s+55,36),foot=pt(s,1);
 return <g>
  {R>0&&<><Arrow x={top.x} y={top.y} dx={n.x*R*K} dy={n.y*R*K} accent={accentR}/><Txt x={top.x+n.x*R*K-14} y={top.y+n.y*R*K-12} anchor="end" size={26}>{Rlabel}</Txt></>}
  {weight&&<><Arrow x={c.x} y={c.y} dx={0} dy={MG*K} muted={muteWeight}/><Figure id="weightFig" x={c.x-16-(weightLabel.length*14)} y={c.y+MG*K-22} size={26}>{weightLabel}</Figure></>}
  {components&&<><Arrow x={c.x} y={c.y} dx={-u.x*WSIN*K} dy={-u.y*WSIN*K} accent dashed/><Figure id="sinComp" x={c.x-u.x*WSIN*K-70} y={c.y-u.y*WSIN*K-46} size={24}>20 N</Figure><Arrow x={c.x} y={c.y} dx={-n.x*WCOS*K} dy={-n.y*WCOS*K} accent dashed/><Figure id="cosComp" x={c.x-n.x*WCOS*K+12} y={c.y-n.y*WCOS*K+2} size={24}>34.6 N</Figure></>}
  {P>0&&<><Arrow x={face.x} y={face.y} dx={u.x*P*K} dy={u.y*P*K} accent={accentP} width={6}/><Figure id="pushFig" x={face.x+u.x*P*K-40} y={face.y+u.y*P*K-56} size={26}>{Plabel}</Figure></>}
  {friction!==0&&<><Arrow x={foot.x} y={foot.y} dx={u.x*friction*K} dy={u.y*friction*K} accent={accentFriction} width={5}/>{friction>0?<Txt x={foot.x+u.x*friction*K+8} y={surfaceY(foot.x+u.x*friction*K+8)+36} size={24}>{frictionLabel}</Txt>:<Txt x={foot.x+u.x*friction*K-8} y={surfaceY(foot.x+u.x*friction*K-8-160)+36} size={24} anchor="end">{frictionLabel}</Txt>}</>}
  
 </g>;};
/* Large weight triangle, drawn one side at a time as the narration names them, in the empty space above the low end of the ramp. */
const Tri:React.FC<{t:number;first:number;second:number;firstDone:boolean;secondDone:boolean}>=({t,first,second,firstDone,secondDone})=>{
 const p=clamp((t-first)/.6),q=clamp((t-second)/.6);const o={x:200,y:170},L=MG*K,i={x:o.x-n.x*WCOS*K,y:o.y-n.y*WCOS*K},e={x:o.x,y:o.y+L};return <g>
  <path d={`M${o.x} ${o.y} V${e.y}`} stroke={T.text} strokeWidth={5} fill="none" markerEnd="url(#cfh-white)"/><Txt x={o.x-16} y={o.y+L/2} size={26} anchor="end">mg = 40 N</Txt>
  <path d={`M${o.x} ${o.y+95} A95 95 0 0 0 ${o.x-n.x*95} ${o.y-n.y*95}`} fill="none" stroke={T.accent} strokeWidth={3}/><Txt x={o.x+16} y={o.y+84} size={24}>θ</Txt>
  {t>=first&&<><path d={`M${o.x} ${o.y} L${i.x} ${i.y}`} stroke={T.accent} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-p} fill="none"/><Figure id="cosComp" x={(o.x+i.x)/2+18} y={(o.y+i.y)/2-6} size={26}>{firstDone?'mg cos 30° = 34.6 N':'mg cos θ'}</Figure></>}
  {t>=second&&<><path d={`M${i.x} ${i.y} L${e.x} ${e.y}`} stroke={T.accent} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><Figure id="sinComp" x={e.x-60} y={e.y+42} size={26}>{secondDone?'mg sin 30° = 20 N':'mg sin θ'}</Figure></>}
 </g>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const m=s.mode;const done=(id:string)=>{const b=s.beats.find(b=>b.id===id);return !!b&&t>=b.penEnd;};const later=(...modes:string[])=>modes.includes(m);
 const w=later('minimum','maximum','closing')||(m==='resolve'&&done('weight'))?'mg = 40 N':'mg = ?';
 const R=later('minimum','maximum','closing')||(m==='resolve'&&done('subR'))?'R = 34.6 N':'R = ?';
 const f=later('minimum','maximum','closing')||(m==='resolve'&&done('sublimit'))?'f max = 8.66 N':'f max = ?';
 const pmin=later('maximum','closing')||(m==='minimum'&&done('answer'))?'P min = 11.3 N':'P min = ?';
 const pmax=later('closing')||(m==='maximum'&&done('answer'))?'P max = 28.7 N':'P max = ?';
 return <g><path d="M35 728 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={762} size={26}>m = 4 kg</Figure><Figure id="angle" x={200} y={762} size={26}>θ = 30°</Figure><Figure id="mu" x={345} y={762} size={26}>μ = 0.25</Figure><Figure id="gravity" x={505} y={762} size={26}>g = 10 m s⁻²</Figure><Figure id="pushRow" x={705} y={762} size={26}>P up the slope</Figure><Figure id="weightFigRow" x={45} y={800} size={26}>{w}</Figure><Figure id="R" x={200} y={800} size={26}>{R}</Figure><Figure id="fmax" x={345} y={800} size={26}>{f}</Figure><Figure id="Pmin" x={545} y={800} size={26}>{pmin}</Figure><Figure id="Pmax" x={730} y={800} size={26}>{pmax}</Figure></g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Rough plane at 30°, μ = 0.25; block 4 kg; g = 10.','Force P up the plane, along the greatest slope.','In equilibrium. Find the least and greatest P.'];const active=b?.id==='block'?0:b?.id==='push'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={30}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Flat-floor block for the limiting-equilibrium recap: P grows, friction matches it up to the limit. */
const Flat:React.FC<{P:number;f:number;Plabel:string;flabel:string;limit:boolean}>=({P,f,Plabel,flabel,limit})=>{const bx=470,by=560,w=150,h=100,k=5;return <g>
 <path d="M60 560 H880" stroke={T.text} strokeWidth={4}/>{Array.from({length:20},(_,i)=><path key={i} d={`M${80+i*40} 562 l-12 14`} stroke={T.muted} strokeWidth={2}/>)}
 <rect x={bx-w/2} y={by-h} width={w} height={h} rx={6} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M${bx-w/2+10} ${by-h/2} H${bx+w/2-10}`} stroke="#4a3624" strokeWidth={3}/>
 <Arrow x={bx} y={by-h} dx={0} dy={-200}/><Txt x={bx+14} y={by-h-200+6} size={26}>R</Txt>
 <Arrow x={bx} y={by-h/2} dx={0} dy={h/2+200}/><Txt x={bx+14} y={by+200+8} size={26}>mg</Txt>
 {P>0&&<><Arrow x={bx+w/2} y={by-h/2} dx={P*k} dy={0} accent width={5}/><Figure id="push20" x={bx+w/2+P*k*.5-50} y={by-h/2-22} size={26}>{Plabel}</Figure></>}
 {f>0&&<><Arrow x={bx-w/2} y={by-h/2} dx={-f*k} dy={0} accent/><Figure id="f20" x={bx-w/2-f*k*.5-70} y={by-h/2-22} size={26}>{flabel}</Figure></>}
 {limit&&<Txt x={470} y={130} size={26} anchor="middle">On the point of sliding: limiting equilibrium</Txt>}
</g>;};
const grow=(t:number,from:number,to:number,a:number,b:number)=>a+(b-a)*clamp((t-from)/Math.max(.3,to-from));
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Ramp/><Block s={S0}/><Forces s={S0} R={RN} weight P={PMAX} Plabel="P" friction={-FMAX} frictionLabel="f"/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.1 · excerpt · p.31</Txt>{['“limiting friction and','limiting equilibrium”'].map((x,i)=><Txt key={x} x={35} y={165+i*70} size={38} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){const g=at(s,'gentle'),h=at(s,'harder'),l=at(s,'limit'),q=at(s,'question');
  const P=t<g?grow(t,at(s,'scene')+1,g,4,9):t<h?grow(t,g,g+2,9,PMIN):t<l?grow(t,h,h+2.5,PMIN,WSIN+4):grow(t,l,l+2.5,WSIN+4,PMAX);
  const f=t<g?0:t<h?grow(t,g,g+2,0,FMAX):t<l?grow(t,h,h+2.5,FMAX,-(4)):grow(t,l,l+2.5,-4,-FMAX);
  const caption=t>=q?'Two limits: the least and the greatest push':t>=l?'About to slide up: friction at maximum':t>=h?'Pushed harder: friction now acts down the slope':t>=g?'Gentle push: friction acts up the slope':'A worker pushes the box up the ramp';
  return <><Stage><g transform="translate(-15 -45) scale(1.1)"><Ramp/><Block s={S0}/><Worker s={S0-170} lean={clamp(P/PMAX)}/><Forces s={S0} P={P} Plabel={t>=l?'P: largest':t>=h?'P: harder':t>=g?'P: gentle':'P'} accentP friction={Math.abs(f)<.5?0:f} frictionLabel={t>=l?'friction (max)':'friction'} accentFriction/></g><Caption x={60} y={792} text={caption}/></Stage></>;}
 if(s.mode==='concept'){const m=at(s,'match'),r=at(s,'rule'),l=at(s,'limit'),w=at(s,'warn');
  const P=t<m?0:t<l?grow(t,m,m+1.5,0,20):grow(t,l,l+2,20,50);const f=Math.min(P,50);const limit=t>=l+2&&t<w;
  return <><Stage><Txt x={35} y={35}>{t>=w?'At rest does not mean maximum friction':t>=l?'Limiting equilibrium: f = μR':t>=r?'Friction can only reach μR':t>=m?'Friction matches the push':'No push, no friction'}</Txt><Flat P={P} f={f} Plabel={P>=49.9?'P = 50 N':P>0?'P = 20 N':''} flabel={P>=49.9?'f = f max = 50 N':P>0?'f = 20 N':''} limit={limit}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='problem'){const push=t>=at(s,'push');return <><Stage><Txt x={35} y={35}>Rough plane · in equilibrium · P along the slope</Txt><Ramp/><Block s={S0}/><Forces s={S0} R={RN} weight P={push?PMIN+6:0} Plabel="P" accentP/><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='resolve'){const into=at(s,'into'),along=at(s,'along'),bal=at(s,'balance');const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const comps=dn('along');
  return <><Stage><Txt x={35} y={35} size={24}>{t>=bal?'Perpendicular to the slope: R balances mg cos 30°':'Resolve the weight into and down the slope · triangle not to scale'}</Txt><Ramp/><Block s={S0}/><Forces s={S0} R={t>=bal?RN:0} Rlabel={dn('subR')?'R = 34.6 N':'R'} accentR={t>=bal&&!dn('formula')} weight={!comps} weightLabel={dn('weight')?'mg = 40 N':'mg'} components={comps} P={PMIN+6} Plabel="P" friction={dn('sublimit')?FMAX:0} frictionLabel="f max"/>{!comps&&<Tri t={t} first={into} second={along} firstDone={dn('into')} secondDone={dn('along')}/>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='minimum'||s.mode==='maximum'){const mn=s.mode==='minimum';const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const dir=t>=at(s,'direction');
  return <><Stage><Txt x={35} y={35} size={26}>{mn?'Least P: about to slip DOWN, so friction acts UP the slope':'Greatest P: about to slip UP, so friction acts DOWN the slope'}</Txt><Ramp/><Block s={S0}/><Forces s={S0} R={RN} Rlabel="R = 34.6 N" components P={mn?PMIN:PMAX} Plabel={dn('answer')?(mn?'P min = 11.3 N':'P max = 28.7 N'):'P'} accentP={dn('answer')} friction={dir?(mn?FMAX:-FMAX):0} frictionLabel="f max = 8.66 N"/>{dir&&<><Arrow x={pt(mn?S0-110:S0-190,200).x} y={pt(mn?S0-110:S0-190,200).y} dx={(mn?-1:1)*u.x*80} dy={(mn?-1:1)*u.y*80} muted/><Txt x={pt(S0-150,240).x} y={pt(S0-150,240).y} size={22} fill={T.muted} anchor="middle">{mn?'about to slip down':'about to slip up'}</Txt></>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const wi=t>=at(s,'whatif');
 return <><Stage><Txt x={35} y={35} size={26}>{wi?'P = 20 N: the push alone balances mg sin 30°':'Between the limits friction is below its maximum'}</Txt><Ramp/><Block s={S0}/><Forces s={S0} R={RN} Rlabel="R = 34.6 N" components P={wi?WSIN:20} Plabel={wi?'P = 20 N':'11.3 ≤ P ≤ 28.7'} accentP friction={wi?0:4} frictionLabel={wi?'':'f < f max'}/>{wi&&<Txt x={pt(S0+40,0).x} y={surfaceY(pt(S0+40,0).x)+36} size={24}>f = 0</Txt>}<Values s={s} t={t}/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsCoefficientOfFrictionHarderProblemsFable:React.FC<MechanicsCoefficientOfFrictionHarderProblemsFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
