import React from 'react';
import transcript from '../public/transcripts/mechanics/coefficient-of-friction-and-inclined-planes-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/coefficient-of-friction-and-inclined-planes-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsCoefficientOfFrictionAndInclinedPlanesFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsCoefficientOfFrictionAndInclinedPlanesFableDuration=(fps:number)=>duration(scenes,fps);
/* Ramp geometry: slope 30° rising to the right from A. u = up-slope unit, n = outward normal. Forces on the crate at 8 px per newton. */
const S3=Math.sqrt(3),C30=S3/2,S30=.5,K=8;
const A={x:60,y:700},LEN=820;
const u={x:C30,y:-S30},n={x:-S30,y:-C30};
const pt=(s:number,h=0)=>({x:A.x+s*u.x+h*n.x,y:A.y+s*u.y+h*n.y});
const MG=40,WCOS=20*S3,WSIN=20,TP=8,TALONG=4*S3,TPERP=4,RN=20*S3-4,FMAX=.25*RN,DEMAND=WSIN-TALONG,ACC=(DEMAND-FMAX)/4;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
/* Arrow from (x,y) along (dx,dy). Four small data-label rects follow the shaft so a diagonal arrow's collision box is tight, not its whole bounding square. */
const Arrow:React.FC<{x:number;y:number;dx:number;dy:number;accent?:boolean;width?:number;dashed?:boolean;muted?:boolean}>=({x,y,dx,dy,accent=false,width=4,dashed=false,muted=false})=><g data-force-arrow="true">{[0,1,2,3].map(i=>{const ax=x+dx*(i+.03)/4,ay=y+dy*(i+.03)/4,bx=x+dx*(i+.97)/4,by=y+dy*(i+.97)/4,w=Math.max(8,Math.abs(bx-ax)),h=Math.max(8,Math.abs(by-ay));return <rect key={i} data-label="true" x={(ax+bx)/2-w/2} y={(ay+by)/2-h/2} width={w} height={h} fill="none" stroke="none"/>;})}<path d={`M${x} ${y} l${dx} ${dy}`} stroke={muted?T.muted:accent?T.accent:T.text} strokeWidth={width} fill="none" strokeDasharray={dashed?'10 8':undefined} markerEnd={muted?'url(#cfi-muted)':accent?'url(#cfi-green)':'url(#cfi-white)'}/></g>;
const Ramp:React.FC=()=><g><path d={`M${A.x} ${A.y} L${pt(LEN).x} ${pt(LEN).y} L${pt(LEN).x} ${A.y} Z`} fill="#2b3a35" stroke={T.text} strokeWidth={4}/>{Array.from({length:20},(_,i)=>{const a=pt(LEN*i/20),b=pt(LEN*(i+1)/20);return <rect key={i} data-label="true" data-ramp-edge="true" x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)-3} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)+6} fill="none" stroke="none"/>;})}<rect data-label="true" data-ramp-edge="true" x={pt(LEN).x-3} y={pt(LEN).y} width={6} height={A.y-pt(LEN).y} fill="none" stroke="none"/><rect data-label="true" data-ramp-edge="true" x={A.x} y={A.y-3} width={pt(LEN).x-A.x} height={6} fill="none" stroke="none"/><path d={`M${A.x+110} ${A.y} A110 110 0 0 0 ${A.x+110*C30} ${A.y-55}`} fill="none" stroke={T.muted} strokeWidth={2}/><Txt x={A.x+124} y={A.y-14} size={24}>30°</Txt></g>;
const Crate:React.FC<{s:number}>=({s})=>{const p=pt(s);return <g data-crate-s={s} transform={`translate(${p.x} ${p.y}) rotate(-30)`}><rect x={-55} y={-72} width={110} height={72} rx={5} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d="M-47 -36 H47 M-47 -52 H47" stroke="#4a3624" strokeWidth={3}/></g>;};
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs>{[['cfi-white',T.text],['cfi-green',T.accent],['cfi-muted',T.muted]].map(([id,c])=><marker key={id} id={id} markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={c} strokeWidth={1.5}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{['into','along','pullalong','pullperp','subR','sublimit','demand','answer','whatif','whatif2'].includes(b.id)&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* Forces on the crate. Weight from the centre; R from the top face; friction along the ramp from the up-slope bottom corner; rope from the up-slope top corner at 30° above the slope (or along it). */
const Forces:React.FC<{s:number;R?:number;Rlabel?:string;weight?:boolean;weightLabel?:string;components?:boolean;symbolic?:boolean;pull?:'angled'|'along'|'none';pullLabel?:string;pullAngle?:boolean;pullComponents?:boolean;friction?:number;frictionLabel?:string;accentR?:boolean;accentFriction?:boolean;accentPull?:boolean;velocity?:boolean;accel?:boolean}>=({s,R=0,Rlabel='R',weight=true,weightLabel='mg',components=false,symbolic=false,pull='none',pullLabel='T = 8 N',pullAngle=true,pullComponents=false,friction=0,frictionLabel='f',accentR=false,accentFriction=false,accentPull=true,velocity=false,accel=false})=>{
 const c=pt(s,36),top=pt(s,72),tail=pt(s+55,60),foot=pt(s+55,8),d={x:.5,y:-C30};
 return <g>
  {R>0&&<><Arrow x={top.x} y={top.y} dx={n.x*R*K} dy={n.y*R*K} accent={accentR}/><Txt x={top.x+n.x*R*K-14} y={top.y+n.y*R*K-12} anchor="end" size={26}>{Rlabel}</Txt></>}
  {weight&&<><Arrow x={c.x} y={c.y} dx={0} dy={MG*K}/><Figure id="weightFig" x={c.x+16} y={c.y+MG*K+4} size={26}>{weightLabel}</Figure></>}
  {components&&<><Arrow x={c.x} y={c.y} dx={-u.x*WSIN*K} dy={-u.y*WSIN*K} accent dashed/><Figure id="sinComp" x={c.x-u.x*WSIN*K-150} y={c.y-u.y*WSIN*K+30} size={24}>{symbolic?'mg sin θ':'20 N'}</Figure><Arrow x={c.x} y={c.y} dx={-n.x*WCOS*K} dy={-n.y*WCOS*K} accent dashed/><Figure id="cosComp" x={c.x-n.x*WCOS*K-72} y={c.y-n.y*WCOS*K+36} size={24}>{symbolic?'mg cos θ':'34.6 N'}</Figure></>}
  {pull==='angled'&&<><Arrow x={tail.x} y={tail.y} dx={d.x*TP*K} dy={d.y*TP*K} accent={accentPull} width={5}/><path d={`M${tail.x+d.x*TP*K} ${tail.y+d.y*TP*K} L${tail.x+d.x*150} ${tail.y+d.y*150}`} stroke={T.muted} strokeWidth={2} strokeDasharray="4 6"/><Txt x={tail.x+d.x*150+10} y={tail.y+d.y*150-6} size={26}>{pullLabel}</Txt>{pullAngle&&<><path d={`M${tail.x+40*u.x} ${tail.y+40*u.y} A40 40 0 0 0 ${tail.x+40*d.x} ${tail.y+40*d.y}`} fill="none" stroke={T.muted} strokeWidth={2}/><Txt x={tail.x+46} y={tail.y-4} size={22} fill={T.muted}>30°</Txt></>}</>}
  {pull==='along'&&<><Arrow x={tail.x} y={tail.y-30} dx={u.x*TP*K*1.5} dy={u.y*TP*K*1.5} accent width={5}/><Txt x={tail.x+u.x*TP*K*1.5+12} y={tail.y-30+u.y*TP*K*1.5+8} size={26}>{pullLabel}</Txt></>}
  {pullComponents&&<><Arrow x={tail.x} y={tail.y} dx={u.x*TALONG*K} dy={u.y*TALONG*K} accent dashed/><Figure id="pullAlong" x={tail.x+u.x*TALONG*K+8} y={tail.y+u.y*TALONG*K-6} size={24}>6.93 N</Figure><Arrow x={tail.x} y={tail.y} dx={n.x*TPERP*K} dy={n.y*TPERP*K} accent dashed/><Figure id="pullPerp" x={tail.x+n.x*TPERP*K-8} y={tail.y+n.y*TPERP*K-12} size={24}>4 N</Figure></>}
  {friction>0&&<><Arrow x={foot.x} y={foot.y} dx={u.x*friction*K} dy={u.y*friction*K} accent={accentFriction}/><Txt x={foot.x+28} y={foot.y+48} size={26}>{frictionLabel}</Txt></>}
  {velocity&&<><Arrow x={pt(s-30,105).x} y={pt(s-30,105).y} dx={-u.x*90} dy={-u.y*90} muted/><Txt x={pt(s-30,105).x-u.x*90-12} y={pt(s-30,105).y-u.y*90+8} size={24} fill={T.muted} anchor="end">v</Txt></>}
  {accel&&<><Arrow x={pt(s-30,105).x} y={pt(s-30,105).y} dx={-u.x*110} dy={-u.y*110} accent/><Txt x={pt(s-30,105).x-u.x*110-12} y={pt(s-30,105).y-u.y*110+8} size={24} anchor="end">a ≈ 1.35 m s⁻²</Txt></>}
 </g>;};
/* Dashed slope axes through the crate centre for the concept scene, with the weight's θ marked against the perpendicular. */
const Axes:React.FC<{s:number}>=({s})=>{const c=pt(s,36);return <g><path d={`M${c.x-u.x*260} ${c.y-u.y*260} L${c.x+u.x*200} ${c.y+u.y*200}`} stroke={T.muted} strokeWidth={2} strokeDasharray="8 8"/><path d={`M${c.x-n.x*230} ${c.y-n.y*230} L${c.x+n.x*120} ${c.y+n.y*120}`} stroke={T.muted} strokeWidth={2} strokeDasharray="8 8"/><Txt x={c.x+u.x*200+10} y={c.y+u.y*200} size={24} fill={T.muted}>along the slope</Txt><Txt x={c.x+n.x*120+60} y={c.y+n.y*120} size={24} fill={T.muted}>perpendicular</Txt></g>;};
const ThetaAtWeight:React.FC<{s:number}>=({s})=>{const c=pt(s,36);return <g><path d={`M${c.x} ${c.y+112} A112 112 0 0 0 ${c.x-n.x*112} ${c.y-n.y*112}`} fill="none" stroke={T.accent} strokeWidth={3}/><Txt x={c.x+12} y={c.y+102} size={22}>θ</Txt></g>;};
/* Large component triangles, drawn one side at a time as the narration names them. Weight triangle at 6 px/N; rope triangle at 25 px/N. */
const Tri:React.FC<{kind:'weight'|'pull';t:number;first:number;second:number;firstDone:boolean;secondDone:boolean;firstLabel:string;secondLabel:string}>=({kind,t,first,second,firstDone,secondDone,firstLabel,secondLabel})=>{
 const p=clamp((t-first)/.6),q=clamp((t-second)/.6);
 if(kind==='weight'){const o={x:200,y:190},L=MG*K,i={x:o.x-n.x*WCOS*K,y:o.y-n.y*WCOS*K},e={x:o.x,y:o.y+L};return <g>
  <path d={`M${o.x} ${o.y} V${e.y}`} stroke={T.text} strokeWidth={5} fill="none" markerEnd="url(#cfi-white)"/><Txt x={o.x-16} y={o.y+L/2} size={26} anchor="end">mg = 40 N</Txt>
  <path d={`M${o.x} ${o.y+95} A95 95 0 0 0 ${o.x-n.x*95} ${o.y-n.y*95}`} fill="none" stroke={T.accent} strokeWidth={3}/><Txt x={o.x+16} y={o.y+84} size={24}>θ</Txt>
  {t>=first&&<><path d={`M${o.x} ${o.y} L${i.x} ${i.y}`} stroke={T.accent} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-p} fill="none"/><Figure id="cosComp" x={(o.x+i.x)/2+18} y={(o.y+i.y)/2-6} size={26}>{firstDone?firstLabel:'mg cos θ'}</Figure></>}
  {t>=second&&<><path d={`M${i.x} ${i.y} L${e.x} ${e.y}`} stroke={T.accent} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><Figure id="sinComp" x={e.x-140} y={e.y+30} size={26}>{secondDone?secondLabel:'mg sin θ'}</Figure></>}
  
 </g>;}
 const o={x:110,y:480},k=25,d={x:.5,y:-C30},h={x:o.x+d.x*TP*k,y:o.y+d.y*TP*k},a={x:o.x+u.x*TALONG*k,y:o.y+u.y*TALONG*k};return <g>
  <path d={`M${o.x} ${o.y} L${h.x} ${h.y}`} stroke={T.accent} strokeWidth={5} fill="none" markerEnd="url(#cfi-green)"/><Txt x={h.x+12} y={h.y-8} size={26}>T = 8 N</Txt>
  <path d={`M${o.x+60*u.x} ${o.y+60*u.y} A60 60 0 0 0 ${o.x+60*d.x} ${o.y+60*d.y}`} fill="none" stroke={T.text} strokeWidth={2}/><Txt x={o.x+66} y={o.y-8} size={24}>30°</Txt>
  {t>=first&&<><path d={`M${o.x} ${o.y} L${a.x} ${a.y}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-p} fill="none"/><Figure id="pullAlong" x={o.x-60} y={o.y+44} size={26}>{firstDone?firstLabel:'T cos 30°'}</Figure></>}
  {t>=second&&<><path d={`M${a.x} ${a.y} L${h.x} ${h.y}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><Figure id="pullPerp" x={a.x+16} y={a.y-10} size={26}>{secondDone?secondLabel:'T sin 30°'}</Figure></>}
  
 </g>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const m=s.mode;const after=(id:string)=>s.cues[id]!==undefined&&t>=at(s,id);const done=(id:string)=>{const b=s.beats.find(b=>b.id===id);return !!b&&t>=b.penEnd;};
 const later=(...modes:string[])=>modes.includes(m);
 const w=later('reaction','decide','newton','closing')||(m==='resolve'&&done('weight'))?'mg = 40 N':'mg = ?';
 const R=m==='reaction'?done('subR')?'R = 30.6 N':'R = ?':later('decide','newton')?'R = 30.6 N':m==='closing'?done('whatif')?'R = 34.6 N':'R = ?':'R = ?';
 const f=m==='reaction'?done('sublimit')?'f max = 7.66 N':'f max = ?':later('decide','newton')?'f max = 7.66 N':m==='closing'?done('whatif2')?'f max = 8.66 N':'f max = ?':'f max = ?';
 const dir=m==='decide'?after('compare')?'moves: down':'moves: ?':m==='newton'?'moves: down':'moves: ?';
 const a=m==='newton'?done('answer')?'a ≈ 1.35 m s⁻²':'a = ?':'a = ?';
 return <g><path d="M35 728 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={762} size={26}>m = 4 kg</Figure><Figure id="angle" x={200} y={762} size={26}>θ = 30°</Figure><Figure id="mu" x={345} y={762} size={26}>μ = 0.25</Figure><Figure id="pull" x={505} y={762} size={26}>T = 8 N at 30°</Figure><Figure id="gravity" x={735} y={762} size={26}>g = 10 m s⁻²</Figure><Figure id="weightFigRow" x={45} y={800} size={26}>{w}</Figure><Figure id="R" x={200} y={800} size={26}>{R}</Figure><Figure id="fmax" x={345} y={800} size={26}>{f}</Figure><Figure id="dir" x={520} y={800} size={26}>{dir}</Figure><Figure id="a" x={700} y={800} size={26}>{a}</Figure></g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Rough ramp at 30°, μ = 0.25; crate 4 kg; g = 10.','Rope: 8 N at 30° above the ramp, up-slope.','Released from rest. Find R, f max, direction, a.'];const active=b?.id==='crate'?0:b?.id==='rope'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={30}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Down-slope displacement (px) from rest at a cue on the hold-frozen clock; capped so the crate stays on the ramp. */
const slide=(t:number,from:number,k:number,max:number)=>Math.min(max,Math.max(0,.5*k*(t-from)*(t-from)));
const S0=620;
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Ramp/><Crate s={S0}/><Forces s={S0} R={RN} pull="angled" pullLabel="T" friction={FMAX} accentFriction/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.1 · excerpt · p.31</Txt>{['“limiting friction and','limiting equilibrium”'].map((x,i)=><Txt key={x} x={35} y={165+i*70} size={38} fill={T.ink}>{x}</Txt>)}</svg>}</>;
 if(s.mode==='story'){const rel=at(s,'release'),fr=at(s,'friction');const dx=t>=rel?slide(t,rel,6,300):0;const sPos=S0-dx;
  const caption=t>=fr?'Friction acts up the ramp: slow speed-up':t>=rel?'Released: it slides down the ramp':'Held by the worker: it stays put';
  return <><Stage><g transform="translate(-20 -70) scale(1.15)"><Ramp/><Crate s={sPos}/><Forces s={sPos} weight={false} pull="angled" pullLabel="rope" pullAngle={false} friction={t>=fr?FMAX*1.6:0} frictionLabel="friction" accentFriction velocity={t>=rel+.3}/>{t<rel&&<Txt x={pt(sPos,60).x-u.x*120-60} y={pt(sPos,60).y-u.y*120-40} size={24} fill={T.muted}>held</Txt>}</g><Caption x={60} y={792} text={caption}/></Stage></>;}
 if(s.mode==='concept'){const into=at(s,'into'),along=at(s,'along'),rea=at(s,'reaction');
  return <><Stage><Txt x={35} y={35}>{t>=rea?'R balances the perpendicular forces':t>=into?'Weight resolved against the slope':'Two directions on a slope'}</Txt><Ramp/><Crate s={S0}/><Axes s={S0}/><Forces s={S0} R={t>=rea?WCOS:0} Rlabel={t>=rea?'R = mg cos θ':'R'} weightLabel="mg" components={t>=into} symbolic accentR/>{t>=into&&<ThetaAtWeight s={S0}/>}</Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='problem'){const rope=t>=at(s,'rope');return <><Stage><Txt x={35} y={35}>Rough ramp · released from rest · stays in contact</Txt><Ramp/><Crate s={S0}/><Forces s={S0} R={RN} pull={rope?'angled':'none'} friction={0} accentPull/><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='resolve'){const into=at(s,'into'),along=at(s,'along'),pu=at(s,'pull'),pa=at(s,'pullalong'),pp=at(s,'pullperp'),rep=t>=at(s,'replace');const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;
  return <><Stage><Txt x={35} y={35} size={24}>{rep?'Four parts replace the weight and the rope':t>=pu?'Resolve the rope: along and away from the slope · triangle not to scale':'Resolve the weight: into and down the slope · triangle not to scale'}</Txt><Ramp/><Crate s={S0}/><Forces s={S0} R={RN} weight={!rep} weightLabel={dn('weight')?'mg = 40 N':'mg'} components={rep} pull={rep?'none':'angled'} pullComponents={rep} friction={0}/>{!rep&&(t<pu?<Tri kind="weight" t={t} first={into} second={along} firstDone={dn('into')} secondDone={dn('along')} firstLabel="mg cos 30° = 34.6 N" secondLabel="mg sin 30° = 20 N"/>:<Tri kind="pull" t={t} first={pa} second={pp} firstDone={dn('pullalong')} secondDone={dn('pullperp')} firstLabel="T cos 30° = 6.93 N" secondLabel="T sin 30° = 4 N"/>)}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='reaction'){const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;return <><Stage><Txt x={35} y={35}>Perpendicular to the slope: nothing moves that way</Txt><Ramp/><Crate s={S0}/><Forces s={S0} R={RN} Rlabel={dn('subR')?'R = 30.6 N':'R'} weight={false} components pull="none" pullComponents friction={dn('sublimit')?FMAX:0} frictionLabel="f max" accentR={t<at(s,'formula')} accentFriction/><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='decide'){const cmp=t>=at(s,'compare'),sl=t>=at(s,'slide');const dx=sl?slide(t,at(s,'slide'),8,90):0;const sPos=S0-dx;
  return <><Stage><Txt x={35} y={35}>{cmp?'Down wins: it slides down; friction acts up the slope':'Along the slope, without friction: which way?'}</Txt><Ramp/><Crate s={sPos}/><Forces s={sPos} R={RN} Rlabel="R = 30.6 N" weight={false} components pull="none" pullComponents friction={cmp?FMAX:0} frictionLabel="f" accentFriction velocity={sl}/>{t>=at(s,'demand')&&<Figure id="demand" x={26} y={185} size={26}>{cmp?'down 13.1 N > f max 7.66 N':'down: 20 − 6.93 = 13.1 N'}</Figure>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='newton'){const dx=slide(t,at(s,'law'),4,110);const sPos=S0-dx;const ans=t>=at(s,'answer');
  return <><Stage><Txt x={35} y={35}>Sliding down · resultant along the slope · down is positive</Txt><Ramp/><Crate s={sPos}/><Forces s={sPos} R={RN} Rlabel="R = 30.6 N" weight={false} components pull="none" pullComponents friction={FMAX} frictionLabel="f" accentFriction accel={ans}/><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const w1=t>=at(s,'whatif');const dn=(id:string)=>s.cues[id]!==undefined&&t>=s.beats.find(b=>b.id===id)!.penEnd;
 return <><Stage><Txt x={35} y={35}>Rope along the ramp: no perpendicular part</Txt><Ramp/><Crate s={S0}/><Forces s={S0} R={WCOS} Rlabel={dn('whatif')?'R = mg cos θ = 34.6 N':'R'} weightLabel="mg = 40 N" pull="along" pullLabel="T = 8 N" friction={dn('whatif2')?.25*WCOS:0} frictionLabel="f max" accentR={w1&&!dn('whatif2')} accentFriction/><Values s={s} t={t}/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsCoefficientOfFrictionAndInclinedPlanesFable:React.FC<MechanicsCoefficientOfFrictionAndInclinedPlanesFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
