import React from 'react';
import transcript from '../public/transcripts/mechanics/work.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-m42/Ink';
import {WorkShapeAudit} from './mechanics-work/ShapeAudit';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsWorkProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsWorkDuration=(fps:number)=>duration(scenes,fps);
const C=Math.sqrt(3)/2,R=20*Math.sqrt(3),F=5*Math.sqrt(3);
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string}>=({x,y,children,size=27,fill=T.text})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size}>{children}</text>;
const Arrow:React.FC<{id:string;x:number;y:number;dx:number;dy:number;accent?:boolean}>=({id,x,y,dx,dy,accent=false})=><path data-force-arrow={id} d={`M${x} ${y} l${dx} ${dy}`} stroke={accent?T.accent:T.text} strokeWidth={4} fill="none" markerEnd={accent?'url(#work-green)':'url(#work-white)'}/>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={830} style={{position:'absolute',left:80,top:190}}><defs>{[['white',T.text],['green',T.accent]].map(([id,color])=><marker key={id} id={'work-'+id} markerWidth={8} markerHeight={8} refX={7} refY={4} orient="auto"><path d="M1 1 L7 4 L1 7" fill="none" stroke={color} strokeWidth={1.5}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string}>=({text})=><svg data-region="caption" width={800} height={220} style={{position:'absolute',left:1040,top:435}}><Caption x={24} y={85} text={text}/></svg>;
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);const gap=Math.min(132,674/Math.max(1,bs.length-1));return <svg data-region="paper" data-visual="paper" width={800} height={780} style={{position:'absolute',left:1040,top:205}}><rect x={1} y={1} width={798} height={778} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(34,718/prepareLine(b.ink!,1).width),y=42+i*gap;return t>=b.cue?<g key={b.id} data-ink-id={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{b.hold>=2&&t>=b.penEnd&&<path d={`M38 ${y+47} Q360 ${y+57} ${38+prepareLine(b.ink!,size).width} ${y+47}`} fill="none" stroke={T.accent} strokeWidth={3}/>}</g>:null;})}</svg>;};
const known=(s:Scene,t:number,id:string)=>s.cues[id]!==undefined&&t>=at(s,id);
const Givens:React.FC<{s:Scene;t:number}>=({s,t})=><g><path d="M35 590 H895" stroke={T.muted}/><Figure id="mass" x={45} y={637}>m = 4 kg</Figure><Figure id="distance" x={325} y={637}>d = 5 m</Figure><Figure id="angle" x={615} y={637}>θ = 30°</Figure><Figure id="mu" x={45} y={687}>μ = 0.25</Figure><Figure id="gravity" x={325} y={687}>g = 10 m s⁻²</Figure><Txt x={615} y={687}>f = μR</Txt><Txt x={45} y={739} size={23}>Constant speed · contact maintained · P parallel uphill</Txt><Txt x={45} y={782} size={23}>Only forces: pull P, weight mg, reaction R, sliding friction f</Txt></g>;
const Crate:React.FC<{bottom:number}>=({bottom})=>{const x=bottom-22.5,y=520-(bottom-120)/Math.sqrt(3)-45*C;return <g data-box-x={x} data-box-y={y} transform={`translate(${x} ${y}) rotate(-30)`}><rect x={-60} y={-45} width={120} height={90} fill="#31453f" stroke={T.text} strokeWidth={3}/><path d="M-60 -45 L0 -20 L60 -45 M0 -20 V45" stroke={T.muted} strokeWidth={2}/></g>;};
const Slope:React.FC<{s:Scene;t:number;simple?:boolean}>=({s,t,simple=false})=>{const story=s.mode==='story';const gravity=s.mode==='gravity';const down=s.mode==='signs'&&known(s,t,'whatif');const active=(v:number)=>v-s.holds.reduce((n,h)=>n+Math.max(0,Math.min(v,h.end)-h.start),0);const bottom=story?210+470*active(t)/active(s.duration):gravity?700:440;const bx=bottom-22.5,by=520-(bottom-120)/Math.sqrt(3)-45*C;const rKnown=['gravity','signs','recap'].includes(s.mode)||known(s,t,'reactionResult');const fKnown=['gravity','signs','recap'].includes(s.mode)||known(s,t,'frictionResult');const wfKnown=['gravity','signs','recap'].includes(s.mode)||known(s,t,'workExactResult');const approx=['gravity','signs','recap'].includes(s.mode)||known(s,t,'workApproxResult');const hKnown=['signs','recap'].includes(s.mode)||known(s,t,'heightResult');const wgKnown=['signs','recap'].includes(s.mode)||known(s,t,'gravityResult');const components=s.mode==='friction';return <g>
<Txt x={40} y={38} size={27}>{story?'Sliding steadily uphill':simple?'A crate on a rough slope':down?'Downhill contrast · direction snapshot':'Uphill journey · force/position snapshot'}</Txt>
<path d={`M120 520 L850 ${520-730/Math.sqrt(3)} M120 520 H865`} stroke={T.muted} strokeWidth={3} fill="none"/>{Array.from({length:19},(_,i)=><path key={i} d={`M${140+i*36} ${520-(20+i*36)/Math.sqrt(3)} l-5 15`} stroke={T.muted} strokeWidth={1.5}/>)}<Crate bottom={bottom}/>
{!gravity&&!simple&&!down&&<><Arrow id="pull" x={bx+60*C} y={by-30} dx={(20+F)*4*C} dy={-(20+F)*2} accent/><Txt x={660} y={145}>P</Txt><Arrow id="reaction" x={bx-23} y={by-40} dx={-R*2} dy={-R*4*C}/><Figure id="reaction" x={50} y={106}>{rKnown?'R = 20√3 N':'R = ?'}</Figure><Arrow id="friction" x={bx-60*C} y={by+30} dx={-F*4*C} dy={F*2}/><Figure id="friction" x={50} y={410}>{fKnown?'f = 5√3 N':'f = ?'}</Figure>{components?<><Arrow id="weightNormal" x={bx+23} y={by+40} dx={R*2} dy={R*4*C}/><Txt x={560} y={473}>mg cos θ</Txt><Arrow id="weightParallel" x={bx-15} y={by+45} dx={-20*4*C} dy={40}/><Txt x={50} y={468}>mg sin θ</Txt></>:<><Arrow id="weight" x={bx} y={by+52} dx={0} dy={160}/><Txt x={bx+35} y={by+181}>mg</Txt></>}</>}
{gravity&&<><path d={`M180 ${520-60/Math.sqrt(3)} L700 ${520-580/Math.sqrt(3)} L700 ${520-60/Math.sqrt(3)} Z`} fill="none" stroke={T.accent} strokeWidth={3} strokeDasharray="10 8"/><Figure id="slopeDistance" x={285} y={329}>d = 5 m</Figure><Figure id="height" x={728} y={365} size={26}>{hKnown?'h = 2.5 m':'h = ?'}</Figure><Txt x={235} y={466}>30°</Txt></>}
{(simple||down)&&<><path d={down?'M640 310 l-145 84':'M500 140 l140 -81'} stroke={T.accent} strokeWidth={5} markerEnd="url(#work-green)" fill="none"/><Txt x={590} y={down?455:480}>{down?'Motion downhill':'Motion uphill'}</Txt>{down&&<><Arrow id="frictionContrast" x={bx+60*C} y={by-30} dx={85*C} dy={-42.5}/><Txt x={630} y={220}>f uphill</Txt><Arrow id="gravityContrast" x={bx} y={by+52} dx={0} dy={145}/><Txt x={470} y={490}>mg down</Txt></>}</>}
{!simple&&<>{!down&&<><Figure id="frictionWork" x={45} y={555} size={25}>{wfKnown?approx?'Wf = 25√3 ≈ 43.3 J':'Wf = 25√3 J':'Wf = ? (against friction)'}</Figure><Figure id="gravityWork" x={520} y={555} size={25}>{wgKnown?'Wg = 100 J':'Wg = ? (against gravity)'}</Figure></>}<Givens s={s} t={t}/></>}
</g>;};
const Component:React.FC<{s:Scene;t:number}>=({s,t})=>{const resolved=known(s,t,'resolve'),parallel=known(s,t,'parallel'),stationary=known(s,t,'stationary');return <Stage><Txt x={35} y={38}>{parallel?'Parallel-force case':'General constant-force diagram'}</Txt><Txt x={35} y={85} size={24}>{parallel?'α = 0 · full force along displacement':'α is measured from displacement'}</Txt><path d="M100 480 H850" stroke={T.muted} strokeWidth={3}/><rect x={320} y={340} width={130} height={140} fill="#31453f" stroke={T.text} strokeWidth={3}/>{parallel?<><Arrow id="parallelForce" x={450} y={355} dx={240} dy={0} accent/><Txt x={630} y={325}>F</Txt></>:resolved?<><Arrow id="parallelComponent" x={450} y={355} dx={240*C} dy={0} accent/><Txt x={570} y={325}>F cos α</Txt><Arrow id="perpendicularComponent" x={450} y={355} dx={0} dy={-120}/><Txt x={485} y={230}>F sin α</Txt></>:<><Arrow id="angled" x={450} y={355} dx={240*C} dy={-120} accent/><Txt x={615} y={210}>F</Txt><path d="M450 355 H670" stroke={T.muted} strokeDasharray="6 5"/><Txt x={500} y={340}>α</Txt></>}{!stationary&&<path d="M320 550 H720" stroke={T.accent} strokeWidth={4} markerEnd="url(#work-green)"/>}<Txt x={350} y={600}>{stationary?'No motion: d = 0':'Displacement d →'}</Txt><Txt x={80} y={700} size={26}>Our example: P is parallel; R is perpendicular</Txt></Stage>;};
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);if(s.mode==='opening')return <><Stage><Slope s={s} t={t} simple/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={360} style={{position:'absolute',left:1040,top:330}}><rect x={1} y={1} width={798} height={330} rx={12} fill={T.paper}/><Txt x={35} y={75} fill={T.ink}>Syllabus 4.5 · excerpt · p.33</Txt><Txt x={35} y={180} size={40} fill={T.ink}>“work done by a force”</Txt></svg>}</>;
if(s.mode==='story')return <><Stage><Slope s={s} t={t} simple/></Stage><Note text="Same speed throughout the climb"/></>;
if(s.mode==='problem')return <><Stage><Slope s={s} t={t}/></Stage><svg data-region="problem" width={800} height={650} style={{position:'absolute',left:1040,top:250}}><rect x={1} y={1} width={798} height={648} rx={12} fill={T.paper}/>{['Pull a crate up the rough ramp steadily.','Use the givens and sliding model shown.','Find work against friction and against gravity.'].map((line,i)=><g key={line}><Txt x={30} y={125+i*180} size={30} fill={T.ink}>{line}</Txt>{t>=at(s,i===0?'mass':i===1?'conditions':'unknown')&&<path d={`M30 ${142+i*180} H760`} stroke={T.accent} strokeWidth={3}/>}</g>)}</svg></>;
if(s.mode==='component')return <><Component s={s} t={t}/><Paper s={s} t={t}/></>;
if(s.mode==='recap')return <><Stage><Slope s={s} t={t}/></Stage><Note text={b?.caption??'Match the force with its displacement'}/></>;
if(s.mode==='signs'&&known(s,t,'whatif'))return <><Stage><Slope s={s} t={t}/></Stage><Note text="Downhill: gravity helps; friction still resists"/></>;
return <><Stage><Slope s={s} t={t}/></Stage><Paper s={s} t={t}/></>;};
export const MechanicsWork:React.FC<MechanicsWorkProps>=props=><><Lesson scenes={scenes} content={Content} {...props}/>{props.audit&&<WorkShapeAudit/>}</>;
