import React from 'react';
import transcript from '../public/transcripts/mechanics/work-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/work-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsWorkFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsWorkFableDuration=(fps:number)=>duration(scenes,fps);
/* Ramp geometry: slope 30° rising to the right from A. u = up-slope unit, n = outward normal. 80 px per metre along the ramp; forces at 4 px per newton, all inside a 1.3× group. */
const S3=Math.sqrt(3),C30=S3/2,S30=.5,K=4,PXM=80;
const A={x:60,y:700},LEN=720;
/* Ramp scenes are drawn 1.3× about the ramp foot so the diagram fills the stage; the values row and sub-heading stay in stage coordinates. */
const RampGroup:React.FC<{children:React.ReactNode}>=({children})=><g transform="translate(-58 -210) scale(1.3)">{children}</g>;
const FlatGroup:React.FC<{children:React.ReactNode}>=({children})=><g transform="translate(-40 -200) scale(1.3)">{children}</g>;
const u={x:C30,y:-S30},n={x:-S30,y:-C30};
const pt=(s:number,h=0)=>({x:A.x+s*u.x+h*n.x,y:A.y+s*u.y+h*n.y});
const MG=40,RN=20*S3,FR=.25*RN,PULL=FR+MG*S30,S0=250,S1=S0+5*PXM;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
/* Arrow from (x,y) along (dx,dy). Four small data-label rects follow the shaft so a diagonal arrow's collision box is tight. */
const Arrow:React.FC<{x:number;y:number;dx:number;dy:number;accent?:boolean;width?:number;dashed?:boolean;muted?:boolean}>=({x,y,dx,dy,accent=false,width=4,dashed=false,muted=false})=><g data-force-arrow="true">{[0,1,2,3].map(i=>{const ax=x+dx*(i+.03)/4,ay=y+dy*(i+.03)/4,bx=x+dx*(i+.97)/4,by=y+dy*(i+.97)/4,w=Math.max(8,Math.abs(bx-ax)),h=Math.max(8,Math.abs(by-ay));return <rect key={i} data-label="true" x={(ax+bx)/2-w/2} y={(ay+by)/2-h/2} width={w} height={h} fill="none" stroke="none"/>;})}<path d={`M${x} ${y} l${dx} ${dy}`} stroke={muted?T.muted:accent?T.accent:T.text} strokeWidth={width} fill="none" strokeDasharray={dashed?'10 8':undefined} markerEnd={muted?'url(#wk-muted)':accent?'url(#wk-green)':'url(#wk-white)'}/></g>;
/* Thin collision boxes along a segment so dimension markers and outlines take part in the audit. */
const Guard:React.FC<{a:{x:number;y:number};b:{x:number;y:number};parts?:number}>=({a,b,parts=6})=><g>{Array.from({length:parts},(_,i)=>{const p={x:a.x+(b.x-a.x)*i/parts,y:a.y+(b.y-a.y)*i/parts},q={x:a.x+(b.x-a.x)*(i+1)/parts,y:a.y+(b.y-a.y)*(i+1)/parts};return <rect key={i} data-label="true" x={Math.min(p.x,q.x)-3} y={Math.min(p.y,q.y)-3} width={Math.abs(q.x-p.x)+6} height={Math.abs(q.y-p.y)+6} fill="none" stroke="none"><title>·guard</title></rect>;})}</g>;
const Ramp:React.FC<{smooth?:boolean}>=({smooth=false})=><g><path d={`M${A.x} ${A.y} L${pt(LEN).x} ${pt(LEN).y} L${pt(LEN).x} ${A.y} Z`} fill={smooth?'#33434a':'#2b3a35'} stroke={T.text} strokeWidth={4}/>{!smooth&&Array.from({length:12},(_,i)=>{const p=pt(40+i*56,-2);return <path key={i} d={`M${p.x} ${p.y} l-6 12`} stroke={T.muted} strokeWidth={2}/>;})}<Guard a={A} b={pt(LEN)} parts={20}/><Guard a={pt(LEN)} b={{x:pt(LEN).x,y:A.y}} parts={4}/><Guard a={A} b={{x:pt(LEN).x,y:A.y}} parts={6}/><path d={`M${A.x+110} ${A.y} A110 110 0 0 0 ${A.x+110*C30} ${A.y-55}`} fill="none" stroke={T.muted} strokeWidth={2}/><Figure id="angleFig" x={A.x+128} y={A.y-24} size={24}>30°</Figure></g>;
const Crate:React.FC<{s:number}>=({s})=>{const p=pt(s);return <g data-crate-s={s} transform={`translate(${p.x} ${p.y}) rotate(-30)`}><rect x={-55} y={-72} width={110} height={72} rx={5} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d="M-47 -36 H47 M-47 -52 H47" stroke="#4a3624" strokeWidth={3}/></g>;};
/* Distance along the ramp (inside the fill, parallel to the surface) and the vertical rise at the finishing position. */
const DistMarker:React.FC<{label:string;accent?:boolean}>=({label,accent=false})=>{const a=pt(S0-55,-42),b=pt(S1+55,-42);return <g><path d={`M${a.x} ${a.y} L${b.x} ${b.y}`} stroke={accent?T.accent:T.muted} strokeWidth={3} strokeDasharray="12 8"/><path d={`M${pt(S0-55,-30).x} ${pt(S0-55,-30).y} L${pt(S0-55,-54).x} ${pt(S0-55,-54).y} M${pt(S1+55,-30).x} ${pt(S1+55,-30).y} L${pt(S1+55,-54).x} ${pt(S1+55,-54).y}`} stroke={accent?T.accent:T.muted} strokeWidth={3}/><Guard a={a} b={b} parts={16}/><Figure id="distFig" x={pt(S0+130,-98).x} y={pt(S0+130,-98).y+8} size={25}>{label}</Figure></g>;};
const RiseMarker:React.FC<{label:string;accent?:boolean;base?:boolean}>=({label,accent=false,base=true})=>{const top=pt(S1+55),x=top.x,y0=pt(S0-55).y;return <g>{base&&<path d={`M${pt(S0-55).x} ${y0} H${x}`} stroke={T.muted} strokeWidth={2} strokeDasharray="8 8"/>}<path d={`M${x} ${top.y} V${y0}`} stroke={accent?T.accent:T.muted} strokeWidth={3} strokeDasharray="12 8"/><path d={`M${x-12} ${top.y} H${x+12} M${x-12} ${y0} H${x+12}`} stroke={accent?T.accent:T.muted} strokeWidth={3}/><Guard a={{x,y:top.y}} b={{x,y:y0}}/><Figure id="hFig" x={label==='h'?x-26:x-50} y={label==='h'?(top.y+y0)/2+8:y0-22} size={25}>{label}</Figure></g>;};
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs>{[['wk-white',T.text],['wk-green',T.accent],['wk-muted',T.muted]].map(([id,c])=><marker key={id} id={id} markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={c} strokeWidth={1.5}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const UNDERLINE=['formula','units','subR','subf','subh','answer','whatif'];
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{UNDERLINE.includes(b.id)&&(b.id!=='formula'||s.mode==='define')&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* Forces on the crate: rope up-slope from the top up-slope corner, friction down-slope from the bottom, R from the top face, weight from the centre. */
const Forces:React.FC<{s:number;rope?:boolean;ropeLabel?:string;friction?:boolean;frictionLabel?:string;R?:boolean;Rlabel?:string;weight?:boolean;weightLabel?:string;into?:boolean;accentR?:boolean;accentF?:boolean;accentRope?:boolean;velocity?:boolean;ropeLen?:number}>=({s,rope=true,ropeLen=PULL*K,ropeLabel='P',friction=false,frictionLabel='f',R=false,Rlabel='R',weight=true,weightLabel='mg',into=false,accentR=false,accentF=false,accentRope=true,velocity=false})=>{
 const c=pt(s,36),top=pt(s,72),head=pt(s+55,50),foot=pt(s-55,10);
 return <g>
  {R&&<><Arrow x={top.x} y={top.y} dx={n.x*RN*K} dy={n.y*RN*K} accent={accentR}/><Figure id="RFig" x={top.x+n.x*RN*K+10} y={top.y+n.y*RN*K-6} size={26}>{Rlabel}</Figure></>}
  {weight&&<><Arrow x={c.x} y={c.y} dx={0} dy={MG*K}/><Figure id="weightFig" x={s>=S1-50?c.x-128:c.x+80} y={s>=S1-50?c.y+MG*K+50:c.y+MG*K-22} size={26}>{weightLabel}</Figure></>}
  {into&&<><Arrow x={c.x} y={c.y} dx={-n.x*RN*K} dy={-n.y*RN*K} accent dashed/><Figure id="intoFig" x={c.x-n.x*RN*K+20} y={c.y-n.y*RN*K-22} size={24}>34.6 N</Figure></>}
  {rope&&<><Arrow x={head.x} y={head.y} dx={u.x*ropeLen} dy={u.y*ropeLen} accent={accentRope} width={5}/><Txt x={head.x+u.x*ropeLen/2+n.x*42} y={head.y+u.y*ropeLen/2+n.y*42+9} size={26} anchor="middle">{ropeLabel}</Txt></>}
  {friction&&<><Arrow x={foot.x} y={foot.y} dx={-u.x*FR*K*1.6} dy={-u.y*FR*K*1.6} accent={accentF}/><Figure id="fFig" x={foot.x-u.x*FR*K*1.6-8-(frictionLabel.length*13)} y={foot.y-u.y*FR*K*1.6-16} size={26}>{frictionLabel}</Figure></>}
  {velocity&&<><Arrow x={pt(s+20,150).x} y={pt(s+20,150).y} dx={u.x*80} dy={u.y*80} muted/><Txt x={pt(s+20,150).x-12} y={pt(s+20,150).y+8} size={24} fill={T.muted} anchor="end">steady speed</Txt></>}
 </g>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const m=s.mode;const done=(id:string)=>{const b=s.beats.find(b=>b.id===id);return !!b&&t>=b.penEnd;};
 const R=m==='friction'?done('subR')?'R = 34.6 N':'R = ?':['gravity','closing'].includes(m)?'R = 34.6 N':'R = ?';
 const f=m==='friction'?done('subf')?'f = 8.66 N':'f = ?':m==='gravity'?'f = 8.66 N':m==='closing'?done('whatif')?'f = 0':'f = 8.66 N':'f = ?';
 const h=m==='gravity'?done('subh')?'h = 2.5 m':'h = ?':m==='closing'?'h = 2.5 m':'h = ?';
 const wf=m==='friction'?done('answer')?'W f = 43.3 J':'W f = ?':m==='gravity'?'W f = 43.3 J':m==='closing'?done('whatif')?'W f = 0 J':'W f = 43.3 J':'W f = ?';
 const wg=m==='gravity'?done('answer')?'W g = 100 J':'W g = ?':m==='closing'?'W g = 100 J':'W g = ?';
 return <g><path d="M35 728 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={762} size={26}>m = 4 kg</Figure><Figure id="angle" x={215} y={762} size={26}>θ = 30°</Figure><Figure id="mu" x={385} y={762} size={26}>μ = 0.25</Figure><Figure id="dist" x={560} y={762} size={26}>d = 5 m</Figure><Figure id="gravity" x={715} y={762} size={26}>g = 10 m s⁻²</Figure><Figure id="R" x={45} y={800} size={26}>{R}</Figure><Figure id="f" x={215} y={800} size={26}>{f}</Figure><Figure id="h" x={385} y={800} size={26}>{h}</Figure><Figure id="Wf" x={540} y={800} size={26}>{wf}</Figure><Figure id="Wg" x={725} y={800} size={26}>{wg}</Figure></g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Crate 4 kg dragged 5 m up a rough ramp at 30°; g = 10.','Rope parallel to the ramp; constant speed; μ = 0.25.','Find the work against friction and against gravity.'];const active=b?.id==='crate'?0:b?.id==='rope'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={29}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Narration time with the inserted holds removed, so motion stays continuous across pauses. */
const active=(s:Scene,v:number)=>v-s.holds.reduce((k,h)=>k+Math.max(0,Math.min(v,h.end)-h.start),0);
const climb=(s:Scene,t:number,from:number,to:number)=>S0+(S1-S0)*clamp((active(s,t)-active(s,from))/Math.max(.5,active(s,to)-active(s,from)));
/* Flat-floor box for the definition and angle scenes. */
const FLOOR=560;
const Box:React.FC<{x:number}>=({x})=><g data-box-x={x}><rect x={x} y={FLOOR-110} width={140} height={110} rx={6} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M${x+12} ${FLOOR-55} H${x+128} M${x+12} ${FLOOR-80} H${x+128}`} stroke="#4a3624" strokeWidth={3}/></g>;
const Floor:React.FC=()=><g><path d={`M40 ${FLOOR} H700`} stroke={T.text} strokeWidth={4}/><Guard a={{x:40,y:FLOOR}} b={{x:700,y:FLOOR}} parts={10}/>{Array.from({length:13},(_,i)=><path key={i} d={`M${60+i*50} ${FLOOR+4} l-8 14`} stroke={T.muted} strokeWidth={2}/>)}</g>;
/* Large weight component triangle for s06, in stage coordinates beside the ramp: mg vertical, then the part into the ramp, drawn as the narration names them. */
const WeightTri:React.FC<{t:number;mgAt:number;intoAt:number;value:boolean}>=({t,mgAt,intoAt,value})=>{const o={x:600,y:48},k=7,L=MG*k,i={x:o.x-n.x*RN*k,y:o.y-n.y*RN*k},e={x:o.x,y:o.y+L};const p=clamp((t-mgAt)/.6),q=clamp((t-intoAt)/.6);return <g>{t>=mgAt&&<><path d={`M${o.x} ${o.y} V${e.y}`} stroke={T.text} strokeWidth={5} fill="none" pathLength={1} strokeDasharray={1} strokeDashoffset={1-p} markerEnd="url(#wk-white)"/><Figure id="triMg" x={o.x-140} y={o.y+L/2+8} size={26}>mg = 40 N</Figure></>}{t>=intoAt&&<><path d={`M${o.x} ${o.y} L${i.x} ${i.y}`} stroke={T.accent} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><path d={`M${i.x} ${i.y} L${e.x} ${e.y}`} stroke={T.muted} strokeWidth={2} strokeDasharray="4 8" opacity={q}/><path d={`M${o.x} ${o.y+45} A45 45 0 0 0 ${o.x-n.x*45} ${o.y-n.y*45}`} fill="none" stroke={T.accent} strokeWidth={3}/><Txt x={o.x+12} y={o.y+100} size={22}>θ</Txt><Figure id="intoTri" x={(o.x+i.x)/2+22} y={(o.y+i.y)/2-4} size={26}>{value?'mg cos θ = 34.6 N':'mg cos θ'}</Figure></>}</g>;};
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><RampGroup><Ramp/><Crate s={400}/><Forces s={400} ropeLabel="rope" weight={false}/><DistMarker label="along the ramp"/></RampGroup></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.5 · excerpt · p.33</Txt><Txt x={35} y={185} size={38} fill={T.ink}>“work done by a force”</Txt></svg>}</>;
 if(s.mode==='story'){const pull=at(s,'pull'),drag=at(s,'drag'),height=at(s,'height');const sPos=climb(s,t,pull,height);
  const caption=t>=at(s,'question')?'Two jobs for the rope: friction and gravity':t>=height?'A long way along, a small rise':t>=drag?'Friction drags back; weight pulls down':'Dragged up at a steady speed';
  return <><Stage><RampGroup><Ramp/><Crate s={sPos}/><Forces s={sPos} ropeLabel="rope" ropeLen={120} weight={t>=drag} friction={t>=drag} frictionLabel="friction" accentF velocity/>{t>=height&&<><DistMarker label="along the ramp" accent/><RiseMarker label="rise" accent/></>}</RampGroup><Caption x={60} y={792} text={caption}/></Stage></>;}
 if(s.mode==='define'){const push=at(s,'push'),still=at(s,'still');const x=t>=still?330:120+240*clamp((t-push)/2.5);
  return <><Stage><Txt x={35} y={35}>{t>=still?'Pushing a wall: nothing moves':'Pushing a box along the floor'}</Txt><FlatGroup><Floor/>{t>=still&&<rect x={470} y={FLOOR-330} width={40} height={330} fill="#3b4a52" stroke={T.text} strokeWidth={4}/>}<Box x={x}/><Arrow x={x-110} y={FLOOR-55} dx={100} dy={0} accent width={5}/><Txt x={x-72} y={FLOOR-72} size={26}>F</Txt>{t>=still?<Txt x={330} y={FLOOR+70} size={26} fill={T.accent}>d = 0 → W = 0</Txt>:t>=push&&<><path d={`M120 ${FLOOR+60} H${x}`} stroke={T.accent} strokeWidth={3} strokeDasharray="12 8"/><path d={`M120 ${FLOOR+46} V${FLOOR+74} M${x} ${FLOOR+46} V${FLOOR+74}`} stroke={T.accent} strokeWidth={3}/><Txt x={(120+x)/2-30} y={FLOOR+110} size={26}>d</Txt></>}</FlatGroup></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='angle'){const comp=at(s,'component'),perp=at(s,'perp'),grav=at(s,'gravity');
  if(t>=grav)return <><Stage><Txt x={35} y={35}>Lifting straight up: work against gravity</Txt><FlatGroup><Floor/><g><rect x={500} y={FLOOR-300} width={140} height={110} rx={6} fill="#6b5237" stroke={T.text} strokeWidth={4}/><Arrow x={570} y={FLOOR-300} dx={0} dy={-90} accent width={5}/><Txt x={590} y={FLOOR-345} size={26}>F = mg</Txt><Arrow x={570} y={FLOOR-190} dx={0} dy={90} /><Txt x={590} y={FLOOR-130} size={26}>mg</Txt><path d={`M460 ${FLOOR} V${FLOOR-190}`} stroke={T.accent} strokeWidth={3} strokeDasharray="12 8"/><path d={`M446 ${FLOOR} H474 M446 ${FLOOR-190} H474`} stroke={T.accent} strokeWidth={3}/><Txt x={405} y={FLOOR-90} size={26}>h</Txt><rect x={500} y={FLOOR-110} width={140} height={110} rx={6} fill="none" stroke={T.muted} strokeWidth={2} strokeDasharray="8 8"/></g></FlatGroup></Stage><Paper s={s} t={t}/></>;
  const o={x:420,y:FLOOR-100},L=300,hx=o.x+L*C30,hy=o.y-L*S30;const p=clamp((t-comp)/.7),q=clamp((t-perp)/.7);
  return <><Stage><Txt x={35} y={35}>Rope at an angle θ to the motion · triangle not to scale</Txt><FlatGroup><Floor/><Box x={80}/><Arrow x={220} y={FLOOR-90} dx={150*C30} dy={-150*S30} accent width={5}/><Txt x={225+150*C30} y={FLOOR-90-150*S30-8} size={26}>F</Txt><path d={`M${220+50} ${FLOOR-90} A50 50 0 0 0 ${220+50*C30} ${FLOOR-90-50*S30}`} fill="none" stroke={T.muted} strokeWidth={2}/><Txt x={300} y={FLOOR-82} size={22} fill={T.muted}>θ</Txt><Arrow x={100} y={FLOOR+40} dx={200} dy={0} muted/><Txt x={130} y={FLOOR+90} size={24} fill={T.muted}>motion</Txt>
   <path d={`M${o.x} ${o.y} L${hx} ${hy}`} stroke={T.accent} strokeWidth={5} fill="none" markerEnd="url(#wk-green)"/><Txt x={(o.x+hx)/2-30} y={(o.y+hy)/2-24} size={28}>F</Txt><path d={`M${o.x+70} ${o.y} A70 70 0 0 0 ${o.x+70*C30} ${o.y-70*S30}`} fill="none" stroke={T.text} strokeWidth={2}/><Txt x={o.x+78} y={o.y-8} size={24}>θ</Txt>
   {t>=comp&&<><path d={`M${o.x} ${o.y} H${hx}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-p} fill="none"/><Txt x={o.x+40} y={o.y+42} size={26}>F cos θ · does the work</Txt></>}
   {t>=perp&&<><path d={`M${hx} ${o.y} V${hy}`} stroke={T.text} strokeWidth={4} strokeDasharray="8 7" pathLength={1} strokeDashoffset={1-q} fill="none"/><Txt x={hx-200} y={hy-18} size={26}>F sin θ · no work</Txt></>}
  </FlatGroup></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='problem'){const rope=t>=at(s,'rope');return <><Stage><Txt x={35} y={35}>Rough ramp · constant speed · rope along the ramp</Txt><RampGroup><Ramp/><Crate s={S0}/><Forces s={S0} rope={rope} ropeLabel="P" weightLabel="mg = 40 N" friction={rope} frictionLabel="f" R={rope}/><DistMarker label="d = 5 m" accent={b?.id==='crate'}/><RiseMarker label="h" accent={b?.id==='think'}/></RampGroup><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='friction'){const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const form=at(s,'formula'),sl=at(s,'sliding');const sPos=climb(s,t,form,at(s,'answer'));
  return <><Stage><Txt x={35} y={35} size={26}>{t>=form?'Friction acts along the whole 5 m':t>=sl?'Moving, so friction is at its limit':'Perpendicular to the ramp: R balances mg cos θ'}</Txt><RampGroup><Ramp/><Crate s={sPos}/><Forces s={sPos} rope R Rlabel={dn('subR')?'R = 34.6 N':'R'} accentR={t<sl} weight={t<form} into={dn('subR')&&t<sl} weightLabel="mg = 40 N" friction={t>=sl} frictionLabel={dn('subf')&&sPos>=S0+100?'f = 8.66 N':'f'} accentF={t>=sl} accentRope={false}/><DistMarker label="d = 5 m" accent={t>=form}/></RampGroup>{t<sl&&<WeightTri t={t} mgAt={at(s,'perp')} intoAt={at(s,'into')} value={dn('subR')}/>}<Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='gravity'){const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const hgt=at(s,'height');
  return <><Stage><Txt x={35} y={35} size={26}>{t>=at(s,'meaning')?'Constant speed, yet the rope did both jobs':'Gravity cares about the rise, not the ramp distance'}</Txt><RampGroup><Ramp/><Crate s={S1}/><Forces s={S1} rope={t>=at(s,'meaning')} ropeLabel="P" friction={t>=at(s,'meaning')} frictionLabel="f" R={false} weightLabel="mg = 40 N"/><DistMarker label="d = 5 m" accent={t<hgt+.5}/><RiseMarker label="h" accent={t>=hgt}/></RampGroup><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const dn=(id:string)=>s.cues[id]!==undefined&&t>=s.beats.find(b=>b.id===id)!.penEnd;
 return <><Stage><Txt x={35} y={35}>Smooth ramp: no friction, same rise</Txt><RampGroup><Ramp smooth/><Crate s={S1}/><Forces s={S1} rope ropeLabel="P" friction={false} weightLabel="mg = 40 N"/><DistMarker label="d = 5 m"/><RiseMarker label="h" accent/></RampGroup><Values s={s} t={t}/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsWorkFable:React.FC<MechanicsWorkFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
