import React from 'react';
import transcript from '../public/transcripts/mechanics/energy-fable.json';
import {Lesson,Scene,Figure,Caption,T,at,clamp,currentBeat,duration} from './mechanics-m42/Presentation';
import {HandwrittenLine,prepareLine} from './mechanics-fable/energy-fable/Ink';
const scenes=transcript.scenes as unknown as Scene[];
export type MechanicsEnergyFableProps={audioEnabled?:boolean;audit?:boolean};
export const getMechanicsEnergyFableDuration=(fps:number)=>duration(scenes,fps);
/* Hill road in stage coordinates (930×810 svg at 80,205): flat at y=600, a straight climb rising 3 m (80 px/m) to y=360, flat again at the top. Speeds at 16 px per m/s. */
const Y0=600,Y1=360,X0=40,X1=330,X2=620,X3=890,PXV=16;
const L1=X1-X0,L2=Math.hypot(X2-X1,Y0-Y1),L3=X3-X2,LT=L1+L2+L3,ANG=Math.atan2(Y0-Y1,X2-X1)*180/Math.PI;
/* Position along the road for a progress fraction p (0 = start of the flat, 1 = end of the top). */
const road=(p:number)=>{const d=clamp(p)*LT;if(d<=L1)return {x:X0+d,y:Y0,a:0};if(d<=L1+L2){const q=(d-L1)/L2;return {x:X1+(X2-X1)*q,y:Y0-(Y0-Y1)*q,a:-ANG};}return {x:X2+(d-L1-L2),y:Y1,a:0};};
const PSTART=.62*L1/LT,PTOP=(L1+L2+.38*L3)/LT;
const Txt:React.FC<{x:number;y:number;children:React.ReactNode;size?:number;fill?:string;anchor?:'start'|'end'|'middle'}>=({x,y,children,size=28,fill=T.text,anchor='start'})=><text data-label="true" x={x} y={y} fill={fill} fontSize={size} textAnchor={anchor}>{children}</text>;
/* Arrow from (x,y) along (dx,dy); four small label rects follow the shaft so a diagonal arrow's collision box is tight. */
const Arrow:React.FC<{x:number;y:number;dx:number;dy:number;accent?:boolean;width?:number;muted?:boolean}>=({x,y,dx,dy,accent=false,width=4,muted=false})=><g data-force-arrow="true">{[0,1,2,3].map(i=>{const ax=x+dx*(i+.03)/4,ay=y+dy*(i+.03)/4,bx=x+dx*(i+.97)/4,by=y+dy*(i+.97)/4,w=Math.max(8,Math.abs(bx-ax)),h=Math.max(8,Math.abs(by-ay));return <rect key={i} data-label="true" x={(ax+bx)/2-w/2} y={(ay+by)/2-h/2} width={w} height={h} fill="none" stroke="none"/>;})}<path d={`M${x} ${y} l${dx} ${dy}`} stroke={muted?T.muted:accent?T.accent:T.text} strokeWidth={width} fill="none" markerEnd={muted?'url(#en-muted)':accent?'url(#en-green)':'url(#en-white)'}/></g>;
/* Thin collision boxes along a segment so outlines and markers take part in the audit. */
const Guard:React.FC<{a:{x:number;y:number};b:{x:number;y:number};parts?:number}>=({a,b,parts=6})=><g>{Array.from({length:parts},(_,i)=>{const p={x:a.x+(b.x-a.x)*i/parts,y:a.y+(b.y-a.y)*i/parts},q={x:a.x+(b.x-a.x)*(i+1)/parts,y:a.y+(b.y-a.y)*(i+1)/parts};return <rect key={i} data-label="true" x={Math.min(p.x,q.x)-3} y={Math.min(p.y,q.y)-3} width={Math.abs(q.x-p.x)+6} height={Math.abs(q.y-p.y)+6} fill="none" stroke="none"><title>·guard</title></rect>;})}</g>;
const Stage:React.FC<{children:React.ReactNode}>=({children})=><svg data-region="diagram" data-visual="diagram" width={930} height={810} style={{position:'absolute',left:80,top:205}}><defs>{[['en-white',T.text],['en-green',T.accent],['en-muted',T.muted]].map(([id,c])=><marker key={id} id={id} markerWidth={10} markerHeight={10} refX={9} refY={5} orient="auto"><path d="M1 1 L9 5 L1 9" fill="none" stroke={c} strokeWidth={1.5}/></marker>)}</defs>{children}</svg>;
const Note:React.FC<{text:string;tick?:boolean}>=({text,tick=false})=><svg data-region="caption" width={790} height={220} style={{position:'absolute',left:1040,top:435}}>{tick&&<text x={20} y={85} fontSize={30} fill={T.accent}>✓</text>}<Caption x={tick?72:24} y={85} text={text}/></svg>;
const UNDERLINE=['formula','factor','answer','simplify','convert','whatif'];
const Paper:React.FC<{s:Scene;t:number}>=({s,t})=>{const bs=s.beats.filter(b=>b.ink);return <svg data-region="paper" data-visual="paper" width={800} height={770} style={{position:'absolute',left:1040,top:210}}><rect width={800} height={770} rx={12} fill={T.paper}/>{Array.from({length:10},(_,i)=><line key={i} x1={30} x2={770} y1={105+i*65} y2={105+i*65} stroke={T.grid}/>)}{bs.map((b,i)=>{const size=Math.min(36,718/prepareLine(b.ink!,1).width),y=52+i*(bs.length>5?113:135);return t>=b.cue?<g key={b.id}><HandwrittenLine text={b.ink!} x={38} y={y} size={size} frame={t*30} start={b.cue*30} end={b.penEnd*30}/>{UNDERLINE.includes(b.id)&&(b.id!=='formula'||['ke','gpe'].includes(s.mode))&&t>=b.penEnd&&<path d={`M38 ${y+53} Q360 ${y+68} ${38+prepareLine(b.ink!,size).width} ${y+53}`} fill="none" stroke={T.accent} strokeWidth={4}/>}</g>:null;})}</svg>;};
/* The hill: bottom road, straight climb, top road; hatching under the surface; guards along every edge. */
const Hill:React.FC<{datum?:boolean;datumLabel?:string}>=({datum=false,datumLabel='zero level'})=><g><path d={`M${X0} ${Y0} H${X1} L${X2} ${Y1} H${X3} V${Y0+60} H${X0} Z`} fill="#2b3a35" stroke="none"/><path d={`M${X0} ${Y0} H${X1} L${X2} ${Y1} H${X3}`} fill="none" stroke={T.text} strokeWidth={4}/><Guard a={{x:X0,y:Y0}} b={{x:X1,y:Y0}} parts={5}/><Guard a={{x:X1,y:Y0}} b={{x:X2,y:Y1}} parts={8}/><Guard a={{x:X2,y:Y1}} b={{x:X3,y:Y1}} parts={5}/>{datum&&<><path d={`M${X1} ${Y0} H${X3}`} stroke={T.muted} strokeWidth={2} strokeDasharray="8 8"/><Txt x={X3-8} y={Y0+32} size={22} fill={T.muted} anchor="end">{datumLabel}</Txt></>}</g>;
const Cyclist:React.FC<{p:number;muted?:boolean;id?:string}>=({p,muted=false,id='cyclist'})=>{const r=road(p);return <g data-visual={id} data-cyclist-p={p} transform={`translate(${r.x} ${r.y}) rotate(${r.a})`} opacity={muted?.35:1}><circle cx={-45} cy={-24} r={24} fill="none" stroke={T.text} strokeWidth={5}/><circle cx={45} cy={-24} r={24} fill="none" stroke={T.text} strokeWidth={5}/><path d="M-45 -24 L-10 -70 L38 -70 L45 -24 M-10 -70 L5 -30 L45 -24 M5 -30 L-45 -24" fill="none" stroke={T.accent} strokeWidth={5} strokeLinejoin="round"/><path d="M-6 -66 L-14 -100 L18 -118 M-14 -100 L28 -90 L40 -74" fill="none" stroke={T.text} strokeWidth={7} strokeLinecap="round"/><circle cx={26} cy={-130} r={13} fill={T.text}/></g>;};
/* Speed arrow ahead of the rider along the road, length from the speed. */
const SpeedArrow:React.FC<{p:number;v:number;label?:string;accent?:boolean;figure?:string}>=({p,v,label,accent=true,figure})=>{const r=road(p);const a=r.a*Math.PI/180,ux=Math.cos(a),uy=Math.sin(a);const x=r.x+ux*70-uy*(-95),y=r.y+uy*70+ux*(-95);const len=v*PXV;return <g><Arrow x={x} y={y} dx={ux*len} dy={uy*len} accent={accent} width={5}/>{label&&(figure?(x+len+180>930?<Figure id={figure} x={x+len-160} y={y+44} size={26}>{label}</Figure>:<Figure id={figure} x={x+10} y={y-62} size={26}>{label}</Figure>):<Txt x={x+10} y={y+34} size={26}>{label}</Txt>)}</g>;};
const HeightMarker:React.FC<{label:string;accent?:boolean}>=({label,accent=false})=>{const x=860;return <g><path d={`M${x} ${Y1} V${Y0}`} stroke={accent?T.accent:T.muted} strokeWidth={3} strokeDasharray="12 8"/><path d={`M${x-12} ${Y1} H${x+12} M${x-12} ${Y0} H${x+12}`} stroke={accent?T.accent:T.muted} strokeWidth={3}/><Guard a={{x,y:Y1}} b={{x,y:Y0}}/><Figure id="hFig" x={x-150} y={(Y0+Y1)/2+9} size={26}>{label}</Figure></g>;};
const Values:React.FC<{s:Scene;t:number}>=({s,t})=>{
 const m=s.mode;const done=(id:string)=>{const b=s.beats.find(b=>b.id===id);return !!b&&t>=b.penEnd;};
 const mass=m==='mass'?done('answer')?'m = 100 kg':'m = ?':['gpework','closing'].includes(m)?'m = 100 kg':'m = ?';
 const ke=m==='mass'?done('convert')?'ΔKE = 2400 J':'ΔKE = 2.4 kJ':['gpework','closing'].includes(m)?'ΔKE = 2400 J':'ΔKE = 2.4 kJ';
 const gpe=m==='gpework'?done('answer')?'ΔGPE = 3000 J':'ΔGPE = ?':m==='closing'?done('whatif')?'ΔGPE = −3000 J':'ΔGPE = 3000 J':'ΔGPE = ?';
 const h=m==='closing'&&t>=at(s,'whatif')?'Δh = −3 m':'Δh = 3 m';
 return <g><path d="M35 728 H895" stroke={T.muted} strokeWidth={1}/><Figure id="mass" x={45} y={762} size={26}>{mass}</Figure><Figure id="u" x={245} y={762} size={26}>u = 4 m s⁻¹</Figure><Figure id="v" x={470} y={762} size={26}>v = 8 m s⁻¹</Figure><Figure id="gravity" x={695} y={762} size={26}>g = 10 m s⁻²</Figure><Figure id="h" x={45} y={800} size={26}>{h}</Figure><Figure id="ke" x={245} y={800} size={26}>{ke}</Figure><Figure id="gpe" x={520} y={800} size={26}>{gpe}</Figure></g>;};
const Problem:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);const lines=['Cyclist + bicycle, mass m: 4 m s⁻¹ on the flat.','Climbs 3 m; reaches the top at 8 m s⁻¹; KE gain 2.4 kJ.','g = 10. Find m and the gain in GPE.'];const active=b?.id==='who'?0:b?.id==='hill'?1:2;return <svg data-region="problem" width={800} height={630} style={{position:'absolute',left:1040,top:290}}><rect width={800} height={590} rx={12} fill={T.paper}/>{lines.map((x,i)=><g key={x}><Txt x={30} y={120+i*150} fill={T.ink} size={29}>{x}</Txt>{b&&i===active&&<path d={`M30 ${138+i*150} H770`} stroke={T.accent} strokeWidth={3} pathLength={1} strokeDasharray={1} strokeDashoffset={1-clamp((t-b.cue)/.5)}/>}</g>)}</svg>;};
/* Narration time with the inserted holds removed, so motion stays continuous across pauses. */
const active=(s:Scene,v:number)=>v-s.holds.reduce((k,h)=>k+Math.max(0,Math.min(v,h.end)-h.start),0);
const ride=(s:Scene,t:number,from:number,to:number,p0=PSTART,p1=PTOP)=>p0+(p1-p0)*clamp((active(s,t)-active(s,from))/Math.max(.5,active(s,to)-active(s,from)));
/* Flat road with a car for the kinetic-energy scenes. */
const FLOOR=600;
const Road:React.FC<{x0?:number;x1?:number}>=({x0=40,x1=890})=><g><path d={`M${x0} ${FLOOR} H${x1}`} stroke={T.text} strokeWidth={4}/><Guard a={{x:x0,y:FLOOR}} b={{x:x1,y:FLOOR}} parts={10}/>{Array.from({length:Math.floor((x1-x0)/60)},(_,i)=><path key={i} d={`M${x0+30+i*60} ${FLOOR+4} l-8 14`} stroke={T.muted} strokeWidth={2}/>)}</g>;
const Car:React.FC<{x:number;muted?:boolean;id?:string}>=({x,muted=false,id='car'})=><g data-visual={id} data-car-x={x} transform={`translate(${x} ${FLOOR}) scale(1.5)`} opacity={muted?.35:1}><path d="M-120 -30 L-100 -70 L-40 -70 L-10 -110 L70 -110 L100 -70 L130 -60 L130 -30 Z" fill="#8a3b3b" stroke={T.text} strokeWidth={4} strokeLinejoin="round"/><path d="M-36 -72 L-12 -104 L60 -104 L80 -72 Z" fill="#2a3436"/><circle cx={-70} cy={-28} r={26} fill="#1d2326" stroke={T.text} strokeWidth={5}/><circle cx={80} cy={-28} r={26} fill="#1d2326" stroke={T.text} strokeWidth={5}/></g>;
const Box:React.FC<{y:number}>=({y})=><g data-visual="box" data-box-y={y}><rect x={300} y={y-150} width={200} height={150} rx={8} fill="#6b5237" stroke={T.text} strokeWidth={4}/><path d={`M316 ${y-75} H484 M316 ${y-110} H484`} stroke="#4a3624" strokeWidth={3}/></g>;
const Content:React.FC<{s:Scene;t:number}>=({s,t})=>{const b=currentBeat(s,t);
 if(s.mode==='opening')return <><Stage><Hill/><Cyclist p={PTOP-.12}/><SpeedArrow p={PTOP-.12} v={6}/><HeightMarker label="height"/></Stage>{b?.id.startsWith('outcome')?<Note text={b.caption!}/>:<svg data-region="syllabus" width={800} height={430} style={{position:'absolute',left:1040,top:315}}><rect width={800} height={390} rx={12} fill={T.paper}/><Txt x={35} y={65} size={27} fill={T.ink}>Syllabus 4.5 · excerpt · p.33</Txt><Txt x={35} y={185} size={38} fill={T.ink}>“gravitational potential energy”</Txt><Txt x={35} y={260} size={27} fill={T.ink}>…and kinetic energy, the energy of motion.</Txt></svg>}</>;
 if(s.mode==='story'){const flat=at(s,'flat'),climb=at(s,'climb'),top=at(s,'top'),q=at(s,'question');
  const p=t<climb?PSTART*.3+(PSTART-PSTART*.3)*clamp((active(s,t)-active(s,flat))/Math.max(.5,active(s,climb)-active(s,flat))):ride(s,t,climb,top);
  const v=t<climb?4:4+4*clamp((p-PSTART)/(PTOP-PSTART));
  const caption=t>=q?'Higher and faster: two kinds of energy':t>=top?'At the top: higher, and faster':t>=climb?'Climbing the hill, and speeding up':'Riding along the flat: energy of motion';
  return <><Stage><Hill datum={t>=top}/><Cyclist p={p}/><SpeedArrow p={p} v={v}/>{t>=top&&<HeightMarker label="higher" accent/>}<Caption x={60} y={792} text={caption}/></Stage></>;}
 if(s.mode==='ke'){const car=at(s,'car'),answer=at(s,'answer'),square=at(s,'square');const x=260+220*clamp((t-car)/3);const boost=t>=square?1+clamp((t-square)/1.2):1;
  return <><Stage><Txt x={35} y={35}>{t>=square?'Speed is squared: double it, four times the energy':t>=at(s,'scalar')?'Kinetic energy is a scalar, never negative':'A moving car has kinetic energy'}</Txt><Road/><Car x={x}/><Figure id="carMass" x={x-150} y={FLOOR+62} size={28}>m = 1500 kg</Figure><Arrow x={x-90} y={FLOOR-250} dx={20*PXV*boost*.6} dy={0} accent width={6}/><Figure id="carV" x={x-90} y={FLOOR-272} size={28}>{t>=square?'2v':'v = 20 m s⁻¹'}</Figure>{t>=answer&&<Figure id="carKE" x={x-150} y={FLOOR+104} size={28}>KE = 300 000 J</Figure>}{t>=square&&<Txt x={x-90} y={FLOOR-310} size={26} fill={T.accent}>KE × 4</Txt>}</Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='delta'){const sign=at(s,'sign');const slow=t>=sign;
  return <><Stage><Txt x={35} y={35}>{slow?'Slowing down: v < u, kinetic energy is lost':t>=at(s,'warning')?'Square each speed first, then subtract':'Speed changes from u to v'}</Txt><Road/><Car x={235} muted id="carBefore"/><Arrow x={150} y={FLOOR-250} dx={(slow?10:6)*PXV} dy={0} muted width={6}/><Txt x={150} y={FLOOR-272} size={28} fill={T.muted}>u</Txt><Txt x={150} y={FLOOR+62} size={26} fill={T.muted}>before</Txt><Car x={700}/><Arrow x={615} y={FLOOR-250} dx={(slow?6:12)*PXV} dy={0} accent width={6}/><Txt x={615} y={FLOOR-272} size={28}>v</Txt><Txt x={615} y={FLOOR+62} size={26}>after</Txt><Arrow x={438} y={FLOOR-70} dx={70} dy={0} muted width={3}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='gpe'){const lift=at(s,'lift'),level=at(s,'level'),both=at(s,'both');const up=clamp((t-lift)/2.5),down=t>=both?clamp((t-both)/2.5):0;const y=FLOOR-260*up+260*down*.6;
  return <><Stage><Txt x={35} y={35}>{t>=both?'Up: gains GPE · down: loses GPE':t>=level?'Choose the zero level; measure height from it':'Lifting a box to height h: work against gravity'}</Txt><Road x0={40} x1={890}/>{t>=level&&<Txt x={860} y={FLOOR+34} size={24} fill={T.muted} anchor="end">zero level · GPE = 0</Txt>}<Box y={y}/><Arrow x={400} y={y-150} dx={0} dy={-100} accent width={6}/><Txt x={425} y={y-215} size={28}>F = mg</Txt><Arrow x={400} y={y} dx={0} dy={100} width={5}/><Txt x={425} y={y+80} size={28}>mg</Txt>{up>=1&&<><path d={`M220 ${FLOOR} V${y}`} stroke={T.accent} strokeWidth={3} strokeDasharray="12 8"/><path d={`M206 ${FLOOR} H234 M206 ${y} H234`} stroke={T.accent} strokeWidth={3}/><Guard a={{x:220,y:FLOOR}} b={{x:220,y}}/><Txt x={170} y={(FLOOR+y)/2+10} size={28}>h</Txt></>}{t>=both&&<Arrow x={620} y={y-170} dx={0} dy={130} muted width={3}/>}</Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='problem'){const hill=t>=at(s,'hill');return <><Stage><Txt x={35} y={35}>Cyclist climbs a 3 m hill, 4 m s⁻¹ to 8 m s⁻¹</Txt><Hill datum datumLabel="zero level"/><Cyclist p={PSTART}/><SpeedArrow p={PSTART} v={4} label="u = 4 m s⁻¹" figure="uFig"/><Figure id="mFig" x={road(PSTART).x-40} y={Y0+60} size={26}>m = ?</Figure>{hill&&<><Cyclist p={PTOP} muted id="cyclistTop"/><SpeedArrow p={PTOP} v={8} label="v = 8 m s⁻¹" figure="vFig"/><Figure id="keFig" x={X2+10} y={Y1+50} size={26}>KE gain 2.4 kJ</Figure></>}<HeightMarker label="Δh = 3 m" accent={b?.id==='hill'}/><Values s={s} t={t}/></Stage><Problem s={s} t={t}/></>;}
 if(s.mode==='mass'){const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const p=ride(s,t,at(s,'substitute'),at(s,'answer'));const v=4+4*clamp((p-PSTART)/(PTOP-PSTART));
  return <><Stage><Txt x={35} y={35} size={26}>{dn('answer')?'Mass found from the change in kinetic energy':'Change in kinetic energy has the mass in it'}</Txt><Hill datum/>{p>PSTART+.02&&<Cyclist p={PSTART} muted id="cyclistStart"/>}<SpeedArrow p={PSTART} v={4} label="u = 4 m s⁻¹" figure="uFig" accent={p<=PSTART+.02}/>{p<PTOP-.02&&<Cyclist p={PTOP} muted id="cyclistTop"/>}<SpeedArrow p={PTOP} v={8} label="v = 8 m s⁻¹" figure="vFig" accent={p>=PTOP-.02}/><Cyclist p={p}/>{p>.40&&p<PTOP-.02&&<SpeedArrow p={p} v={v}/>}<Figure id="mFig" x={road(p).x-40} y={p<PTOP-.2?Y0+60:Y1-150} size={26}>{dn('answer')?'m = 100 kg':'m = ?'}</Figure><Figure id="keFig" x={X2+10} y={Y1+50} size={26}>{dn('convert')?'KE gain 2400 J':'KE gain 2.4 kJ'}</Figure><HeightMarker label="Δh = 3 m"/><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 if(s.mode==='gpework'){const dn=(id:string)=>t>=s.beats.find(b=>b.id===id)!.penEnd;const meaning=t>=at(s,'meaning');
  return <><Stage><Txt x={35} y={35} size={26}>{meaning?'At the top: more GPE and more KE, at the same time':'Gain in GPE comes from the gain in height'}</Txt><Hill datum/><Cyclist p={PTOP}/><SpeedArrow p={PTOP} v={8} label="v = 8 m s⁻¹" figure="vFig"/><Figure id="mFig" x={road(PTOP).x-40} y={Y1-150} size={26}>m = 100 kg</Figure><Figure id="keFig" x={X2+10} y={Y1+50} size={26}>KE gain 2400 J</Figure>{t>=at(s,'answer')&&<Figure id="gpeFig" x={X2+10} y={Y1+90} size={26}>GPE gain 3000 J</Figure>}<HeightMarker label="Δh = 3 m" accent={!dn('answer')}/><Values s={s} t={t}/></Stage><Paper s={s} t={t}/></>;}
 const dn=(id:string)=>s.cues[id]!==undefined&&t>=s.beats.find(b=>b.id===id)!.penEnd;const w=at(s,'whatif');const p=t>=w?PTOP-(PTOP-PSTART)*clamp((active(s,t)-active(s,w))/Math.max(1,active(s,s.beats.find(b=>b.id==='whatif')!.penEnd)-active(s,w))):PTOP;
 return <><Stage><Txt x={35} y={35} size={26}>Rolling back down: the height change is negative</Txt><Hill datum/><Cyclist p={p}/><Figure id="mFig" x={road(p).x-40} y={p<PTOP-.2?Y0+60:Y1-150} size={26}>m = 100 kg</Figure>{t>=w&&<Figure id="gpeFig" x={60} y={Y0+100} size={26}>GPE change −3000 J</Figure>}<HeightMarker label={t>=w?'Δh = −3 m':'Δh = 3 m'} accent={t>=w}/><Values s={s} t={t}/></Stage>{b?.caption?<Note text={b.caption} tick/>:<Paper s={s} t={t}/>}</>;
};
export const MechanicsEnergyFable:React.FC<MechanicsEnergyFableProps>=props=><Lesson scenes={scenes} content={Content} {...props}/>;
