"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered", "open", "How does a graze heal over with new skin that is still yours?"),
 ("a grazed knee heals over", "heal", "Cells at the edges divide; new cells close the gap"),
 ("gene for gene, yours", "same", "Same set of chromosomes?"),
 ("You grew by adding cells", "grow", "Growth: new cells"),
 ("the surface of your skin", "skin", "Skin surface: worn away and replaced"),
 ("lining of your gut", "gut", "Gut lining: worn away and replaced"),
 ("a strawberry plant even makes whole new plants", "straw", "A runner makes a new plant"),
 ("new cells come from a cell dividing", "divide", "Each time: one cell becomes two"),
 ("the same genetic information", "info", "New cells: the same set as the parent cell"),
 ("how the division is done", "how", "Why the same? How the division is done"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("explain why mitosis gives daughter cells", "l1", ""),
 ("from two events in the cell cycle", "l1b", ""),
 ("why that matters for growth", "l2", ""),
],
3: [
 ("Two things you have met already", "open", "Recall: the cell cycle (5.1.3)"),
 ("the S phase of interphase", "s", "S (synthesis) phase of interphase"),
 ("is replicated", "rep", "DNA replicated during S"),
 ("When that is complete", "done", "Replication complete: 4 chromosomes, 8 DNA molecules"),
 ("two sister chromatids joined at the centromere", "sisters", "Two sister chromatids, one centromere"),
 ("one is a copy of the other", "copy", "Gene bands: the same on both sisters"),
 ("they carry the same genes", "genes", ""),
 ("Second, from mitosis", "mit", "Recall: mitosis (5.2.1), metaphase"),
 ("the centromeres divide", "divide", "Centromeres divide: 8 daughter chromosomes"),
 ("separate to opposite poles", "poles", "Daughter chromosomes move to opposite poles"),
 ("each pole receives one from every chromosome", "each", "Each pole: one of every chromosome"),
],
4: [
 ("Replication made two identical copies", "copy", "Copy: replication in S phase"),
 ("separation sent one copy of each", "share", "Share: separation in anaphase"),
 ("each new nucleus holds one copy", "nuclei", "Two new nuclei form"),
 ("the same number as the parent nucleus", "same", "4 in each new nucleus = 4 in the parent"),
 ("the same genetic information", "info", "Same genetic information"),
 ("unless a copying error has occurred", "err", ""),
 ("Cytokinesis then divides the cytoplasm", "cyto", "Cytokinesis: the cytoplasm divides"),
 ("two genetically identical daughter cells", "cards", "Two genetically identical daughter cells"),
 ("four chromosomes each in our model", "four", "Model cell: 4 per daughter cell"),
 ("forty-six in a typical diploid human somatic cell", "human", "Typical diploid human somatic cell: 46"),
 ("copy, then share one of each", "handle", "Handle: copy, then share one of each"),
 ("Copy: replication in the S phase", "hc", "Copy → replication in the S phase"),   # run 009g hook links
 ("two identical sister chromatids of every chromosome", "hct", "Copy → two identical sister chromatids"),
 ("Share one of each: separation in anaphase", "hs", "Share one of each → separation in anaphase"),
 ("go to opposite poles", "hst", "Share one of each → one of each to each pole"),
 ("Written properly", "wp", "Written properly"),
 ("replication makes identical sister chromatids", "c1", ""),
 ("gives each daughter nucleus one copy", "c2", ""),
],
5: [
 ("Here is an answer that would lose the marks", "open", "EXAM CONTRAST: an answer that would lose the marks"),
 ("Our framing of a November 2022 question", "q", "Our framing of a real question"),
 ("Read this answer", "card", "Read the answer. What is missing?"),
 ("Look at the whole line", "line", "The whole line"),
 ("Nothing in it is false", "true", "True, but…"),
 ("it echoes the syllabus wording", "syl", "It echoes the syllabus wording"),
 ("it restates the result", "result", "It restates the result the question gives"),
 ("That paper asked for two events", "demand", "The demand: two events, 3 marks"),
 ("crediting points such as identical sister chromatids", "examples", "Examples of credited points"),
 ("None of those points is in this line", "none", "None of them is in the answer"),
 ("it names no event", "slots", "No event named"),
 ("how the identical copies are made", "made", "How are the copies made?"),
 ("how they are shared out", "shared", "How are they shared out?"),
 ("DNA is replicated in the S phase of interphase", "fix", "Event 1: DNA replicated in S phase"),
 ("in anaphase they separate to opposite poles", "ana", "Event 2: sister chromatids separate to opposite poles"),
 ("each daughter nucleus receives", "tel", "Each daughter nucleus: one copy of every chromosome"),
 ("one copy of every chromosome$", "done", "One sufficient answer: two events, three credited points"),
],
6: [
 ("why does identical matter", "open", "Why does identical matter? Growth"),
 ("Just behind the tip of a root", "root", "Root tip: region of cell division behind the root cap"),
 ("cells divide by mitosis, supplying new cells", "div", "Cells divide by mitosis"),
 ("the root lengthens", "long", "The root lengthens"),
 ("also elongate", "elong", "New cells also elongate"),
 ("not by division alone", "both", "Division and elongation"),
 ("Your own tissues grew", "human", "Growing tissues"),
 ("Each new cell carries the same genes", "cards", "New cells: the same set as the parent cell"),
 ("a growing tissue is built of cells", "light", ""),
],
7: [
 ("Replacement goes on all the time", "open", "Replacement"),
 ("The outer layer of your skin", "skin", "Outer layer of skin"),
 ("lining of your small intestine", "gut", "Small-intestine lining"),
 ("continually worn away", "lost", "Surface cells worn away"),
 ("typically replaced by cells made by mitosis", "repl", "Replaced by cells made by mitosis"),
 ("the same genetic information as the cells they replace", "cards", "Same set when the daughter cells form"),
 ("Repair is replacement after damage", "repair", "Repair: a skin cut"),
 ("mitosis supplies replacement cells", "close", "Cells at the edges divide and close the gap"),
 ("the daughter cells then differentiate", "diff", "Daughter cells differentiate where needed"),
 ("The same genes don't by themselves decide", "genes", "Same genes, different specialised type"),
 ("some cells specialise and stop dividing", "stop", "Some cells specialise and stop dividing"),
 ("a mature human red blood cell", "rbc", "Mature human red blood cell: no nucleus"),
 ("Which cells do the dividing?", "which", "Which cells do the dividing?"),
 ("Stem cells, next", "next", "Next: 5.1.5 stem cells"),
],
8: [
 ("Last, asexual reproduction", "open", "Asexual reproduction"),
 ("sends out runners", "runner", "A runner grows along the ground"),
 ("touches the soil", "soil", "Where it touches the soil, roots grow"),
 ("a new plantlet roots and grows", "plantlet", "A new plantlet"),
 ("produced by mitosis from the parent's cells", "mit", "Its cells: made by mitosis"),
 ("genetically identical to its parent", "same", "Same set as the parent plant"),
 ("a clone, from one parent alone", "clone", "A clone of one parent"),
],
9: [
 ("So here it is", "open", "What I told you, on the diagram you built"),
 ("on the diagram you built", "settle", ""),
 ("makes identical sister chromatids", "l1", "Copy: identical sister chromatids"),
 ("one copy of every chromosome", "l2", "Share: one copy of every chromosome per nucleus"),
 ("the daughter cells are genetically identical", "sent", "Genetically identical daughter cells"),
 ("Growth, replacement, repair", "panels", "Growth · replacement · repair · asexual reproduction"),
 ("And the grazed knee?", "knee", "The grazed knee"),
 ("they carry your genes", "genes", "New cells by mitosis: your genes"),
],
10: [
 ("How does this reach you?", "open", "How it is asked"),
 ("two events that make daughter cells genetically identical", "r1", "Two events: a real question"),
 ("three marks, any three credited points", "marks", ""),
 ("Multiple-choice items ask about the purpose of mitosis", "r2", "Purpose of mitosis: a real multiple-choice item"),
 ("its roles in growth and repair", "r3", "Growth and repair: a real multiple-choice item"),
 ("The reject card", "reject", "The reject card"),
 ("each nucleus needs one copy of every chromosome", "ring", "One copy of every chromosome"),
 ("one copy of every chromosome$", "end", ""),
],
}
