"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Beat 10's recogniser heard "2023" as words, so no Beat 10 cue contains it."""
PLANS = {
1: [
 ("Ever wondered how sugar gets into a cell", "open", "How does sugar get into a cell?"),
 ("built to keep water-loving things out", "core0", ""),
 ("trade with their surroundings", "trade", "Cells trade with their surroundings"),
 ("oxygen moves into red blood cells", "o2", "Lungs: oxygen into red blood cells"),
 ("reaches cells that use it in respiration", "glu", "Glucose reaches cells"),
 ("Water moves into and out of cells", "water", "Water moves in and out"),
 ("has a hydrophobic core", "core", "A hydrophobic core"),
 ("a polar molecule", "polar", "Glucose: polar"),
 ("So how does it get in?", "how", "So how does it get in?"),
 ("costs the cell any energy at all", "atp", "Any energy cost?"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("explain diffusion as a net movement", "l1", ""),
 ("which substances cross the bilayer directly", "l2", ""),
 ("explain osmosis in terms of water potential", "l3", ""),
],
3: [
 ("Start with the particles themselves", "open", "Particles in random motion"),
 ("constantly moving at random", "random", "Constantly moving at random"),
 ("colliding and changing direction", "collide", "Colliding, changing direction"),
 ("Put more of them on the left", "more", "More on the left"),
 ("watch the counter in the middle", "counter", "Watch the counter"),
 ("Particles cross both ways", "both", "Crossings both ways"),
 ("more cross from left to right", "lr", "More cross left to right"),
 ("a net movement, down the concentration gradient", "net", "Net movement down the gradient"),
 ("So diffusion is the net movement", "def", "Diffusion"),
],
4: [
 ("Keep watching", "open", "Keep watching"),
 ("the counts come closer", "closer", "The counts come closer"),
 ("the two numbers run level", "level", "Equal: the numbers run level"),
 ("still cross both ways", "still", "Still crossing both ways"),
 ("so the arrow fades", "fades", "No net movement"),
 ("what drove all of this", "drove", "What drove it?"),
 ("no ATP from a cell", "noatp", "No ATP used"),
 ("That is what passive means", "passive", "Passive"),
 ("cells exchange substances", "exch", "Cells exchange substances"),
 ("which substance takes which route", "routes", "Which route?"),
],
5: [
 ("Now put a membrane in the way", "open", "Put a membrane in the way"),
 ("Turn the field so the outside", "turn", "Outside at the top, cytoplasm below"),
 ("slide in a phospholipid bilayer", "slide", "A phospholipid bilayer"),
 ("a red blood cell taking up oxygen", "rbc", "Our example: a red blood cell in a lung capillary"),
 ("Here we track freely dissolved oxygen", "setup", "New setup: freely dissolved oxygen"),
 ("not oxygen bound to haemoglobin", "hb", ""),
 ("from the surrounding plasma into the cell", "hilo", ""),
 ("small and non-polar", "small", "Small and non-polar"),
 ("pass straight through the bilayer", "pass", "Straight through the bilayer"),
 ("That is simple diffusion", "simple", "Simple diffusion"),
],
6: [
 ("What makes net diffusion faster", "open", "What makes net diffusion faster?"),
 ("A steeper concentration gradient", "steep", "1 · A steeper gradient"),
 ("a bigger gap between the two counts", "gap", "A bigger gap between the counts"),
 ("A higher temperature", "temp", "2 · A higher temperature"),
 ("more kinetic energy", "ke", "More kinetic energy"),
 ("A larger surface area", "area", "3 · A larger surface area"),
 ("a shorter distance to travel", "dist", "4 · A shorter distance"),
 ("the surface-area lesson", "sa", "Calculated and tested later"),
 ("For bilayer passage", "bil", "5 · Size and lipid solubility"),
 ("No equation needed", "noeq", "Direction of each effect only"),
],
7: [
 ("Now the hook's problem", "open", "Back to the hook's problem"),
 ("made of fatty-acid tails", "tails", "Hydrophobic fatty-acid tails"),
 ("Ions are charged", "ion", "Ions: charged"),
 ("and glucose is polar", "glu", "Glucose: polar"),
 ("interact well with water", "water", "They interact well with water"),
 ("approach it and turn back", "turn", "Turned back at the core"),
 ("does not cross the hydrophobic bilayer core readily", "sent", "Needs a transport protein"),
 ("Ions need a protein route too", "prot", "A protein route"),
 ("In the passive routes shown here", "bracket", "Channel and carrier proteins"),
 ("through these proteins", "names", ""),
 ("without ATP: facilitated diffusion", "fd", "Facilitated diffusion"),
],
8: [
 ("The first is a channel protein", "open", "A channel protein"),
 ("Picture a door in a wall", "door", "Handle: a door in a wall"),
 ("Written properly", "written", "Written properly"),
 ("provides a hydrophilic pore", "pore", "A hydrophilic pore"),
 ("diffuse down their concentration gradient", "sent", ""),
 ("Watch the ions", "watch", "Watch the ions"),
 ("lined by hydrophilic parts", "lined", "Lined by hydrophilic parts"),
 ("without meeting the hydrophobic core", "count", "Down the gradient, through the pore"),
 ("A few go the other way", "few", "A few go the other way"),
 ("does not change shape", "shape", "Shape unchanged"),
 ("the pore simply stays open", "open2", "Our model: pore open"),
 ("Different channels let through", "diff", "Each channel: particular ions"),
],
9: [
 ("The second is a carrier protein", "open", "A carrier protein"),
 ("fits into a binding site", "bind", "Binds at a binding site"),
 ("The carrier changes shape", "flip", "Changes shape"),
 ("the glucose is released", "release", "Released into the cytoplasm"),
 ("returns to its first shape", "reset", "Returns to its first shape"),
 ("without ATP", "count", "Down its gradient, without ATP"),
 ("It can carry either way", "either", "Either way"),
 ("more often from the side with more glucose", "more", "More often from the side with more"),
 ("One caution", "caution", "One caution"),
 ("every glucose transporter", "every", ""),
],
10: [
 ("Here is a mistake the June", "entry", "COMMON MISTAKE: glucose 'too large'"),
 ("Our framing", "header", "Our framing of a June 2023 question"),
 ("Read this answer", "card", "Read this answer"),
 ("Look at the words too large here", "ring", "Look at these words"),
 ("bigger than an oxygen molecule", "size", "Size differs"),
 ("report on this question", "report", "What the June 2023 report says"),
 ("most incorrect answers", "most", "Of the incorrect answers"),
 ("a different property", "prop", "The credited property"),
 ("the core of the bilayer is hydrophobic", "coreh", ""),
 ("nothing for size alone", "nothing", "Nothing for size alone"),
 ("So state the property and the barrier first", "first", "Property → barrier → protein"),
 ("In place", "fix", "Corrected in place"),
 ("it needs a transport protein, such as a carrier", "last", ""),
 ("such as a carrier$", "exit", "A transport protein, such as a carrier"),
],
11: [
 ("Now water", "open", "Water has its own measure"),
 ("which has its own measure", "measure", ""),
 ("water's tendency to move", "tend", "Water's tendency to move"),
 ("Pure water at atmospheric pressure", "pure", "Pure water: the reference"),
 ("zero kilopascals", "zero", "0 kPa"),
 ("adding solute lowers the water potential", "lower", "Solute lowers water potential"),
 ("negative values", "neg", "Negative values"),
 ("a less negative value is higher", "less", "Less negative = higher"),
 ("a little solute on the left", "left", "A little solute on the left"),
 ("more on the right", "right", "More on the right"),
 ("at the start, the left side", "ll", "At the start"),
 ("the right side the lower", "rl", ""),
],
12: [
 ("Water molecules cross this membrane", "open", "Water crosses both ways"),
 ("in both directions all the time", "count", ""),
 ("in many cells, channel proteins too", "aqp", "Real cells: bilayer and channel proteins"),
 ("The sucrose here does not pass", "suc", "Sucrose does not pass"),
 ("More water molecules cross from the higher", "more", "More from the higher water potential"),
 ("a net movement to the lower side", "net", "Net movement of water"),
 ("That is osmosis", "def", "Osmosis"),
 ("through a partially permeable membrane", "ppm", ""),
 ("add solute to the left", "add", "We change the left solution"),
 ("the water potentials are equal", "equal", "Equal water potentials"),
 ("The net arrow fades", "fades", "No net movement"),
 ("water still crosses both ways", "still", "Crossings continue"),
],
13: [
 ("So here is what I told you", "open", "What I told you, on the models"),
 ("on the membrane and the water model", "settle", ""),
 ("Particles move randomly", "rand", "Random movement → net movement"),
 ("until concentrations are equal", "equal", ""),
 ("Oxygen, small and non-polar", "o2", "Simple diffusion"),
 ("Ions and polar molecules like glucose", "polar", "Not through the core readily"),
 ("Here their net movement", "fd", "Facilitated diffusion"),
 ("A channel has a hydrophilic pore", "chan", "Channel: hydrophilic pore"),
 ("a carrier binds its solute and changes shape", "carr", "Carrier: binds, changes shape"),
 ("water moves by osmosis", "osm", "Osmosis"),
 ("All three are passive", "passive", "Passive: no ATP"),
],
14: [
 ("How does this reach you?", "open", "How it is asked"),
 ("question on glucose and the membrane", "row1", "Why glucose needs a transport protein"),
 ("glucose is polar, and the core", "gp", ""),
 ("Write that first", "first", "Polarity and the core first"),
 ("A March 2024 question", "row2", "Sodium ions: the charge"),
 ("for sodium ions", "na", ""),
 ("The reject card", "reject", "The reject card"),
 ("not no movement", "notno", "No net movement, not no movement"),
 ("And the sugar?", "sugar", "And the sugar?"),
 ("a carrier, down its gradient", "carrier", "A carrier, down its gradient"),
 ("without ATP$", "exit", "Without ATP"),
],
}
