"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered", "open", "Your body holds its temperature steady"),
 ("hold its temperature steady", "steady", ""),
 ("shivering when you are cold", "shiver", "Cold: you shiver"),
 ("sweating when you are hot", "sweat", "Hot: you sweat"),
 ("catalysed by enzymes", "cell", "Inside a cell: reactions catalysed by enzymes (MODEL)"),
 ("too cool, and it runs slowly", "cool", "Too cool: slower"),
 ("the enzyme starts to lose its shape", "shape", "Too hot: the enzyme starts to lose its shape"),
 ("pH matters too", "gut", "pH matters too"),
 ("the protease in your stomach", "stomach", "Stomach: strong acid"),
 ("your small intestine", "intestine", "Small intestine: far less acidic"),
 ("Today: temperature and pH", "title", "Today: temperature and pH"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("describe how to investigate", "l1", ""),
 ("read a rate from each investigation", "l2", ""),
 ("explain both effects", "l3", ""),
],
3: [
 ("Temperature first", "rig", "The gas-syringe rig (recall: 3.1.3)"),
 ("The conical flask holds hydrogen peroxide solution", "flask", "Conical flask: hydrogen peroxide solution"),
 ("standing upright inside it", "tube", "Small tube inside: yeast suspension (catalase)"),
 ("Sealed to a gas syringe", "syringe", "Syringe at 0 cm³; tap set to vent"),
 ("the flask stands in a water bath", "bath", "Into the water bath"),
 ("The key design choice", "equil", "The key design choice"),
 ("equilibrate separately", "apart", "Enzyme and substrate apart, both warming"),
 ("for the same ten minutes", "strip", "Five separate runs, the same 10 min each"),
 ("so both are at that temperature", "zero", "Both at 30 °C, still apart"),
 ("when they meet", "baseline", "Baseline checked; tap to collect"),
 ("tilt the flask by its neck", "tilt", "Tilt by the neck: t = 0 at first contact"),
 ("the tube spills", "spill", ""),
 ("the timer starts", "timer", "The stopwatch runs from first contact"),
 ("This is not the June 2022 practical's design", "contrast", "A different experiment: S22/33 Q1(b)"),
 ("heated the enzyme mixture for five minutes", "heat5", ""),
 ("took it out of the bath", "out", ""),
 ("soaked a disc in it", "disc", ""),
 ("before the peroxide test", "test", "Heated, then taken out: not held at temperature"),
],
4: [
 ("Each run gives a progress curve", "curve", "One run: its progress curve"),
 ("For the initial rate", "early", "The first seconds"),
 ("draw the tangent at time zero", "tangent", "The tangent at t = 0"),
 ("take rise over run", "tri", "Rise over run, along the tangent"),
 ("twelve cubic centimetres in thirty seconds", "values", ""),
 ("so nought point four zero", "result", "Initial rate at 30 °C: 0.40 cm³ s⁻¹"),
 ("Take the mean of three runs", "table", "Three runs at each temperature"),
 ("plot the means", "plot", "Plot the five means"),
 ("The rate climbs", "climb", "The means climb"),
 ("its highest mean at forty degrees", "peak", "Highest mean: 40 °C"),
 ("then falls at fifty", "fall", "Lower at 50 °C"),
 ("the enzyme-free control", "control", "Enzyme-free control: no measurable gas"),
 ("has its optimum between thirty and fifty degrees", "bracket", "Optimum: between the values either side"),
 ("one enzyme's optimum, not a rule", "rule", "This catalase, this set-up"),
],
5: [
 ("To explain that graph", "open", "To explain the graph"),
 ("one sentence carries the whole lesson", "model", "One sentence carries the lesson"),
 ("The rate depends on how often", "write", ""),
 ("meet a working active site", "seat", "Substrate meets a working active site"),
 ("form enzyme–substrate complexes per unit time", "complex", "Enzyme–substrate complexes per unit time"),
 ("whether the active sites stay functional", "functional", "Do the active sites stay functional?"),
 ("Below the optimum", "below", "Below the optimum"),
 ("more kinetic energy", "ke", "Warmer: more kinetic energy"),
 ("collide more often", "collide", "More collisions"),
 ("more effective collisions", "effective", "Effective collisions form complexes"),
 ("more complexes per unit time, a higher rate", "faster", "More complexes per unit time: a higher rate"),
 ("a slow rate in the cold", "cold", "In the cold: slower"),
 ("not denatured", "notden", "At 10 °C: not denatured"),
 ("complexes simply form less often", "less", "Complexes form less often"),
],
6: [
 ("Above the optimum", "above", "Above the optimum"),
 ("the second half takes over", "second", "Do the active sites stay functional?"),
 ("hydrogen bonds and ionic bonds between R groups", "links", "Bonds between R groups hold the fold"),
 ("the molecule vibrates more", "heat", "Heating: the molecule vibrates more"),
 ("those bonds break, one after another", "break", "The bonds between R groups break"),
 ("The fold loosens", "loosen", "The fold loosens"),
 ("the active site changes shape", "distort", "The active site changes shape"),
 ("no longer complementary", "notcomp", "No longer complementary"),
 ("it rocks, and cannot seat", "fail", "The substrate cannot seat"),
 ("Think press studs, not stitches", "studs", "Press studs, not stitches (analogy only)"),
 ("heat pops the studs", "pop", ""),
 ("the stitching stays", "stitch", ""),
 ("Written properly", "proper", "Written properly"),
 ("peptide bonds do not", "backbone", "Backbone continuous: peptide bonds intact"),
 ("the enzyme is denatured", "denatured", "Denatured"),
 ("As more molecules denature", "field", "More molecules denatured"),
 ("fewer active sites are functional", "fewer", "Fewer functional active sites"),
 ("fewer complexes form per unit time", "slower", "Fewer complexes per unit time"),
 ("The particles have not lost kinetic energy", "stillfast", "Still fast: working active sites lost"),
 ("The June 2022 mark scheme credited this chain", "ms", "The credited chain: S22/33 Q1(b)(v)"),
],
7: [
 ("Now pH", "rig", "pH: the disc method (S22/33 Q1(a) design)"),
 ("mixed with a buffer solution", "pipette", "Yeast suspension + buffer solution"),
 ("which holds the chosen pH", "labels", "Each buffer holds its pH"),
 ("either side of the expected optimum", "bracket", "Five buffers, pH 5 to 9"),
 ("Identical paper discs", "punch", "Identical discs from one hole punch"),
 ("soak in each mixture", "swirl", "Mixed just before each disc"),
 ("for the same time", "soak", "Each disc soaks 60 s"),
 ("With forceps", "forceps", "Forceps rinsed, disc drained"),
 ("to the bottom of a tube of hydrogen peroxide", "down", "Down to the bottom of the peroxide"),
 ("same concentration and depth", "mark", "Same concentration, filled to the same mark"),
 ("is released", "release", "Released: the stopwatch starts"),
 ("Oxygen forms on the disc", "bubbles", "Oxygen gathers on the disc"),
 ("time it to the surface", "surface", "At the surface: stop the clock"),
 ("Fresh peroxide for every disc", "fresh", "Fresh peroxide for every disc"),
 ("a used tube can already contain enzyme", "used", "A used tube can contain enzyme"),
 ("Three whole-second times per pH", "table", "Three whole-second times per pH"),
 ("soaked in boiled enzyme", "boiled", "Control: boiled yeast suspension, same procedure"),
 ("does not rise", "norise", "The control disc stays down"),
],
8: [
 ("A shorter time means a faster reaction", "race", "Shorter time, faster reaction"),
 ("one over the mean rise time", "column", "Use 1 ÷ mean rise time"),
 ("twelve, thirteen and fourteen seconds", "ring", "pH 7.0: three readings"),
 ("give a mean of thirteen", "mean", "Mean rise time: 13 s"),
 ("one over thirteen", "recip", "1 ÷ 13 s = 0.077 s⁻¹"),
 ("a relative rate for comparing these discs", "proxy", "A relative rate, for comparing these discs"),
 ("not an initial rate", "notinit", "No progress curve here: one endpoint time per disc"),
 ("Plotted", "plot", "The five values, plotted"),
 ("the highest value is at pH eight", "peak", "Highest: pH 8.0"),
 ("lower values at seven and nine", "sides", "Lower either side: pH 7.0 and 9.0"),
 ("optimum lies between pH seven and nine", "bracket", "Optimum: between pH 7 and 9"),
],
9: [
 ("Why?", "open", "Why does pH change the rate?"),
 ("Some R groups lining the active site carry charges", "charges", "Charged R groups line the active site"),
 ("they gain or lose hydrogen ions", "ions", "Away from the optimum: H⁺ gained or lost"),
 ("The charges change", "change", "The charges change"),
 ("ionic and hydrogen bonds are altered", "altered", "Ionic and hydrogen bonds altered"),
 ("the active site changes shape", "shift", "The active site changes shape"),
 ("fewer enzyme–substrate complexes form per unit time", "fewer", "Seats less well: fewer complexes per unit time"),
 ("A modest change like this need not unfold the enzyme", "modest", "Still folded"),
 ("bring the pH back", "back", "pH back near the optimum"),
 ("activity can return", "return", "Activity can return"),
 ("At an extreme pH", "extreme", "Extreme pH"),
 ("denature it", "denatured", "Extreme pH: denatured"),
 ("the optimum is that enzyme's own", "own", "An optimum belongs to one enzyme"),
 ("a protease in a June 2024 practical", "protease", "A protease: around pH 6.1"),
],
10: [
 ("Here is the lesson", "open", "What I told you"),
 ("on the pictures you now know", "rigs", "The two investigations"),
 ("the one sentence that carried it", "sentence", "The sentence"),
 ("more kinetic energy, more effective collisions", "rise", "Below the temperature optimum"),
 ("R-group bonds break", "rbonds", "Above it: denatured"),
 ("backbone intact", "backbone", ""),
 ("charges change, and so does the active site", "ph", "Away from the pH optimum"),
 ("at extreme pH, denaturation can occur", "extreme", "Extreme pH can denature"),
],
11: [
 ("How this reaches you", "forms", "How it is asked"),
 ("run one of these investigations", "row1", ""),
 ("explain a graph or table", "row2", ""),
 ("Here is one from June 2024", "question", "The real question: 9700/32 June 2024 Q1(b)(ii)"),
 ("Read it", "read", "Read it: explain, using their data"),
 ("The mark scheme credits", "ms", "What the mark scheme credits"),
 ("around pH six point one", "ms1", ""),
 ("the active site's shape changing", "ms2", ""),
 ("more complexes up to the optimum", "ms3", ""),
 ("low activity at extreme pH", "ms4", ""),
 ("And your body", "body", "And your body"),
 ("keeps enzyme-catalysed rates steady", "steady", "A steady temperature: steady rates"),
 ("below the temperatures", "card", "Above the temperature optimum: denatured"),
 ("begin to denature", "final", ""),
],
}
