"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat.
4.1.1-2: cues containing the request-normalised word "OH" are shortened so no cue phrase includes it."""
PLANS = {
1: [
 ("Ever wondered", "open", "A cell in water"),
 ("why a cell doesn't simply mix", "hook", ""),
 ("Take a red blood cell", "rbc", "A red blood cell (schematic)"),
 ("Around it is plasma", "plasma", "Outside: plasma, a watery solution"),
 ("inside it is cytoplasm", "cyto", "Inside: cytoplasm, another watery solution"),
 ("different substances dissolved in each", "solutes", "Different substances dissolved in each"),
 ("the cell surface membrane", "membrane", "Between them: the cell surface membrane"),
 ("two layers of molecules", "layers", "Two layers of molecules"),
 ("keeps the inside and the outside separate", "separate", "Inside and outside kept separate"),
 ("controls what crosses it", "controls", "Yet the cell controls what crosses"),
 ("why does it hold together in water", "question", "Why does it hold together in water?"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("how phospholipids arrange themselves", "l1", ""),
 ("which interactions make them do it", "inter", ""),
 ("where proteins sit in that bilayer", "l2", ""),
 ("where cholesterol, glycolipids and glycoproteins sit", "l3", ""),
],
3: [
 ("Start with the molecule", "open", "The molecule the membrane is built from"),
 ("the phospholipid", "pl", "A phospholipid (recall: Topic 2 lipids)"),
 ("a head containing a phosphate group", "head", "The head: phosphate group"),
 ("polar and carries charge", "polar", "The head is polar"),
 ("two fatty-acid tails", "tails", "Two fatty-acid tails: non-polar"),
 ("Water molecules are polar too", "wpolar", "Water molecules are polar too"),
 ("form hydrogen bonds with it", "hb", "Hydrogen bonds with the head"),
 ("the head is hydrophilic", "hphil", "Hydrophilic head"),
 ("The tails can't form those interactions", "notails", "No hydrogen bonds with the tails"),
 ("they're hydrophobic", "hphob", "Hydrophobic tails"),
 ("two very different ends", "ends", "One molecule, two different ends"),
],
4: [
 ("Now scatter", "open", "Phospholipids scattered through water"),
 ("scatter lots of phospholipids through water", "scatter", ""),
 ("hydrogen bonds with each other", "wwhb", "Water keeps bonding with water"),
 ("The non-polar tails can't join in", "tailsout", "The tails can't join in"),
 ("excluded from the water and come together", "assemble", "Tails excluded from the water come together"),
 ("held there by hydrophobic interactions", "hint", "Held together: hydrophobic interactions"),
 ("the heads stay in contact with the water", "heads", "Heads stay in contact with water"),
 ("With water on both sides", "sides", "Water on both sides"),
 ("two layers", "two", "Two layers: 12 per layer in this section"),
 ("heads facing the water outside and inside", "hfaces", "Heads face the water"),
 ("tails facing each other in the middle", "tfaces", "Tails face each other"),
 ("the phospholipid bilayer", "bilayer", "The phospholipid bilayer"),
 ("the hydrophobic core", "core", "Its middle: the hydrophobic core"),
],
5: [
 ("Here's a way", "open", "The bilayer"),
 ("heads to the water, tails to each other", "handle", "Memory aid: heads to the water, tails to each other"),
 ("each other. ^Heads to the water: the heads", "l1", "Heads → the heads · water → the water on both sides"),
 ("on both sides. ^Tails to each other", "l2", "Tails → the tails · each other → they meet in the core"),
 ("face each other in the core$", "map", "The whole mapping: heads to the water, tails to each other"),
 ("a memory aid, not an exam answer", "aid", "A memory aid, not an exam answer"),
 ("Written properly", "written", "Written properly"),
 ("their hydrophilic heads interact with water on both sides", "c1", "Clause 1: heads interact with water"),
 ("held together by hydrophobic interactions", "c2", "Clause 2: tails held together"),
 ("why that matters", "why", "Why a bilayer suits a cell"),
 ("a watery compartment in watery surroundings", "compart", "Watery inside, watery outside"),
 ("our red blood cell in plasma", "rbc", "Our red blood cell in plasma"),
 ("keeps a water-based inside separate", "separate", "Inside and outside kept separate"),
 ("The proteins set into it", "next", "Next: the proteins"),
],
6: [
 ("Proteins sit in the bilayer", "open", "Proteins in the bilayer"),
 ("by the same logic", "logic", ""),
 ("Intrinsic proteins are embedded", "intrinsic", "Intrinsic proteins: embedded in the bilayer"),
 ("a channel, a carrier and a receptor", "names", "A channel, a carrier and a receptor"),
 ("they're transmembrane proteins", "trans", "These three span it: transmembrane"),
 ("Where a protein touches the tails", "midband", "Where the protein touches the tails"),
 ("hydrophobic R groups", "hphobR", "Hydrophobic R groups against the tails"),
 ("where it meets the water", "outband", "Where the protein meets the water"),
 ("it has hydrophilic R groups", "hphilR", "Hydrophilic R groups in the water"),
 ("lining a central pore", "pore", "A pore lined by hydrophilic R groups"),
 ("what that pore is for", "porerole", ""),
 ("Extrinsic proteins sit on one surface", "extrinsic", "Extrinsic protein: on one surface"),
 ("the cytoplasmic side", "cytoside", "Here: the cytoplasmic side"),
 ("attached to phospholipid heads or to an intrinsic protein", "attach", "Attached to heads or an intrinsic protein"),
],
7: [
 ("Now the name", "open", "Now the name"),
 ("fluid mosaic", "name", "Fluid mosaic"),
 ("aren't fixed in place", "fluid", "Fluid: phospholipids aren't fixed in place"),
 ("drift sideways within their own layer", "drift", "Drifting sideways within their own layer"),
 ("many of the proteins drift too, more slowly", "pdrift", "Proteins drift too, more slowly"),
 ("each molecule stays in its own layer", "own", "Each stays in its own layer (in this model)"),
 ("Mosaic, because", "mosaic", "Mosaic"),
 ("different sizes and shapes", "shapes", "Proteins of different sizes and shapes"),
 ("like tiles set in a mosaic", "tiles", "Scattered like tiles in a mosaic"),
 ("introduced in nineteen seventy-two", "1972", "The fluid mosaic model: 1972"),
 ("still being modified", "modified", "Still being modified"),
 ("a model of how the molecules are arranged", "model", "A model of the arrangement"),
],
8: [
 ("Now three more components", "open", "Three more components"),
 ("starting with cholesterol", "chol", "First: cholesterol"),
 ("In animal cell surface membranes", "animal", "In animal cell surface membranes"),
 ("in both layers", "both", "Cholesterol in both layers"),
 ("a small polar", "oh", "A small polar hydroxyl group"),
 ("a rigid ring structure that is non-polar", "ring", "A rigid, non-polar ring structure"),
 ("sits level with the phospholipid heads", "level", "Hydroxyl group level with the heads"),
 ("the rings lie among the tails", "rings", "Rings among the tails"),
 ("the same logic again", "logic", "The same logic again"),
 ("the polar part with the polar heads", "polar", "Polar with polar"),
 ("the non-polar part with the non-polar tails", "nonpolar", "Non-polar with non-polar"),
],
9: [
 ("Next, glycolipids", "open", "Next: glycolipids"),
 ("a lipid with a carbohydrate chain attached", "gl", "A lipid with a carbohydrate chain"),
 ("sits in the outer layer", "outer", "Lipid part: outer layer"),
 ("its tails in the core", "tails", "Its tails in the core"),
 ("projects from the outer surface", "project", "The chain projects from the outer surface"),
 ("Carbohydrate chains are hydrophilic", "hphil", "Carbohydrate chains are hydrophilic"),
 ("stays out of the hydrophobic core", "out", "Out of the hydrophobic core"),
 ("not into the cytoplasm", "notcyto", "Chains on the outer face"),
],
10: [
 ("Then glycoproteins", "open", "Then: glycoproteins"),
 ("proteins with carbohydrate chains attached", "gp", "Proteins with carbohydrate chains"),
 ("Some of the proteins you've already placed", "some", "Some are already placed"),
 ("This receptor carries a short chain", "rchain", "The receptor: a short chain"),
 ("this protein at the end carries a longer one", "gprot", "A glycoprotein with a longer chain"),
 ("Their protein parts sit in the bilayer", "parts", "Protein parts in the bilayer"),
 ("project from the outer surface", "project", "Chains project from the outer surface"),
 ("just like the glycolipid's", "likegl", "Three chains, all on the outer face"),
 ("Not every membrane protein carries a chain", "notevery", "Not every protein carries a chain"),
 ("the channel and the carrier don't", "nochain", ""),
],
11: [
 ("Step back", "open", "The whole membrane"),
 ("look at the whole membrane", "whole", ""),
 ("Every carbohydrate chain in it", "chains", "Every chain in our membrane"),
 ("on the top face, outside the cell", "top", "All on the top face, outside the cell"),
 ("none faces the cytoplasm", "none", "None faces the cytoplasm"),
 ("Cholesterol is in both layers", "chol", "Cholesterol: both layers"),
 ("the glycolipid is in the outer layer", "gl", "Glycolipid: outer layer"),
 ("As a description you could write", "desc", "A description you could write"),
 ("towards the heads", "c1", "Clause 1: cholesterol"),
 ("project from the outer surface of the membrane", "c2", "Clause 2: the carbohydrate chains"),
],
12: [
 ("So here's what I told you", "open", "What I told you"),
 ("on the membrane you watched being built", "settle", ""),
 ("Phospholipids form a bilayer", "bilayer", "Phospholipids form a bilayer"),
 ("hydrophobic tails are held together in the core", "core", "Tails held together in the core"),
 ("Intrinsic proteins are embedded in it", "intrinsic", "Intrinsic proteins: embedded"),
 ("the four spanning proteins drawn here", "four", "Four transmembrane proteins drawn here"),
 ("An extrinsic protein sits on a surface", "extrinsic", "An extrinsic protein on a surface"),
 ("can move sideways: fluid", "fluid", "Fluid"),
 ("scattered through it: mosaic", "mosaic", "Mosaic"),
 ("Cholesterol sits in both layers", "chol", "Cholesterol in both layers"),
 ("carry their chains on the outer face", "chains", "Chains on the outer face"),
],
13: [
 ("How does this reach you?", "open", "How it is asked"),
 ("In March twenty twenty-four, Paper twenty-two", "row1", "March 2024, Paper 22: cholesterol's orientation"),
 ("linked to its polar and non-polar parts", "link", "Linked to its polar and non-polar parts"),
 ("checks the cholesterol part of this lesson", "part", "Checks the cholesterol part only"),
 ("the syllabus asks you to describe", "row2", "The syllabus: describe the model"),
 ("The reject card", "reject", "The reject card (our wording contrast)"),
 ("the red blood cell in its plasma", "rbc", "Back to the red blood cell"),
 ("sit where each part interacts best", "best", "Each part where it interacts best"),
 ("tails together in the core", "tick", "Why it holds together in water"),
],
}
