"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered", "open", "Split in two, with a full copy each?"),
 ("can split into two", "split", ""),
 ("half the instructions", "half", "Full copy in each?"),
 ("deepest layer of your skin", "skin", "Deepest layer of the skin"),
 ("replacing cells lost from the surface", "replace", "Replacing cells lost from the surface"),
 ("a full copy of the genetic information", "full", "Same genetic information in each"),
 ("copy everything", "copy", "Copy"),
 ("share it out", "share", "Copy · share"),
 ("then split", "splitI", "Copy · share · split"),
 ("the mitotic cell cycle", "title", "The mitotic cell cycle"),
],
2: [
 ("By the end", "open", "What you will be able to do"),
 ("outline the cycle", "l1", ""),
 ("then mitosis and cytokinesis", "turn", ""),
 ("place DNA replication", "l2", ""),
 ("read it on a graph", "graph", ""),
 ("keep mitosis and cytokinesis apart", "l3", ""),
],
3: [
 ("Here is the routine as a loop", "ring", "The loop, read clockwise from the top"),
 ("Interphase comes first", "inter", "Interphase first"),
 ("G one, S and G two", "g1s", "Interphase: G1, S, G2"),
 ("division of the nucleus", "m", "M: mitosis, nuclear division"),
 ("division of the cytoplasm", "c", "C: cytokinesis, division of the cytoplasm"),
 ("go round again", "lap", "Each new cell can go round again"),
 ("The arcs are schematic", "schem", "Schematic proportions"),
 ("typically the longest part", "longest", "Interphase: typically the longest part"),
],
4: [
 ("Follow one chromosome", "inset", "Follow one chromosome (C1)"),
 ("the cell grows", "g1", "G1: growth"),
 ("making proteins and organelles", "prot", "Proteins and organelles"),
 ("long, thin and spread out", "thin", "Long, thin, spread out"),
 ("too fine to pick out", "fine", "Not individually visible"),
 ("one DNA molecule wound around histone proteins", "z1", "One DNA molecule, with histones"),
 ("on the graph", "graph", "DNA mass per cell"),
 ("holds steady at one unit", "flat1", "G1: steady at 1 unit"),
],
5: [
 ("Next", "open", "Next: S"),
 ("the synthesis phase", "s", "S: DNA replication (synthesis)"),
 ("As copying proceeds", "rep", "Replication in progress"),
 ("the DNA mass per cell rises", "rise", "The DNA mass per cell rises"),
 ("drawn as a slope because replication takes time", "slope", "A slope: replication takes time"),
 ("the straight line is schematic", "note", "The straight line is schematic"),
 ("By the end of the S phase", "send", "End of S: replication complete"),
 ("two sister chromatids", "sisters", "Two sister chromatids"),
 ("joined at the centromere", "cen", ""),
 ("still one chromosome, two DNA molecules", "one", "Still one chromosome, two DNA molecules"),
 ("Our model cell now has", "model", "Model cell: 4 chromosomes · 8 DNA molecules"),
 ("a typical diploid human body cell", "human", "Typical human cell: 46 · 92"),
],
6: [
 ("G two brings more growth", "g2", "G2: growth, preparation for division"),
 ("the graph stays at two units", "flat2", "Stays at 2 units"),
 ("what has not happened yet", "notyet", "Not yet condensed"),
 ("still long and thin", "thin", "Replicated, still long and thin"),
 ("They become visible as separate chromosomes later", "later", "They condense at the start of mitosis"),
 ("Keep that order in mind", "order", "Copied (S) → still thin (G2) → condenses (M)"),
],
7: [
 ("Now mitosis", "m", "M: mitosis, nuclear division"),
 ("The chromosome condenses", "cond", "The chromosome condenses"),
 ("Spindle fibres attach", "fib", "Spindle fibres attach at the centromere"),
 ("lines up at the equator", "eq", "Lined up at the equator"),
 ("the centromere divides", "div", "The centromere divides"),
 ("separate to opposite poles", "move", "Daughter chromosomes to opposite poles"),
 ("At each pole they decondense", "nuc", "Two new nuclei form"),
 ("eight daughter chromosomes in the whole model cell", "w8", "Whole cell: 8 · 8"),
 ("four in each new nucleus", "n4", "Each new nucleus: 4 · 4"),
 ("stays at two units", "flatm", "DNA per cell: still 2 units"),
],
8: [
 ("Then cytokinesis", "c", "C: cytokinesis, division of the cytoplasm"),
 ("usually follows mitosis", "order", "Usually follows mitosis"),
 ("commonly starts while mitosis is finishing", "overlap", "They can overlap"),
 ("The cytoplasm divides around the two nuclei", "pinch", "The cytoplasm divides"),
 ("giving two daughter cells", "split", "Two daughter cells"),
 ("Only now does this per-cell graph drop", "drop", "Only now the per-cell graph drops"),
 ("half the doubled DNA", "half", "2 units ÷ 2 cells = 1 unit each"),
 ("four chromosomes and four DNA molecules in the model", "d4", "Each daughter cell: 4 · 4"),
 ("forty-six and forty-six", "d46", "Human: 46 · 46 each"),
 ("in the human case$", "next", "Each daughter cell can go round again"),
],
9: [
 ("Think of it as", "open", "The handle"),
 ("a copy-then-share routine", "handle", "A copy-then-share routine (the handle)"),
 ("Written properly", "written", "Written properly"),
 ("DNA is replicated during the S phase of interphase", "cl1", ""),
 ("mitosis then separates the copies into two nuclei", "cl2", ""),
 ("cytokinesis divides the cytoplasm", "cl3", ""),
 ("genetically identical to the parent", "ident", "Same bands on both copies"),
 ("why the loop exists", "why", "Why the loop exists: growth, replacement"),
],
10: [
 ("Here is an answer that would lose the mark", "open", "An answer that would lose the mark"),
 ("Our framing", "q", "Our framing of the question"),
 ("Read this answer", "card", "Read this answer"),
 ("Look at the word prophase here", "ring1", "The word 'prophase'"),
 ("the word appear", "ring2", "…and 'appear'"),
 ("when you first see a replicated chromosome", "seen", "First SEEN in prophase"),
 ("seeing is not copying", "split", "Seen is not copied"),
 ("On the graph", "graph", "On the graph"),
 ("already doubled across the S phase", "doubled", "Already doubled across S"),
 ("In prophase the chromosomes condense", "condense", "Prophase: they condense"),
 ("copied earlier, while long and thin", "earlier", "Copied earlier, long and thin"),
 ("The question asks where replication happens", "where", "Where does replication happen?"),
 ("name that phase in full", "tabs", "Name the phase in full"),
 ("a bare letter S was ignored", "bare", ""),
 ("both interphase and S phase", "both", ""),
 ("So, in place", "fix", "Corrected in place"),
 ("during the S, or synthesis, phase of interphase", "fix2", ""),
 ("phase of interphase$", "done", "DNA replication: the S phase of interphase"),
],
11: [
 ("One more thing", "open", "One more thing"),
 ("read the axis label first", "axis", "Read the axis label first"),
 ("Ours plots DNA mass per cell", "cell", "Ours: DNA mass per cell"),
 ("Some graphs plot DNA per nucleus instead", "pn", "Some: DNA mass per nucleus"),
 ("the drop comes earlier", "earlier", "The drop comes earlier"),
 ("when the two new nuclei form", "nuclei", "When the two new nuclei form"),
 ("not when the cell divides", "notcell", "Same cell, different axis"),
 ("no intact nucleus to measure", "hatch", "No intact nucleus: hatched"),
 ("hatched as schematic", "hatch2", ""),
],
12: [
 ("Here is an answer that would lose the marks", "open", "An answer that would lose the marks"),
 ("Our framing", "q", "Our framing of the question"),
 ("Read this answer", "card", "Read this answer"),
 ("Look at the words DNA replication here", "ring1", "'DNA replication'"),
 ("and cytokinesis here", "ring2", "…and 'cytokinesis'"),
 ("both processes use energy", "energy", "Both use energy; both are in the cycle"),
 ("the cycle you have just followed", "wheel", ""),
 ("the question asks about mitosis", "scope", "The question's scope: M"),
 ("replication in the S phase", "outS", "Replication: outside M"),
 ("cytokinesis in the C arc", "outC", "Cytokinesis: outside M"),
 ("For this two-mark question", "tab", "The mark scheme's ignore line"),
 ("ignore references to replication or cytokinesis", "ign", ""),
 ("That is not a claim that ATP goes unused there", "bound", "A local ignore line"),
 ("neither point on this card gains credit", "zero", "0 credited points here"),
 ("So answer inside the M arc", "inside", "Answer inside the M arc"),
 ("In place", "fix", "Corrected in place"),
 ("spindle formation", "fix1", "Spindle formation"),
 ("movement of daughter chromosomes to opposite poles", "move", ""),
 ("to opposite poles$", "fix2", "…and movement of daughter chromosomes"),
],
13: [
 ("Here it is", "open", "What I told you"),
 ("on the wheel and graph you built", "settle", ""),
 ("G one: growth", "g1", ""),
 ("one unit of DNA per cell", "u1", ""),
 ("The S phase of interphase", "s", ""),
 ("the trace rising to two", "rise", ""),
 ("each chromosome now two sister chromatids", "sis", ""),
 ("G two: more growth", "g2", ""),
 ("one nucleus becomes two", "m", ""),
 ("the cytoplasm divides", "c", ""),
 ("back to one unit", "back", ""),
],
14: [
 ("How this reaches you", "forms", "How it is asked"),
 ("which stage of interphase replication happens in", "r1", ""),
 ("crediting the S phase or synthesis phase", "r1b", ""),
 ("circle both interphase and S phase", "r2", ""),
 ("Multiple-choice items track DNA mass", "r3", ""),
 ("the role of ATP in mitosis", "r4", ""),
 ("The reject card", "card", "The reject card"),
 ("And the hook", "hook", "And the hook?"),
 ("a full set of genetic information", "full", "A full genetic set in each"),
 ("copied first", "copied", "Copied first…"),
 ("shared between the two cells", "shared", "…then shared"),
 ("the two cells$", "exit", ""),
],
}
