"""Cue plan: (exact narration phrase, key, caption). The storyboard's cues, plus an opening cue where the
storyboard's first cue is not the beat's first words (recorded in qa/cue-additions.md). '^' marks the
trigger word inside a phrase that is matched whole for uniqueness; a trailing '$' triggers at the END of
the phrase's last spoken word. An empty caption keeps the previous caption. Captions are look-here
anchors, never the narration re-typed. Matching is case-normalised, so every phrase is unique in its beat."""
PLANS = {
1: [
 ("Ever wondered how", "open", "Copied again and again, genes kept?"),
 ("losing the genes near its ends", "ends", "The genes near the ends"),
 ("Plenty of your cells", "strips", "Cells that keep dividing"),
 ("your gut lining", "gut", "Gut lining"),
 ("the base layer of your skin", "skin", "Skin: base layer"),
 ("worn-out cells are replaced", "replace", "Worn-out cells replaced"),
 ("the DNA is copied", "copied", "Before each division, the DNA is copied"),
 ("typical dividing body cells", "mag", "Typical dividing body cells"),
 ("a little shorter", "short", "A little shorter each round"),
 ("each round of copying", "q", "So what protects the genes?"),
],
2: [
 ("when does that copying happen", "wheel", "When is the DNA copied? (recall: 5.1.3)"),
 ("S phase of interphase", "s", "The S (synthesis) phase of interphase"),
 ("before mitosis begins", "m", "Before mitosis begins"),
 ("During the S phase", "rep", "Replication during S"),
 ("two identical sister chromatids", "sisters", "Two identical sister chromatids"),
 ("joined at a centromere", "cen", ""),
 ("still one chromosome", "one", "Still one chromosome"),
 ("a telomere at each of its four ends", "four", "A telomere at each of the four ends"),
],
3: [
 ("By the end", "open", "What you will be able to do"),
 ("say what a telomere is", "l1", ""),
 ("describe what happens at a chromosome end", "l2", ""),
 ("outline how telomeres prevent the loss of genes", "l3", ""),
],
4: [
 ("Zoom in on one end", "zoom", "Zoom in on one chromatid end"),
 ("Here is its DNA as a simple strip", "dna", "DNA as a simple strip"),
 ("two genes near the end", "genes", "Two genes near the end"),
 ("Beyond the last gene comes the telomere", "tel", "Beyond the last gene: the telomere"),
 ("one short DNA sequence", "seq", "One short DNA sequence…"),
 ("repeated over and over", "rep", "…repeated over and over"),
 ("In humans the repeat is", "ttaggg", "In humans: TTAGGG"),
 ("doesn't code for a protein", "noncoding", "Repeated, non-coding DNA"),
 ("between the genes and the very tip", "tip", "Between the genes and the tip"),
],
5: [
 ("copy this molecule", "copy", "Copy the molecule"),
 ("watch the end", "end", "Watch the end"),
 ("The new copy grows along the old one", "grow1", "Round 1: the copy grows"),
 ("stops a little short of the tip", "stop1", "…and stops short of the tip"),
 ("the daughter molecule's end is shorter", "swap1", "The daughter molecule's end is shorter"),
 ("The next round starts", "grow2", "Round 2"),
 ("stops shorter again", "stop2", "Shorter again"),
 ("typical dividing somatic cells", "r3", "Typical dividing somatic cells"),
 ("what goes is telomere", "lost", "Lost from the telomere"),
 ("both genes are untouched", "genes", "Genes intact"),
 ("Some cells maintain their telomeres", "maintain", "Some cells maintain their telomeres"),
],
6: [
 ("Now a thought experiment", "thought", "Thought experiment — not a real chromosome"),
 ("take the telomere away", "away", "No telomere (thought experiment)"),
 ("run the same rounds", "rounds", "The same rounds"),
 ("The shortening end reaches the gene nearest the tip", "reach", "The end reaches the gene"),
 ("would lack part of that gene", "lack", "Part of a gene not copied (thought experiment)"),
 ("Put the telomere back", "back", "Back to the real chromosome"),
 ("a buffer at the end of the line", "handle", "The handle: a buffer at the end of the line"),
 ("Written properly", "written", "Written properly"),
 ("repeated non-coding DNA at chromosome ends", "s1", ""),
 ("In typical dividing somatic cells", "s2", ""),
 ("shortening during repeated replication", "ticks", ""),
 ("initially removes telomeric DNA", "removes", ""),
 ("protecting nearby genes", "protect", ""),
],
7: [
 ("So here is what I told you", "open", "What I told you"),
 ("on the end you watched", "settle", ""),
 ("A telomere is repeated, non-coding DNA", "what", ""),
 ("each chromosome end", "ends", ""),
 ("S phase of interphase", "s", ""),
 ("In our model of a typical dividing somatic cell", "typ", ""),
 ("the end shortens over successive rounds", "ticks", ""),
 ("initially losing telomeric DNA", "lost", ""),
 ("keeping the nearby genes intact", "genes", ""),
],
8: [
 ("How is this asked", "forms", "How it is asked"),
 ("The command word is outline", "outline", "Outline: short, but keep the link"),
 ("keep the link", "link", ""),
 ("A cloze on DNA replication", "row1", "A cloze: name the structure"),
 ("repeated sequences at the chromosome ends", "rep", ""),
 ("the answer was telomeres", "ans", "Answer: telomeres"),
 ("Multiple-choice questions", "row2", "Multiple choice"),
 ("more divisions to shorter telomeres", "ticks", ""),
 ("possibly stopping division", "row3", "A cell may stop dividing"),
 ("And the hook", "hook", "And the hook?"),
 ("copying leaves a shorter telomere", "copy", ""),
 ("the nearby genes remain intact", "genes", "Nearby genes intact"),
 ("remain intact$", "card", "The reject card"),
],
}
